// Shared question bank for Candlelight.
// Server uses this for grading. Client gets questions with answers stripped.

export const BANK = {
  trivia:[
    {q:"What form does Harry's Patronus take?",o:["A stag","A doe","An otter","A jack russell terrier"],a:0},
    {q:"What is the core of Harry's first wand?",o:["Dragon heartstring","Unicorn hair","Phoenix feather","Thestral tail hair"],a:2},
    {q:"What is Voldemort's birth name?",o:["Tom Marvolo Riddle","Marvolo Gaunt","Thomas Slytherin","Tom Gaunt Riddle"],a:0},
    {q:"Which potion grants the drinker good luck?",o:["Amortentia","Veritaserum","Felix Felicis","Draught of Peace"],a:2},
    {q:"What kind of creature is Aragog?",o:["An Acromantula","A Nundu","A Quintaped","A Doxy"],a:0},
    {q:"How many points is the Golden Snitch worth?",o:["50","100","150","200"],a:2},
    {q:"How many players are on a Quidditch team?",o:["Five","Six","Seven","Nine"],a:2},
    {q:"Which dragon did Harry face in the first Triwizard task?",o:["Chinese Fireball","Hungarian Horntail","Swedish Short-Snout","Welsh Green"],a:1},
    {q:"Who killed Bellatrix Lestrange?",o:["Neville Longbottom","Molly Weasley","Ginny Weasley","Minerva McGonagall"],a:1},
    {q:"What does S.P.E.W. stand for?",o:["Society for the Protection of Enchanted Wildlife","Society for the Promotion of Elfish Welfare","Students Protesting Elf Work","Society for Practical Elfish Wages"],a:1},
    {q:"Which object did Dumbledore leave Harry in his will?",o:["The Sword of Gryffindor","A Deluminator","The first Snitch he ever caught","A copy of The Tales of Beedle the Bard"],a:2},
    {q:"What animal represents Hufflepuff house?",o:["A badger","A raven","An otter","A boar"],a:0},
    {q:"Which teacher turns out to be the Half-Blood Prince?",o:["Horace Slughorn","Remus Lupin","Severus Snape","Filius Flitwick"],a:2},
    {q:"What destroyed the Basilisk in the Chamber of Secrets?",o:["The Sword of Gryffindor","A rooster's crow","Fawkes' tears","A Killing Curse"],a:0},
    {q:"Where do the Weasleys live?",o:["Shell Cottage","Spinner's End","The Burrow","Godric's Hollow"],a:2},
    {q:"Which platform does the Hogwarts Express leave from?",o:["Nine and a half","Nine and three-quarters","Ten and a quarter","Seven and three-quarters"],a:1},
    {q:"Who teaches Herbology at Hogwarts?",o:["Pomona Sprout","Charity Burbage","Wilhelmina Grubbly-Plank","Septima Vector"],a:0},
    {q:"How many Horcruxes did Voldemort deliberately create?",o:["Five","Six","Seven","Eight"],a:1},
    {q:"What is the wizarding newspaper of Britain called?",o:["The Quibbler","Witch Weekly","The Daily Prophet","The Evening Seer"],a:2},
    {q:"Which house ghost is the Grey Lady?",o:["Gryffindor","Ravenclaw","Hufflepuff","Slytherin"],a:1},
    {q:"What is the highest-value wizarding coin?",o:["Knut","Sickle","Galleon","Sovereign"],a:2},
    {q:"What kind of creature is Dobby?",o:["A goblin","A house-elf","A gnome","A leprechaun"],a:1},
    {q:"Which two schools competed against Hogwarts in the Triwizard Tournament?",o:["Ilvermorny and Mahoutokoro","Beauxbatons and Durmstrang","Castelobruxo and Uagadou","Durmstrang and Ilvermorny"],a:1},
    {q:"What does the Marauder's Map reveal?",o:["Hidden passages only","Everyone's location inside Hogwarts","Dark objects nearby","The future"],a:1},
    {q:"Which Marauder went by the nickname Padfoot?",o:["Remus Lupin","James Potter","Sirius Black","Peter Pettigrew"],a:2},
    {q:"What subject did Snape teach for most of Harry's school years?",o:["Potions","Defence Against the Dark Arts","Transfiguration","Charms"],a:0},
    {q:"What is Hagrid's three-headed dog called?",o:["Fang","Fluffy","Norbert","Cerberus"],a:1},
    {q:"Which creature can only be seen by someone who has witnessed death?",o:["A Hippogriff","A Thestral","A Nifflers","A Boggart"],a:1},
    {q:"What does a Boggart become when it is defeated?",o:["Invisible","Something laughable","A cloud of smoke","A mirror"],a:1},
    {q:"Which Weasley brother works with dragons in Romania?",o:["Bill","Charlie","Percy","Fred"],a:1},
    {q:"What was Tom Riddle's diary a fragment of?",o:["A curse","A Horcrux","A Pensieve","A Portkey"],a:1},
    {q:"Who was the Hogwarts caretaker?",o:["Argus Filch","Rubeus Hagrid","Aberforth Dumbledore","Amos Diggory"],a:0},
    {q:"What is Hermione's cat named?",o:["Crookshanks","Mrs Norris","Scabbers","Pigwidgeon"],a:0},
    {q:"Which shop sells wands in Diagon Alley?",o:["Flourish and Blotts","Ollivanders","Borgin and Burkes","Madam Malkin's"],a:1},
    {q:"What is the name of the wizarding prison?",o:["Nurmengard","Azkaban","Gringotts","Grimmauld"],a:1},
    {q:"Which spell is known as the Killing Curse?",o:["Crucio","Imperio","Avada Kedavra","Morsmordre"],a:2},
    {q:"Who founded Dumbledore's Army?",o:["Harry, Ron and Hermione","Neville and Luna","The Order of the Phoenix","Fred and George"],a:0},
    {q:"What was Lupin's condition?",o:["He was a werewolf","He was a vampire","He was an Animagus","He was a Squib"],a:0},
    {q:"What does a Pensieve store?",o:["Potions","Memories","Prophecies","Souls"],a:1},
    {q:"Who won the Triwizard Tournament alongside Harry?",o:["Viktor Krum","Fleur Delacour","Cedric Diggory","Nobody"],a:2},
    {q:"Which magical creature guards the deepest Gringotts vaults?",o:["A dragon","A Sphinx","A Chimaera","Goblin warriors"],a:0},
    {q:"What is Neville's toad called?",o:["Trevor","Errol","Arnold","Nagini"],a:0},
    {q:"Which room appears only when someone truly needs it?",o:["The Chamber of Secrets","The Room of Requirement","The Restricted Section","The Great Hall"],a:1},
    {q:"What is the name of the pub that hides the entrance to Diagon Alley?",o:["The Three Broomsticks","The Hog's Head","The Leaky Cauldron","The Green Dragon"],a:2},
  ],
  tf:[
    {q:"Hedwig is a snowy owl.",a:true},
    {q:"Peeves is a ghost.",a:false,note:"He's a poltergeist — never alive to begin with."},
    {q:"Argus Filch is a Squib.",a:true},
    {q:"Fawkes is a griffin.",a:false,note:"Fawkes is a phoenix."},
    {q:"Sirius Black is Harry's godfather.",a:true},
    {q:"Draco Malfoy was sorted into Ravenclaw.",a:false,note:"Slytherin, and instantly."},
    {q:"Moaning Myrtle haunts a girls' bathroom.",a:true},
    {q:"Hagrid was expelled from Hogwarts as a student.",a:true},
    {q:"Nagini is Voldemort's cat.",a:false,note:"Nagini is a snake."},
    {q:"Dementors guard Azkaban.",a:true},
    {q:"Firenze the centaur taught Divination.",a:true},
    {q:"The Knight Bus is triple-decker and purple.",a:true},
    {q:"Umbridge decorates her office with kitten plates.",a:true},
    {q:"Butterbeer is sold at the Three Broomsticks.",a:true},
    {q:"Viktor Krum attended Beauxbatons.",a:false,note:"Durmstrang."},
    {q:"Luna Lovegood is a Ravenclaw.",a:true},
    {q:"The Whomping Willow hides a passage to Hogsmeade.",a:true},
    {q:"Cho Chang played Beater for Ravenclaw.",a:false,note:"She was a Seeker."},
    {q:"Bill Weasley worked as a curse-breaker for Gringotts.",a:true},
    {q:"A Niffler is attracted to anything shiny.",a:true},
    {q:"Godric's Hollow is where Harry's parents died.",a:true},
    {q:"Slughorn was Head of Ravenclaw house.",a:false,note:"Slytherin."},
  ],
  spells:[
    {s:"Expelliarmus",e:"Disarms your opponent"},
    {s:"Lumos",e:"Lights the wand tip"},
    {s:"Nox",e:"Puts out wandlight"},
    {s:"Alohomora",e:"Unlocks doors"},
    {s:"Wingardium Leviosa",e:"Makes an object float"},
    {s:"Expecto Patronum",e:"Conjures a Patronus"},
    {s:"Riddikulus",e:"Defeats a Boggart"},
    {s:"Accio",e:"Summons an object to you"},
    {s:"Obliviate",e:"Erases memories"},
    {s:"Reparo",e:"Mends broken things"},
    {s:"Petrificus Totalus",e:"Freezes the body rigid"},
    {s:"Protego",e:"Raises a shield"},
    {s:"Episkey",e:"Heals small injuries"},
    {s:"Silencio",e:"Silences the target"},
    {s:"Confundo",e:"Confuses the target"},
    {s:"Aguamenti",e:"Produces a jet of water"},
    {s:"Incendio",e:"Starts a fire"},
    {s:"Levicorpus",e:"Dangles the target by an ankle"},
    {s:"Muffliato",e:"Fills nearby ears with buzzing"},
    {s:"Sectumsempra",e:"Slashes deep wounds"},
    {s:"Rictusempra",e:"Sets the target laughing"},
    {s:"Engorgio",e:"Makes something swell in size"},
  ],
  scramble:[
    {w:"PATRONUS",h:"Conjured by a happy memory"},
    {w:"HORCRUX",h:"A hidden fragment of a soul"},
    {w:"THESTRAL",h:"Only the bereaved can see them"},
    {w:"PENSIEVE",h:"A stone basin of memories"},
    {w:"PARSELTONGUE",h:"The language of snakes"},
    {w:"GRINGOTTS",h:"Run by goblins"},
    {w:"HOGSMEADE",h:"The all-wizarding village"},
    {w:"ANIMAGUS",h:"A witch who becomes an animal at will"},
    {w:"BUTTERBEER",h:"Warm, foamy, faintly alcoholic"},
    {w:"QUIDDITCH",h:"Played on broomsticks"},
    {w:"BASILISK",h:"Its gaze kills"},
    {w:"DEMENTOR",h:"It feeds on happiness"},
    {w:"GRYFFINDOR",h:"Lion, scarlet and gold"},
    {w:"RAVENCLAW",h:"Eagle, blue and bronze"},
    {w:"HUFFLEPUFF",h:"Badger, yellow and black"},
    {w:"SLYTHERIN",h:"Serpent, green and silver"},
    {w:"AZKABAN",h:"An island you don't leave"},
    {w:"PORTKEY",h:"An ordinary object that yanks you away"},
    {w:"OCCLUMENCY",h:"Sealing the mind against intrusion"},
    {w:"HIPPOGRIFF",h:"Bow before you approach one"},
    {w:"VERITASERUM",h:"Three drops and you'll tell the truth"},
    {w:"DEATHSTICK",h:"Another name for the Elder Wand"},
  ],
  odd:[
    {items:["Gryffindor","Slytherin","Ravenclaw","Durmstrang"],a:3,why:"Durmstrang is a school, not a Hogwarts house."},
    {items:["Quaffle","Bludger","Snitch","Portkey"],a:3,why:"A Portkey isn't a Quidditch ball."},
    {items:["Moony","Wormtail","Padfoot","Nagini"],a:3,why:"The other three are Marauders' nicknames."},
    {items:["The diary","The locket","The cup","The Sorting Hat"],a:3,why:"The Sorting Hat was never a Horcrux."},
    {items:["Hedwig","Errol","Pigwidgeon","Crookshanks"],a:3,why:"Crookshanks is a cat; the rest are owls."},
    {items:["Lumos","Incendio","Protego","Felix Felicis"],a:3,why:"Felix Felicis is a potion, not a spell."},
    {items:["Fang","Fluffy","Aragog","Fawkes"],a:3,why:"Fawkes was Dumbledore's; the rest were Hagrid's."},
    {items:["Snape","McGonagall","Flitwick","Ollivander"],a:3,why:"Ollivander never taught at Hogwarts."},
    {items:["Elder Wand","Invisibility Cloak","Resurrection Stone","Time-Turner"],a:3,why:"A Time-Turner isn't a Deathly Hallow."},
    {items:["Beauxbatons","Durmstrang","Hogwarts","Ilvermorny"],a:3,why:"Ilvermorny didn't compete in the Triwizard Tournament."},
    {items:["Fred","George","Percy","Cedric"],a:3,why:"Cedric isn't a Weasley."},
    {items:["Dementor","Boggart","Thestral","Patronus"],a:3,why:"A Patronus is a charm, not a creature."},
    {items:["Galleon","Sickle","Knut","Florin"],a:3,why:"There's no wizarding Florin."},
    {items:["Quirrell","Lockhart","Lupin","Slughorn"],a:3,why:"Slughorn taught Potions, not Defence Against the Dark Arts."},
    {items:["Bill","Charlie","Ginny","Tonks"],a:3,why:"Tonks was born a Black, not a Weasley."},
    {items:["Amortentia","Polyjuice","Veritaserum","Deluminator"],a:3,why:"A Deluminator is a device, not a potion."},
  ],
  whoami:[
    {clues:["I was a half-blood, and I was bullied at school.","I taught Potions long before I taught anything else.","My Patronus was a doe."],o:["Severus Snape","Horace Slughorn","Regulus Black","Barty Crouch Jr"],a:0},
    {clues:["I was clumsy, and nobody expected much of me.","My grandmother raised me and never let me forget my parents.","I killed the last Horcrux with a sword."],o:["Seamus Finnigan","Neville Longbottom","Dean Thomas","Colin Creevey"],a:1},
    {clues:["I served a cruel family for years.","A single sock changed my life.","I died protecting children I chose to help."],o:["Kreacher","Winky","Dobby","Hokey"],a:2},
    {clues:["I was a champion nobody resented.","I played Seeker for my house.","I died in a graveyard, first."],o:["Cedric Diggory","Viktor Krum","Roger Davies","Ernie Macmillan"],a:0},
    {clues:["I can change my appearance at will.","I trained as an Auror.","I married a man who thought he was too dangerous to love."],o:["Emmeline Vance","Hestia Jones","Nymphadora Tonks","Alice Longbottom"],a:2},
    {clues:["I was Head Girl in my year.","I had red hair and green eyes.","My death left a protection nobody could break."],o:["Molly Weasley","Lily Potter","Marlene McKinnon","Mary Macdonald"],a:1},
    {clues:["I spent twelve years somewhere very cold.","I am an unregistered Animagus.","I am the closest thing Harry had to a father."],o:["Remus Lupin","Alastor Moody","Sirius Black","Kingsley Shacklebolt"],a:2},
    {clues:["I run a shop built on laughter.","I had an identical twin.","I lost an ear and made a joke about it."],o:["Fred Weasley","George Weasley","Lee Jordan","Percy Weasley"],a:1},
    {clues:["I am a ghost, and the daughter of a founder.","I stole from my mother and regretted it forever.","My diadem became something monstrous."],o:["The Fat Friar","Helena Ravenclaw","Moaning Myrtle","The Bloody Baron"],a:1},
    {clues:["People called me odd and I never minded.","I believe in creatures most wizards deny.","My father printed a paper nobody trusted."],o:["Luna Lovegood","Padma Patil","Susan Bones","Hannah Abbott"],a:0},
    {clues:["I was once the most feared wizard in Europe.","A childhood friend eventually defeated me.","I died in a prison I built myself."],o:["Voldemort","Gellert Grindelwald","Herpo the Foul","Ekrizdis"],a:1},
  ],
  sorting:[
    {n:"Luna Lovegood",h:"Ravenclaw"},{n:"Cedric Diggory",h:"Hufflepuff"},
    {n:"Draco Malfoy",h:"Slytherin"},{n:"Neville Longbottom",h:"Gryffindor"},
    {n:"Cho Chang",h:"Ravenclaw"},{n:"Nymphadora Tonks",h:"Hufflepuff"},
    {n:"Bellatrix Lestrange",h:"Slytherin"},{n:"Ginny Weasley",h:"Gryffindor"},
    {n:"Filius Flitwick",h:"Ravenclaw"},{n:"Pomona Sprout",h:"Hufflepuff"},
    {n:"Horace Slughorn",h:"Slytherin"},{n:"Minerva McGonagall",h:"Gryffindor"},
    {n:"Gilderoy Lockhart",h:"Ravenclaw"},{n:"Newt Scamander",h:"Hufflepuff"},
    {n:"Regulus Black",h:"Slytherin"},{n:"Sirius Black",h:"Gryffindor"},
    {n:"Padma Patil",h:"Ravenclaw"},{n:"Justin Finch-Fletchley",h:"Hufflepuff"},
    {n:"Dolores Umbridge",h:"Slytherin"},{n:"Seamus Finnigan",h:"Gryffindor"},
    {n:"Moaning Myrtle",h:"Ravenclaw"},{n:"Susan Bones",h:"Hufflepuff"},
    {n:"Marcus Flint",h:"Slytherin"},{n:"Colin Creevey",h:"Gryffindor"},
  ],
  sequence:[
    {t:"Order the Triwizard tasks",items:["Retrieve a golden egg from a dragon","Rescue a hostage from the Black Lake","Reach the cup at the heart of the maze"]},
    {t:"Order these Horcruxes by when they were destroyed",items:["Tom Riddle's diary","Marvolo's ring","Slytherin's locket","Hufflepuff's cup","Ravenclaw's diadem","Nagini"]},
    {t:"Order the wizarding coins, smallest value first",items:["Knut","Sickle","Galleon"]},
    {t:"Order the Defence Against the Dark Arts teachers by Harry's school years",items:["Quirinus Quirrell","Gilderoy Lockhart","Remus Lupin","'Alastor Moody'","Dolores Umbridge"]},
    {t:"Order these events in Harry's first year",items:["A letter arrives by owl","A visit to Ollivanders","The Sorting Hat's decision","Facing the mirror in the chamber below"]},
    {t:"Order Harry's brooms, earliest first",items:["School broom","Nimbus 2000","Firebolt"]},
    {t:"Order these by size, smallest first",items:["A Snitch","A Bludger","A Quaffle"]},
    {t:"Order the stages of the Second Wizarding War",items:["Voldemort returns in a graveyard","The Ministry denies everything","Dumbledore falls from the tower","The Battle of Hogwarts"]},
  ],
};

export const HOUSES=["Gryffindor","Slytherin","Ravenclaw","Hufflepuff"];
export const HOUSE_SUB={Gryffindor:"Lion",Slytherin:"Serpent",Ravenclaw:"Eagle",Hufflepuff:"Badger"};
