import type { CategorizeItem } from "@curio/core";

export const categorize: CategorizeItem[] = [
  { set: "continents", label: "Cairo", category: "africa" },
  { set: "continents", label: "Nairobi", category: "africa" },
  { set: "continents", label: "Lagos", category: "africa" },
  { set: "continents", label: "Marrakesh", category: "africa" },
  { set: "continents", label: "Tokyo", category: "asia" },
  { set: "continents", label: "Mumbai", category: "asia" },
  { set: "continents", label: "Seoul", category: "asia" },
  { set: "continents", label: "Tashkent", category: "asia" },
  { set: "continents", label: "Lisbon", category: "europe" },
  { set: "continents", label: "Prague", category: "europe" },
  { set: "continents", label: "Oslo", category: "europe" },
  { set: "continents", label: "Zagreb", category: "europe" },
  { set: "continents", label: "Lima", category: "americas" },
  { set: "continents", label: "Toronto", category: "americas" },
  { set: "continents", label: "Bogota", category: "americas" },
  { set: "continents", label: "Havana", category: "americas" },
  { set: "continents", label: "Auckland", category: "oceania" },
  { set: "continents", label: "Suva", category: "oceania" },
  { set: "continents", label: "Perth", category: "oceania" },
  { set: "continents", label: "Port Moresby", category: "oceania" },

  { set: "water", label: "The Caspian", category: "lake" },
  { set: "water", label: "Lake Baikal", category: "lake" },
  { set: "water", label: "Lake Victoria", category: "lake" },
  { set: "water", label: "Lake Titicaca", category: "lake" },
  { set: "water", label: "The Adriatic", category: "sea" },
  { set: "water", label: "The Baltic", category: "sea" },
  { set: "water", label: "The Coral Sea", category: "sea" },
  { set: "water", label: "The Sargasso", category: "sea" },
  { set: "water", label: "The Mekong", category: "river" },
  { set: "water", label: "The Danube", category: "river" },
  { set: "water", label: "The Orinoco", category: "river" },
  { set: "water", label: "The Zambezi", category: "river" },
];
