import type { CategorizeItem } from "@curio/core";

/** Every sorting item, tagged with the set whose buckets it belongs to. */
export const categorize: CategorizeItem[] = [
  /* ── era: 2000–2004 ── */
  { set: "era", label: "Kaho Naa... Pyaar Hai", category: "early2000s" },
  { set: "era", label: "Hera Pheri", category: "early2000s" },
  { set: "era", label: "Lagaan", category: "early2000s" },
  { set: "era", label: "Dil Chahta Hai", category: "early2000s" },
  { set: "era", label: "Kabhi Khushi Kabhie Gham", category: "early2000s" },
  { set: "era", label: "Gadar: Ek Prem Katha", category: "early2000s" },
  { set: "era", label: "Devdas", category: "early2000s" },
  { set: "era", label: "Company", category: "early2000s" },
  { set: "era", label: "Koi... Mil Gaya", category: "early2000s" },
  { set: "era", label: "Munna Bhai M.B.B.S.", category: "early2000s" },
  { set: "era", label: "Kal Ho Naa Ho", category: "early2000s" },
  { set: "era", label: "Maqbool", category: "early2000s" },
  { set: "era", label: "Dhoom", category: "early2000s" },
  { set: "era", label: "Veer-Zaara", category: "early2000s" },
  { set: "era", label: "Main Hoon Na", category: "early2000s" },
  { set: "era", label: "Swades", category: "early2000s" },

  /* ── era: 2005–2009 ── */
  { set: "era", label: "Black", category: "late2000s" },
  { set: "era", label: "Bunty Aur Babli", category: "late2000s" },
  { set: "era", label: "Sarkar", category: "late2000s" },
  { set: "era", label: "Rang De Basanti", category: "late2000s" },
  { set: "era", label: "Lage Raho Munna Bhai", category: "late2000s" },
  { set: "era", label: "Omkara", category: "late2000s" },
  { set: "era", label: "Krrish", category: "late2000s" },
  { set: "era", label: "Chak De! India", category: "late2000s" },
  { set: "era", label: "Om Shanti Om", category: "late2000s" },
  { set: "era", label: "Taare Zameen Par", category: "late2000s" },
  { set: "era", label: "Jab We Met", category: "late2000s" },
  { set: "era", label: "Guru", category: "late2000s" },
  { set: "era", label: "Rock On!!", category: "late2000s" },
  { set: "era", label: "Ghajini", category: "late2000s" },
  { set: "era", label: "Jodhaa Akbar", category: "late2000s" },
  { set: "era", label: "Rab Ne Bana Di Jodi", category: "late2000s" },
  { set: "era", label: "3 Idiots", category: "late2000s" },
  { set: "era", label: "Dev.D", category: "late2000s" },
  { set: "era", label: "Kaminey", category: "late2000s" },
  { set: "era", label: "Wake Up Sid", category: "late2000s" },

  /* ── era: 2010–2014 ── */
  { set: "era", label: "Dabangg", category: "early2010s" },
  { set: "era", label: "My Name Is Khan", category: "early2010s" },
  { set: "era", label: "Udaan", category: "early2010s" },
  { set: "era", label: "Band Baaja Baaraat", category: "early2010s" },
  { set: "era", label: "Zindagi Na Milegi Dobara", category: "early2010s" },
  { set: "era", label: "Rockstar", category: "early2010s" },
  { set: "era", label: "The Dirty Picture", category: "early2010s" },
  { set: "era", label: "Delhi Belly", category: "early2010s" },
  { set: "era", label: "Gangs of Wasseypur", category: "early2010s" },
  { set: "era", label: "Barfi!", category: "early2010s" },
  { set: "era", label: "Kahaani", category: "early2010s" },
  { set: "era", label: "Vicky Donor", category: "early2010s" },
  { set: "era", label: "Paan Singh Tomar", category: "early2010s" },
  { set: "era", label: "English Vinglish", category: "early2010s" },
  { set: "era", label: "Student of the Year", category: "early2010s" },
  { set: "era", label: "Yeh Jawaani Hai Deewani", category: "early2010s" },
  { set: "era", label: "Bhaag Milkha Bhaag", category: "early2010s" },
  { set: "era", label: "The Lunchbox", category: "early2010s" },
  { set: "era", label: "Kai Po Che!", category: "early2010s" },
  { set: "era", label: "Queen", category: "early2010s" },
  { set: "era", label: "Haider", category: "early2010s" },
  { set: "era", label: "PK", category: "early2010s" },

  /* ── era: 2015–2019 ── */
  { set: "era", label: "Bajrangi Bhaijaan", category: "late2010s" },
  { set: "era", label: "Piku", category: "late2010s" },
  { set: "era", label: "Bajirao Mastani", category: "late2010s" },
  { set: "era", label: "Masaan", category: "late2010s" },
  { set: "era", label: "Dil Dhadakne Do", category: "late2010s" },
  { set: "era", label: "Dangal", category: "late2010s" },
  { set: "era", label: "Pink", category: "late2010s" },
  { set: "era", label: "Neerja", category: "late2010s" },
  { set: "era", label: "Udta Punjab", category: "late2010s" },
  { set: "era", label: "Kapoor & Sons", category: "late2010s" },
  { set: "era", label: "Sultan", category: "late2010s" },
  { set: "era", label: "Airlift", category: "late2010s" },
  { set: "era", label: "Newton", category: "late2010s" },
  { set: "era", label: "Hindi Medium", category: "late2010s" },
  { set: "era", label: "Andhadhun", category: "late2010s" },
  { set: "era", label: "Padmaavat", category: "late2010s" },
  { set: "era", label: "Raazi", category: "late2010s" },
  { set: "era", label: "Badhaai Ho", category: "late2010s" },
  { set: "era", label: "Stree", category: "late2010s" },
  { set: "era", label: "Sanju", category: "late2010s" },
  { set: "era", label: "Gully Boy", category: "late2010s" },
  { set: "era", label: "Uri: The Surgical Strike", category: "late2010s" },

  /* ── craft ── */
  { set: "craft", label: "Hrithik Roshan", category: "acting" },
  { set: "craft", label: "Ranbir Kapoor", category: "acting" },
  { set: "craft", label: "Vidya Balan", category: "acting" },
  { set: "craft", label: "Nawazuddin Siddiqui", category: "acting" },
  { set: "craft", label: "Kangana Ranaut", category: "acting" },
  { set: "craft", label: "Rajkummar Rao", category: "acting" },
  { set: "craft", label: "Deepika Padukone", category: "acting" },
  { set: "craft", label: "Irrfan Khan", category: "acting" },
  { set: "craft", label: "Rajkumar Hirani", category: "directing" },
  { set: "craft", label: "Zoya Akhtar", category: "directing" },
  { set: "craft", label: "Anurag Kashyap", category: "directing" },
  { set: "craft", label: "Imtiaz Ali", category: "directing" },
  { set: "craft", label: "Rohit Shetty", category: "directing" },
  { set: "craft", label: "Meghna Gulzar", category: "directing" },
  { set: "craft", label: "Sujoy Ghosh", category: "directing" },
  { set: "craft", label: "Ashutosh Gowariker", category: "directing" },
  { set: "craft", label: "Arijit Singh", category: "singing" },
  { set: "craft", label: "Shreya Ghoshal", category: "singing" },
  { set: "craft", label: "Sonu Nigam", category: "singing" },
  { set: "craft", label: "Sunidhi Chauhan", category: "singing" },
  { set: "craft", label: "Mohit Chauhan", category: "singing" },
  { set: "craft", label: "Rahat Fateh Ali Khan", category: "singing" },
  { set: "craft", label: "Neha Kakkar", category: "singing" },
  { set: "craft", label: "Kailash Kher", category: "singing" },
  { set: "craft", label: "A. R. Rahman", category: "composing" },
  { set: "craft", label: "Pritam", category: "composing" },
  { set: "craft", label: "Amit Trivedi", category: "composing" },
  { set: "craft", label: "Shankar–Ehsaan–Loy", category: "composing" },
  { set: "craft", label: "Vishal–Shekhar", category: "composing" },
  { set: "craft", label: "Sneha Khanwalkar", category: "composing" },
  { set: "craft", label: "Ajay–Atul", category: "composing" },
  { set: "craft", label: "Salim–Sulaiman", category: "composing" },

  /* ── stars ── */
  { set: "stars", label: "Kal Ho Naa Ho", category: "shahrukh" },
  { set: "stars", label: "Swades", category: "shahrukh" },
  { set: "stars", label: "Chak De! India", category: "shahrukh" },
  { set: "stars", label: "Om Shanti Om", category: "shahrukh" },
  { set: "stars", label: "Rab Ne Bana Di Jodi", category: "shahrukh" },
  { set: "stars", label: "My Name Is Khan", category: "shahrukh" },
  { set: "stars", label: "Chennai Express", category: "shahrukh" },
  { set: "stars", label: "Raees", category: "shahrukh" },
  { set: "stars", label: "Tere Naam", category: "salman" },
  { set: "stars", label: "Wanted", category: "salman" },
  { set: "stars", label: "Dabangg", category: "salman" },
  { set: "stars", label: "Bodyguard", category: "salman" },
  { set: "stars", label: "Ek Tha Tiger", category: "salman" },
  { set: "stars", label: "Kick", category: "salman" },
  { set: "stars", label: "Bajrangi Bhaijaan", category: "salman" },
  { set: "stars", label: "Sultan", category: "salman" },
  { set: "stars", label: "Lagaan", category: "aamir" },
  { set: "stars", label: "Rang De Basanti", category: "aamir" },
  { set: "stars", label: "Ghajini", category: "aamir" },
  { set: "stars", label: "3 Idiots", category: "aamir" },
  { set: "stars", label: "Talaash", category: "aamir" },
  { set: "stars", label: "PK", category: "aamir" },
  { set: "stars", label: "Dangal", category: "aamir" },
  { set: "stars", label: "Fanaa", category: "aamir" },
  { set: "stars", label: "Hera Pheri", category: "akshay" },
  { set: "stars", label: "Namastey London", category: "akshay" },
  { set: "stars", label: "Singh Is Kinng", category: "akshay" },
  { set: "stars", label: "Special 26", category: "akshay" },
  { set: "stars", label: "Airlift", category: "akshay" },
  { set: "stars", label: "Rustom", category: "akshay" },
  { set: "stars", label: "Toilet: Ek Prem Katha", category: "akshay" },
  { set: "stars", label: "Kesari", category: "akshay" },

  /* ── settings ── */
  { set: "settings", label: "Gully Boy", category: "mumbai" },
  { set: "settings", label: "Wake Up Sid", category: "mumbai" },
  { set: "settings", label: "The Lunchbox", category: "mumbai" },
  { set: "settings", label: "Munna Bhai M.B.B.S.", category: "mumbai" },
  { set: "settings", label: "Life in a... Metro", category: "mumbai" },
  { set: "settings", label: "Kaminey", category: "mumbai" },
  { set: "settings", label: "Once Upon a Time in Mumbaai", category: "mumbai" },
  { set: "settings", label: "Dhobi Ghat", category: "mumbai" },
  { set: "settings", label: "Delhi-6", category: "delhi" },
  { set: "settings", label: "Vicky Donor", category: "delhi" },
  { set: "settings", label: "Band Baaja Baaraat", category: "delhi" },
  { set: "settings", label: "Rang De Basanti", category: "delhi" },
  { set: "settings", label: "Delhi Belly", category: "delhi" },
  { set: "settings", label: "Oye Lucky! Lucky Oye!", category: "delhi" },
  { set: "settings", label: "Badhaai Ho", category: "delhi" },
  { set: "settings", label: "Khosla Ka Ghosla", category: "delhi" },
  { set: "settings", label: "Zindagi Na Milegi Dobara", category: "abroad" },
  { set: "settings", label: "Queen", category: "abroad" },
  { set: "settings", label: "Kal Ho Naa Ho", category: "abroad" },
  { set: "settings", label: "My Name Is Khan", category: "abroad" },
  { set: "settings", label: "English Vinglish", category: "abroad" },
  { set: "settings", label: "Namastey London", category: "abroad" },
  { set: "settings", label: "Salaam Namaste", category: "abroad" },
  { set: "settings", label: "Dil Dhadakne Do", category: "abroad" },
  { set: "settings", label: "Tanu Weds Manu", category: "smalltown" },
  { set: "settings", label: "Bareilly Ki Barfi", category: "smalltown" },
  { set: "settings", label: "Dum Laga Ke Haisha", category: "smalltown" },
  { set: "settings", label: "Gangs of Wasseypur", category: "smalltown" },
  { set: "settings", label: "Masaan", category: "smalltown" },
  { set: "settings", label: "Stree", category: "smalltown" },
  { set: "settings", label: "Newton", category: "smalltown" },
  { set: "settings", label: "Swades", category: "smalltown" },
];
