import type { CategorizeItem } from "@curio/core";

/** Every sorting item, tagged with the set whose buckets it belongs to. */
export const categorize: CategorizeItem[] = [
  /* ── decades ── */
  { set: "decades", label: "Mughal-e-Azam", category: "sixties" },
  { set: "decades", label: "Mother India", category: "sixties" },
  { set: "decades", label: "Pyaasa", category: "sixties" },
  { set: "decades", label: "Awara", category: "sixties" },
  { set: "decades", label: "Guide", category: "sixties" },
  { set: "decades", label: "Do Bigha Zamin", category: "sixties" },
  { set: "decades", label: "Kaagaz Ke Phool", category: "sixties" },
  { set: "decades", label: "Madhumati", category: "sixties" },
  { set: "decades", label: "Sholay", category: "seventies" },
  { set: "decades", label: "Deewaar", category: "seventies" },
  { set: "decades", label: "Zanjeer", category: "seventies" },
  { set: "decades", label: "Anand", category: "seventies" },
  { set: "decades", label: "Pakeezah", category: "seventies" },
  { set: "decades", label: "Don", category: "seventies" },
  { set: "decades", label: "Mr. India", category: "seventies" },
  { set: "decades", label: "Tezaab", category: "seventies" },
  { set: "decades", label: "Qayamat Se Qayamat Tak", category: "seventies" },
  { set: "decades", label: "Dilwale Dulhania Le Jayenge", category: "nineties" },
  { set: "decades", label: "Hum Aapke Hain Koun..!", category: "nineties" },
  { set: "decades", label: "Kuch Kuch Hota Hai", category: "nineties" },
  { set: "decades", label: "Baazigar", category: "nineties" },
  { set: "decades", label: "Darr", category: "nineties" },
  { set: "decades", label: "Satya", category: "nineties" },
  { set: "decades", label: "Dil To Pagal Hai", category: "nineties" },
  { set: "decades", label: "Andaz Apna Apna", category: "nineties" },
  { set: "decades", label: "Rangeela", category: "nineties" },
  { set: "decades", label: "Lagaan", category: "modern" },
  { set: "decades", label: "Dil Chahta Hai", category: "modern" },
  { set: "decades", label: "3 Idiots", category: "modern" },
  { set: "decades", label: "Gangs of Wasseypur", category: "modern" },
  { set: "decades", label: "Queen", category: "modern" },
  { set: "decades", label: "Gully Boy", category: "modern" },
  { set: "decades", label: "Andhadhun", category: "modern" },
  { set: "decades", label: "Zindagi Na Milegi Dobara", category: "modern" },
  { set: "decades", label: "Bajirao Mastani", category: "modern" },
  { set: "decades", label: "Barfi!", category: "modern" },

  /* ── craft ── */
  { set: "craft", label: "Amitabh Bachchan", category: "acting" },
  { set: "craft", label: "Dilip Kumar", category: "acting" },
  { set: "craft", label: "Madhubala", category: "acting" },
  { set: "craft", label: "Nargis", category: "acting" },
  { set: "craft", label: "Sridevi", category: "acting" },
  { set: "craft", label: "Madhuri Dixit", category: "acting" },
  { set: "craft", label: "Nawazuddin Siddiqui", category: "acting" },
  { set: "craft", label: "Irrfan Khan", category: "acting" },
  { set: "craft", label: "Kangana Ranaut", category: "acting" },
  { set: "craft", label: "Naseeruddin Shah", category: "acting" },
  { set: "craft", label: "Yash Chopra", category: "directing" },
  { set: "craft", label: "Mani Ratnam", category: "directing" },
  { set: "craft", label: "Anurag Kashyap", category: "directing" },
  { set: "craft", label: "Sanjay Leela Bhansali", category: "directing" },
  { set: "craft", label: "Zoya Akhtar", category: "directing" },
  { set: "craft", label: "Rajkumar Hirani", category: "directing" },
  { set: "craft", label: "Shyam Benegal", category: "directing" },
  { set: "craft", label: "Meghna Gulzar", category: "directing" },
  { set: "craft", label: "Bimal Roy", category: "directing" },
  { set: "craft", label: "Guru Dutt", category: "directing" },
  { set: "craft", label: "Lata Mangeshkar", category: "singing" },
  { set: "craft", label: "Asha Bhosle", category: "singing" },
  { set: "craft", label: "Mohammed Rafi", category: "singing" },
  { set: "craft", label: "Kishore Kumar", category: "singing" },
  { set: "craft", label: "Mukesh", category: "singing" },
  { set: "craft", label: "Manna Dey", category: "singing" },
  { set: "craft", label: "Sonu Nigam", category: "singing" },
  { set: "craft", label: "Arijit Singh", category: "singing" },
  { set: "craft", label: "Shreya Ghoshal", category: "singing" },
  { set: "craft", label: "Geeta Dutt", category: "singing" },
  { set: "craft", label: "A. R. Rahman", category: "composing" },
  { set: "craft", label: "R. D. Burman", category: "composing" },
  { set: "craft", label: "S. D. Burman", category: "composing" },
  { set: "craft", label: "Naushad", category: "composing" },
  { set: "craft", label: "Laxmikant-Pyarelal", category: "composing" },
  { set: "craft", label: "Shankar-Ehsaan-Loy", category: "composing" },
  { set: "craft", label: "Vishal-Shekhar", category: "composing" },
  { set: "craft", label: "Amit Trivedi", category: "composing" },
  { set: "craft", label: "Madan Mohan", category: "composing" },
  { set: "craft", label: "Jatin-Lalit", category: "composing" },

  /* ── settings ── */
  { set: "settings", label: "Satya", category: "mumbai" },
  { set: "settings", label: "Gully Boy", category: "mumbai" },
  { set: "settings", label: "The Lunchbox", category: "mumbai" },
  { set: "settings", label: "Munna Bhai M.B.B.S.", category: "mumbai" },
  { set: "settings", label: "Wake Up Sid", category: "mumbai" },
  { set: "settings", label: "Rangeela", category: "mumbai" },
  { set: "settings", label: "Talaash", category: "mumbai" },
  { set: "settings", label: "Jab We Met", category: "punjab" },
  { set: "settings", label: "Udta Punjab", category: "punjab" },
  { set: "settings", label: "Bhaag Milkha Bhaag", category: "punjab" },
  { set: "settings", label: "Rocket Singh", category: "punjab" },
  { set: "settings", label: "Band Baaja Baaraat", category: "punjab" },
  { set: "settings", label: "Zindagi Na Milegi Dobara", category: "abroad" },
  { set: "settings", label: "Queen", category: "abroad" },
  { set: "settings", label: "Namastey London", category: "abroad" },
  { set: "settings", label: "Kabhi Alvida Naa Kehna", category: "abroad" },
  { set: "settings", label: "Race", category: "abroad" },
  { set: "settings", label: "English Vinglish", category: "abroad" },
  { set: "settings", label: "Masaan", category: "smalltown" },
  { set: "settings", label: "Gangs of Wasseypur", category: "smalltown" },
  { set: "settings", label: "Lagaan", category: "smalltown" },
  { set: "settings", label: "Dum Laga Ke Haisha", category: "smalltown" },
  { set: "settings", label: "Bareilly Ki Barfi", category: "smalltown" },
  { set: "settings", label: "Peepli Live", category: "smalltown" },
  { set: "settings", label: "Newton", category: "smalltown" },

  /* ── families ── */
  { set: "families", label: "Prithviraj Kapoor", category: "kapoor" },
  { set: "families", label: "Raj Kapoor", category: "kapoor" },
  { set: "families", label: "Shashi Kapoor", category: "kapoor" },
  { set: "families", label: "Rishi Kapoor", category: "kapoor" },
  { set: "families", label: "Ranbir Kapoor", category: "kapoor" },
  { set: "families", label: "Kareena Kapoor", category: "kapoor" },
  { set: "families", label: "Karisma Kapoor", category: "kapoor" },
  { set: "families", label: "Harivansh Rai Bachchan", category: "bachchan" },
  { set: "families", label: "Amitabh Bachchan", category: "bachchan" },
  { set: "families", label: "Jaya Bachchan", category: "bachchan" },
  { set: "families", label: "Abhishek Bachchan", category: "bachchan" },
  { set: "families", label: "Aishwarya Rai Bachchan", category: "bachchan" },
  { set: "families", label: "Salim Khan", category: "khan" },
  { set: "families", label: "Salman Khan", category: "khan" },
  { set: "families", label: "Arbaaz Khan", category: "khan" },
  { set: "families", label: "Sohail Khan", category: "khan" },
  { set: "families", label: "Yash Chopra", category: "chopra" },
  { set: "families", label: "Aditya Chopra", category: "chopra" },
  { set: "families", label: "Yash Johar", category: "chopra" },
  { set: "families", label: "Karan Johar", category: "chopra" },
];
