import type { ChoiceItem } from "@curio/core";

/** Straight trivia: four options, one truth. */
export const choice: ChoiceItem[] = [
  { prompt: "Which film features the song 'Mere Sapno Ki Rani'?", options: ["Aradhana", "Amar Prem", "Kati Patang", "Anand"], answer: 0 },
  { prompt: "Who directed Sholay?", options: ["Yash Chopra", "Ramesh Sippy", "Manmohan Desai", "Raj Khosla"], answer: 1 },
  { prompt: "What is the name of the bandit in Sholay?", options: ["Sultan", "Shakaal", "Gabbar Singh", "Mogambo"], answer: 2 },
  { prompt: "Which actor played Vijay in Deewaar?", options: ["Shashi Kapoor", "Amitabh Bachchan", "Vinod Khanna", "Rajesh Khanna"], answer: 1 },
  { prompt: "Who directed Dilwale Dulhania Le Jayenge?", options: ["Yash Chopra", "Karan Johar", "Aditya Chopra", "Sooraj Barjatya"], answer: 2 },
  { prompt: "What does the villain Mogambo say in Mr. India?", options: ["Mogambo khush hua", "Mogambo aa gaya", "Mogambo naaraz hai", "Mogambo zinda hai"], answer: 0 },
  { prompt: "Which film gave us the line 'Kitne aadmi the?'", options: ["Deewaar", "Sholay", "Zanjeer", "Don"], answer: 1 },
  { prompt: "Who played the title role in Mughal-e-Azam's Anarkali?", options: ["Meena Kumari", "Nargis", "Madhubala", "Nutan"], answer: 2 },
  { prompt: "Which film is India's first colour-and-sound blockbuster about a courtesan and a prince?", options: ["Pakeezah", "Mughal-e-Azam", "Umrao Jaan", "Devdas"], answer: 1 },
  { prompt: "Who composed the music for Dilwale Dulhania Le Jayenge?", options: ["Nadeem-Shravan", "Anu Malik", "Jatin-Lalit", "A. R. Rahman"], answer: 2 },
  { prompt: "Which film won A. R. Rahman the Academy Award for Best Original Score in 2009?", options: ["Lagaan", "Slumdog Millionaire", "Taare Zameen Par", "Rang De Basanti"], answer: 1 },
  { prompt: "Which film was India's official Oscar entry and lost to No Man's Land?", options: ["Lagaan", "Devdas", "Swades", "Paheli"], answer: 0 },
  { prompt: "Who directed Lagaan?", options: ["Ashutosh Gowariker", "Rakeysh Omprakash Mehra", "Aamir Khan", "Vidhu Vinod Chopra"], answer: 0 },
  { prompt: "In Lagaan, what is the villagers' wager against the British?", options: ["A horse race", "A wrestling match", "A cricket match", "A hunt"], answer: 2 },
  { prompt: "Which actor is known as the 'Shahenshah' of Bollywood?", options: ["Dilip Kumar", "Amitabh Bachchan", "Dharmendra", "Shah Rukh Khan"], answer: 1 },
  { prompt: "Which actor was nicknamed the 'Tragedy King'?", options: ["Raj Kapoor", "Dev Anand", "Dilip Kumar", "Guru Dutt"], answer: 2 },
  { prompt: "Who directed and starred in Pyaasa?", options: ["Raj Kapoor", "Guru Dutt", "Bimal Roy", "Mehboob Khan"], answer: 1 },
  { prompt: "Which Raj Kapoor film features the song 'Awara Hoon'?", options: ["Shree 420", "Awara", "Barsaat", "Sangam"], answer: 1 },
  { prompt: "Which film's title song is 'Mera Joota Hai Japani'?", options: ["Awara", "Shree 420", "Jagte Raho", "Anari"], answer: 1 },
  { prompt: "Who played the lead in Mother India?", options: ["Nargis", "Meena Kumari", "Waheeda Rehman", "Vyjayanthimala"], answer: 0 },
  { prompt: "Which film is Kamal Haasan's celebrated dual-role comedy?", options: ["Chachi 420", "Sadma", "Hey Ram", "Ek Duuje Ke Liye"], answer: 0 },
  { prompt: "Who directed the 2001 film Dil Chahta Hai?", options: ["Farhan Akhtar", "Zoya Akhtar", "Karan Johar", "Rakeysh Omprakash Mehra"], answer: 0 },
  { prompt: "In which city do the friends in Dil Chahta Hai take their famous road trip?", options: ["Jaipur", "Goa", "Manali", "Pondicherry"], answer: 1 },
  { prompt: "Which film features the character Circuit?", options: ["Dhamaal", "Munna Bhai M.B.B.S.", "Hera Pheri", "Golmaal"], answer: 1 },
  { prompt: "Who plays Munna Bhai?", options: ["Arshad Warsi", "Sanjay Dutt", "Boman Irani", "Sunil Dutt"], answer: 1 },
  { prompt: "What word does Lage Raho Munna Bhai popularise?", options: ["Jugaad", "Gandhigiri", "Bhaigiri", "Timepass"], answer: 1 },
  { prompt: "Who directed 3 Idiots?", options: ["Rajkumar Hirani", "Aamir Khan", "Vidhu Vinod Chopra", "Anurag Basu"], answer: 0 },
  { prompt: "What is the phrase repeated throughout 3 Idiots?", options: ["Jaane bhi do", "All is well", "Chak de", "Sab moh maya hai"], answer: 1 },
  { prompt: "What is Rancho's real name in 3 Idiots?", options: ["Ranchoddas Chanchad", "Phunsukh Wangdu", "Farhan Qureshi", "Raju Rastogi"], answer: 1 },
  { prompt: "Which sport does Chak De! India centre on?", options: ["Cricket", "Kabaddi", "Field hockey", "Boxing"], answer: 2 },
  { prompt: "Which film is about a wrestler training his daughters?", options: ["Sultan", "Dangal", "Mary Kom", "Bhaag Milkha Bhaag"], answer: 1 },
  { prompt: "Bhaag Milkha Bhaag tells the story of which athlete?", options: ["P. T. Usha", "Milkha Singh", "Dhyan Chand", "Abhinav Bindra"], answer: 1 },
  { prompt: "Who directed Gangs of Wasseypur?", options: ["Anurag Kashyap", "Vishal Bhardwaj", "Dibakar Banerjee", "Tigmanshu Dhulia"], answer: 0 },
  { prompt: "Vishal Bhardwaj's Maqbool adapts which Shakespeare play?", options: ["Hamlet", "Othello", "Macbeth", "King Lear"], answer: 2 },
  { prompt: "Vishal Bhardwaj's Omkara adapts which Shakespeare play?", options: ["Othello", "Macbeth", "Hamlet", "The Tempest"], answer: 0 },
  { prompt: "Vishal Bhardwaj's Haider adapts which Shakespeare play?", options: ["Macbeth", "Hamlet", "Julius Caesar", "Romeo and Juliet"], answer: 1 },
  { prompt: "Which film features the song 'Chaiyya Chaiyya', shot atop a moving train?", options: ["Dil Se..", "Bombay", "Roja", "Taal"], answer: 0 },
  { prompt: "Who directed Dil Se..?", options: ["Mani Ratnam", "Ram Gopal Varma", "Sanjay Leela Bhansali", "Subhash Ghai"], answer: 0 },
  { prompt: "Which composer's debut Hindi-dubbed film was Roja?", options: ["Ilaiyaraaja", "A. R. Rahman", "Shankar-Ehsaan-Loy", "Vishal-Shekhar"], answer: 1 },
  { prompt: "Who directed Devdas (2002)?", options: ["Sanjay Leela Bhansali", "Karan Johar", "Ashutosh Gowariker", "Bimal Roy"], answer: 0 },
  { prompt: "Which two actresses share the screen in Devdas (2002) as Paro and Chandramukhi?", options: ["Kajol and Rani Mukerji", "Aishwarya Rai and Madhuri Dixit", "Karisma Kapoor and Tabu", "Preity Zinta and Rani Mukerji"], answer: 1 },
  { prompt: "Which Bhansali film has Aishwarya Rai sent to Italy to find her lover, escorted by her husband?", options: ["Guzaarish", "Hum Dil De Chuke Sanam", "Saawariya", "Black"], answer: 1 },
  { prompt: "Which film made Shah Rukh Khan's 'Rahul' name famous alongside 'Anjali'?", options: ["Kabhi Khushi Kabhie Gham", "Kuch Kuch Hota Hai", "Dil To Pagal Hai", "Kal Ho Naa Ho"], answer: 1 },
  { prompt: "Who directed Kuch Kuch Hota Hai?", options: ["Aditya Chopra", "Karan Johar", "Yash Chopra", "Sooraj Barjatya"], answer: 1 },
  { prompt: "Which film is Sooraj Barjatya's wedding-drama blockbuster of 1994?", options: ["Maine Pyar Kiya", "Hum Aapke Hain Koun..!", "Hum Saath-Saath Hain", "Vivah"], answer: 1 },
  { prompt: "Which actress made her debut opposite Salman Khan in Maine Pyar Kiya?", options: ["Madhuri Dixit", "Bhagyashree", "Juhi Chawla", "Karisma Kapoor"], answer: 1 },
  { prompt: "The song 'Ek Do Teen' belongs to which film?", options: ["Tezaab", "Beta", "Ram Lakhan", "Khalnayak"], answer: 0 },
  { prompt: "Which actress is known for 'Dhak Dhak Karne Laga'?", options: ["Sridevi", "Madhuri Dixit", "Juhi Chawla", "Raveena Tandon"], answer: 1 },
  { prompt: "Which film features Sridevi in a blue saree singing in the rain?", options: ["Chandni", "Mr. India", "Lamhe", "Nagina"], answer: 1 },
  { prompt: "Which actor plays a double role in Don (1978)?", options: ["Amitabh Bachchan", "Vinod Khanna", "Feroz Khan", "Shatrughan Sinha"], answer: 0 },
  { prompt: "Who directed the 2006 remake Don: The Chase Begins Again?", options: ["Farhan Akhtar", "Karan Johar", "Rohit Shetty", "Abbas-Mustan"], answer: 0 },
  { prompt: "Which film features the trio Raju, Shyam and Baburao?", options: ["Golmaal", "Hera Pheri", "Dhamaal", "Welcome"], answer: 1 },
  { prompt: "Which actor plays Baburao Ganpatrao Apte?", options: ["Johnny Lever", "Paresh Rawal", "Boman Irani", "Om Puri"], answer: 1 },
  { prompt: "Which film's plot revolves around a suitcase of money and a wrong phone number?", options: ["Hera Pheri", "Dhamaal", "Phir Hera Pheri", "Golmaal Returns"], answer: 0 },
  { prompt: "Which film features Anil Kapoor as an invisible man protecting orphans?", options: ["Mr. India", "Nayak", "Ram Lakhan", "Tezaab"], answer: 0 },
  { prompt: "Who wrote the screenplays for Sholay, Deewaar and Zanjeer?", options: ["Salim-Javed", "Gulzar", "Kader Khan", "Honey Irani"], answer: 0 },
  { prompt: "Which lyricist and director gave us Aandhi and Maachis?", options: ["Javed Akhtar", "Gulzar", "Sahir Ludhianvi", "Shailendra"], answer: 1 },
  { prompt: "Who is often called the 'Nightingale of India'?", options: ["Asha Bhosle", "Lata Mangeshkar", "Geeta Dutt", "Shamshad Begum"], answer: 1 },
  { prompt: "Which playback singer is most associated with Rajesh Khanna's songs?", options: ["Mohammed Rafi", "Kishore Kumar", "Mukesh", "Manna Dey"], answer: 1 },
  { prompt: "Which composer scored both Sholay and Deewaar?", options: ["Laxmikant-Pyarelal", "Shankar-Jaikishan", "R. D. Burman", "Kalyanji-Anandji"], answer: 2 },
  { prompt: "R. D. Burman was affectionately known by which nickname?", options: ["Dada", "Pancham", "Bappi", "Anna"], answer: 1 },
  { prompt: "Which film features the song 'Tujhe Dekha To Ye Jaana Sanam'?", options: ["Dilwale Dulhania Le Jayenge", "Darr", "Dil To Pagal Hai", "Veer-Zaara"], answer: 0 },
  { prompt: "In DDLJ, what does Raj famously refuse to do without her father's blessing?", options: ["Buy the tickets", "Take Simran away", "Fight Kuljeet", "Sing at the wedding"], answer: 1 },
  { prompt: "Which Mumbai cinema famously ran DDLJ for decades?", options: ["Regal", "Maratha Mandir", "Liberty", "Eros"], answer: 1 },
  { prompt: "Kabir Singh is a Hindi remake of which Telugu film?", options: ["Arjun Reddy", "Jersey", "Pelli Choopulu", "Mahanati"], answer: 0 },
  { prompt: "Which 2015 film features Salman Khan taking a mute girl home to Pakistan?", options: ["Sultan", "Bajrangi Bhaijaan", "Tubelight", "Ek Tha Tiger"], answer: 1 },
  { prompt: "Which film features the character Chulbul Pandey?", options: ["Singham", "Dabangg", "Simmba", "Rowdy Rathore"], answer: 1 },
  { prompt: "Who directed Singham and the Golmaal series?", options: ["Rohit Shetty", "Sajid Khan", "Anees Bazmee", "David Dhawan"], answer: 0 },
  { prompt: "Which film features a queen of a small kingdom and the siege of Chittor?", options: ["Bajirao Mastani", "Padmaavat", "Jodhaa Akbar", "Panipat"], answer: 1 },
  { prompt: "Which Bhansali film pairs Ranveer Singh and Deepika Padukone as a Peshwa and his second wife?", options: ["Padmaavat", "Bajirao Mastani", "Ram-Leela", "Goliyon Ki Raasleela"], answer: 1 },
  { prompt: "Which film opens with a young woman travelling alone across Europe after a cancelled wedding?", options: ["Queen", "Highway", "English Vinglish", "Piku"], answer: 0 },
  { prompt: "Which actress won wide acclaim for Queen?", options: ["Alia Bhatt", "Kangana Ranaut", "Anushka Sharma", "Vidya Balan"], answer: 1 },
  { prompt: "In Piku, what is the running preoccupation of Amitabh Bachchan's character?", options: ["His constipation", "His property", "His late wife", "His scooter"], answer: 0 },
  { prompt: "Which film features Sridevi as a housewife who secretly takes English classes?", options: ["English Vinglish", "Mom", "Chandni", "Judaai"], answer: 0 },
  { prompt: "Which film's soundtrack includes 'Kabira' and 'Balam Pichkari'?", options: ["Rockstar", "Yeh Jawaani Hai Deewani", "Tamasha", "Wake Up Sid"], answer: 1 },
  { prompt: "Who directed Zindagi Na Milegi Dobara?", options: ["Farhan Akhtar", "Zoya Akhtar", "Imtiaz Ali", "Ayan Mukerji"], answer: 1 },
  { prompt: "In which country is Zindagi Na Milegi Dobara mostly set?", options: ["Portugal", "Spain", "Italy", "Greece"], answer: 1 },
  { prompt: "Which festival closes Zindagi Na Milegi Dobara?", options: ["La Tomatina", "Running of the bulls", "Carnival", "Holi"], answer: 1 },
  { prompt: "Who directed Rockstar and Tamasha?", options: ["Imtiaz Ali", "Anurag Basu", "Ayan Mukerji", "Shakun Batra"], answer: 0 },
  { prompt: "Which film features the song 'Kun Faya Kun'?", options: ["Rockstar", "Tamasha", "Highway", "Jab We Met"], answer: 0 },
  { prompt: "In Jab We Met, what is Kareena Kapoor's character called?", options: ["Geet", "Meera", "Simran", "Naina"], answer: 0 },
  { prompt: "Which film cuts between a present-day couple in London and a 1960s romance in Delhi?", options: ["Jab Harry Met Sejal", "Love Aaj Kal", "Befikre", "Queen"], answer: 1 },
  { prompt: "Which 2006 film revolves around students re-enacting freedom fighters?", options: ["Rang De Basanti", "Lakshya", "Swades", "Yuva"], answer: 0 },
  { prompt: "Which film has Shah Rukh Khan returning from NASA to an Indian village?", options: ["Swades", "Chak De! India", "Veer-Zaara", "My Name Is Khan"], answer: 0 },
  { prompt: "Which film features the song 'Yeh Jo Des Hai Tera'?", options: ["Swades", "Rang De Basanti", "Lagaan", "Taare Zameen Par"], answer: 0 },
  { prompt: "Taare Zameen Par is about a child with which condition?", options: ["Autism", "Dyslexia", "ADHD", "Deafness"], answer: 1 },
  { prompt: "Which film features a talking-to-God courtroom premise?", options: ["OMG – Oh My God!", "PK", "Bhool Bhulaiyaa", "Toilet: Ek Prem Katha"], answer: 0 },
  { prompt: "In PK, what is the alien searching for?", options: ["His spaceship remote", "His friend", "A wife", "A passport"], answer: 0 },
  { prompt: "Which film features a photographer and his fake girlfriend in Mumbai?", options: ["Photograph", "The Lunchbox", "Masaan", "Court"], answer: 0 },
  { prompt: "The Lunchbox turns on a mix-up in which delivery system?", options: ["Indian Railways", "The dabbawalas", "India Post", "A courier firm"], answer: 1 },
  { prompt: "Which film features Nawazuddin Siddiqui as Faizal Khan?", options: ["Gangs of Wasseypur", "Raman Raghav 2.0", "Badlapur", "Manjhi"], answer: 0 },
  { prompt: "Which film is set in a Varanasi cremation ground?", options: ["Masaan", "Mukti Bhawan", "Raanjhanaa", "Banaras"], answer: 0 },
  { prompt: "Which actor's screen name is Vijay Deenanath Chauhan?", options: ["Amitabh Bachchan", "Anil Kapoor", "Nana Patekar", "Jackie Shroff"], answer: 0 },
  { prompt: "Which film gave the line 'Mere paas maa hai'?", options: ["Deewaar", "Trishul", "Shakti", "Kaala Patthar"], answer: 0 },
  { prompt: "Which actor is known as 'Bhaijaan'?", options: ["Aamir Khan", "Salman Khan", "Saif Ali Khan", "Shah Rukh Khan"], answer: 1 },
  { prompt: "Which actor is nicknamed 'Mr. Perfectionist'?", options: ["Shah Rukh Khan", "Aamir Khan", "Akshay Kumar", "Ajay Devgn"], answer: 1 },
  { prompt: "Which actress won the Miss World title before entering films?", options: ["Sushmita Sen", "Aishwarya Rai", "Lara Dutta", "Priyanka Chopra"], answer: 1 },
  { prompt: "Which actress played a boxer in Mary Kom?", options: ["Priyanka Chopra", "Deepika Padukone", "Kangana Ranaut", "Anushka Sharma"], answer: 0 },
  { prompt: "Which film features Vidya Balan searching for her husband in Kolkata?", options: ["Kahaani", "Ishqiya", "No One Killed Jessica", "Bobby Jasoos"], answer: 0 },
  { prompt: "Which film has Vidya Balan as a South Indian star of the 1980s?", options: ["The Dirty Picture", "Begum Jaan", "Shakuntala Devi", "Tumhari Sulu"], answer: 0 },
  { prompt: "Which actor delivered the line 'Don ko pakadna mushkil hi nahin, namumkin hai' in the 2006 remake?", options: ["Amitabh Bachchan", "Shah Rukh Khan", "Ranveer Singh", "Hrithik Roshan"], answer: 1 },
  { prompt: "Which film launched Hrithik Roshan?", options: ["Kaho Naa... Pyaar Hai", "Fiza", "Mission Kashmir", "Koi... Mil Gaya"], answer: 0 },
  { prompt: "Which film features the alien Jadoo?", options: ["Koi... Mil Gaya", "Krrish", "PK", "Ra.One"], answer: 0 },
  { prompt: "Which film is India's big-budget superhero sequel to Koi... Mil Gaya?", options: ["Ra.One", "Krrish", "Drona", "Flying Jatt"], answer: 1 },
  { prompt: "Which actor played the antagonist Kancha Cheena in Agneepath (2012)?", options: ["Rishi Kapoor", "Sanjay Dutt", "Ronit Roy", "Om Puri"], answer: 1 },
  { prompt: "Which film features the song 'Kajra Re'?", options: ["Bunty Aur Babli", "Bluffmaster", "Dhoom", "Jhoom Barabar Jhoom"], answer: 0 },
  { prompt: "Which franchise features a motorcycle-riding thief chased by a Mumbai cop?", options: ["Race", "Dhoom", "Don", "Baaghi"], answer: 1 },
  { prompt: "Who played the thief in the first Dhoom?", options: ["Hrithik Roshan", "Aamir Khan", "John Abraham", "Abhishek Bachchan"], answer: 2 },
  { prompt: "In which South African city is Race (2008) set?", options: ["Cape Town", "Durban", "Johannesburg", "Pretoria"], answer: 1 },
  { prompt: "Which film features Andaz Apna Apna's bumbling duo?", options: ["Amar and Prem", "Raju and Shyam", "Jai and Veeru", "Karan and Arjun"], answer: 0 },
  { prompt: "Who plays Crime Master Gogo in Andaz Apna Apna?", options: ["Paresh Rawal", "Shakti Kapoor", "Kader Khan", "Asrani"], answer: 1 },
  { prompt: "In Karthik Calling Karthik, who is on the other end of the nightly phone calls?", options: ["His brother", "Karthik himself", "His therapist", "A stranger"], answer: 1 },
  { prompt: "Which film features a man with short-term memory loss and tattoos?", options: ["Ghajini", "Gajraj", "Aankhen", "Race"], answer: 0 },
  { prompt: "Which film has Aamir Khan as a Mumbai policeman investigating a car crash into the sea?", options: ["Talaash", "Kahaani", "Drishyam", "Andhadhun"], answer: 0 },
  { prompt: "In Andhadhun, what is Ayushmann Khurrana's character pretending to be?", options: ["Deaf", "Blind", "Mute", "Paralysed"], answer: 1 },
  { prompt: "Which instrument does the lead play in Andhadhun?", options: ["Sitar", "Violin", "Piano", "Tabla"], answer: 2 },
  { prompt: "Which film features a family covering up a death with an alibi built from film screenings?", options: ["Drishyam", "Talvar", "Badla", "Kahaani 2"], answer: 0 },
  { prompt: "Which film is Amitabh Bachchan's courtroom drama about consent?", options: ["Pink", "Badla", "Aarakshan", "Section 375"], answer: 0 },
  { prompt: "Which phrase is central to Pink?", options: ["No means no", "Justice delayed", "Truth alone", "Silence is consent"], answer: 0 },
  { prompt: "Which film stars Rani Mukerji as a teacher with Tourette syndrome?", options: ["Hichki", "Mardaani", "Black", "Talaash"], answer: 0 },
  { prompt: "In Black, what disabilities does Rani Mukerji's character have?", options: ["Deaf and blind", "Blind only", "Deaf only", "Mute only"], answer: 0 },
  { prompt: "Which film features a village toilet as its central conflict?", options: ["Toilet: Ek Prem Katha", "Padman", "Swades", "Peepli Live"], answer: 0 },
  { prompt: "Padman is based on the real-life inventor of what?", options: ["A cheap sanitary pad machine", "A solar cooker", "A water pump", "A bicycle ambulance"], answer: 0 },
  { prompt: "Which satire follows a farmer whose suicide becomes a media circus?", options: ["Peepli Live", "Newton", "Jolly LLB", "Aankhon Dekhi"], answer: 0 },
  { prompt: "Newton is set during what event?", options: ["A wedding", "An election", "A census", "A cricket match"], answer: 1 },
  { prompt: "Which film has Ayushmann Khurrana mortified by news from his own parents?", options: ["Badhaai Ho", "Shubh Mangal Saavdhan", "Bareilly Ki Barfi", "Dum Laga Ke Haisha"], answer: 0 },
  { prompt: "In Badhaai Ho, what is the source of the family's embarrassment?", options: ["A middle-aged pregnancy", "A runaway bride", "A lottery win", "A divorce"], answer: 0 },
  { prompt: "Which film pairs a plus-size bride with an unwilling groom in 1990s Haridwar?", options: ["Dum Laga Ke Haisha", "Bareilly Ki Barfi", "Shuddh Desi Romance", "Tanu Weds Manu"], answer: 0 },
  { prompt: "Which actor plays both Tanu and Kusum in Tanu Weds Manu Returns?", options: ["Kangana Ranaut", "Swara Bhasker", "Vidya Balan", "Radhika Apte"], answer: 0 },
  { prompt: "Which film is Anurag Kashyap's two-part crime saga set in Jharkhand?", options: ["Gangs of Wasseypur", "Ugly", "Black Friday", "Raman Raghav 2.0"], answer: 0 },
  { prompt: "Black Friday dramatises which event?", options: ["The 1993 Bombay bombings", "The 26/11 attacks", "The Emergency", "The 1984 riots"], answer: 0 },
  { prompt: "Which film features Irrfan Khan as a Delhi businessman faking poverty for a school seat?", options: ["Hindi Medium", "Angrezi Medium", "Piku", "Qarib Qarib Singlle"], answer: 0 },
  { prompt: "Which film's soundtrack is built around the song 'Emotional Atyachar'?", options: ["Dev.D", "Oye Lucky! Lucky Oye!", "Delhi Belly", "Shanghai"], answer: 0 },
  { prompt: "Dev.D is a modern retelling of which classic?", options: ["Devdas", "Pyaasa", "Awara", "Guide"], answer: 0 },
  { prompt: "Which 1965 film has Dev Anand as a guide turned reluctant holy man?", options: ["Guide", "Jewel Thief", "Hare Rama Hare Krishna", "Kala Bazar"], answer: 0 },
  { prompt: "Which film features the song 'Aaj Phir Jeene Ki Tamanna Hai'?", options: ["Guide", "Teesri Manzil", "Kashmir Ki Kali", "Aradhana"], answer: 0 },
  { prompt: "Which classic follows a poet who is celebrated only after being presumed dead?", options: ["Pyaasa", "Kaagaz Ke Phool", "Sahib Bibi Aur Ghulam", "Chaudhvin Ka Chand"], answer: 0 },
  { prompt: "Which Guru Dutt film about a failing director flopped and was later reclaimed as a classic?", options: ["Kaagaz Ke Phool", "Pyaasa", "Baazi", "Mr. & Mrs. 55"], answer: 0 },
  { prompt: "Which film features Meena Kumari as a courtesan and was released after her death?", options: ["Pakeezah", "Sahib Bibi Aur Ghulam", "Kohinoor", "Dil Apna Aur Preet Parai"], answer: 0 },
  { prompt: "Which studio-era director made Do Bigha Zamin and Madhumati?", options: ["Bimal Roy", "Mehboob Khan", "V. Shantaram", "Hrishikesh Mukherjee"], answer: 0 },
  { prompt: "Which director is associated with gentle middle-class comedies like Golmaal (1979) and Chupke Chupke?", options: ["Hrishikesh Mukherjee", "Basu Chatterjee", "Gulzar", "Sai Paranjpye"], answer: 0 },
  { prompt: "Which film features Rajesh Khanna as a terminally ill man who refuses to be sad?", options: ["Anand", "Safar", "Bawarchi", "Amar Prem"], answer: 0 },
  { prompt: "Complete the line from Anand: 'Zindagi badi honi chahiye…'", options: ["…lambi nahin", "…sasti nahin", "…khaali nahin", "…kadwi nahin"], answer: 0 },
  { prompt: "Which film features the song 'Ae Watan' from a spy drama set in Pakistan?", options: ["Raazi", "Ek Tha Tiger", "Baby", "Phantom"], answer: 0 },
  { prompt: "Who directed Raazi?", options: ["Meghna Gulzar", "Zoya Akhtar", "Reema Kagti", "Gauri Shinde"], answer: 0 },
  { prompt: "Which film is a courtroom drama about the Aarushi Talwar case?", options: ["Talvar", "Talaash", "Rustom", "Section 375"], answer: 0 },
  { prompt: "Which film follows four women in Bhopal speaking frankly about desire?", options: ["Lipstick Under My Burkha", "Parched", "Angry Indian Goddesses", "Pink"], answer: 0 },
  { prompt: "In which hill town does Barfi! largely take place?", options: ["Shimla", "Darjeeling", "Ooty", "Mussoorie"], answer: 1 },
  { prompt: "In Barfi!, what disabilities do the two leads have?", options: ["Deaf-mute and autistic", "Blind and deaf", "Autistic and blind", "Mute and paralysed"], answer: 0 },
  { prompt: "Which film is set against a 1950s Bengal zamindari and an art forgery?", options: ["Lootera", "Barfi!", "Detective Byomkesh Bakshy!", "Bulbbul"], answer: 0 },
  { prompt: "Lootera draws on which O. Henry short story?", options: ["The Last Leaf", "The Gift of the Magi", "The Cop and the Anthem", "After Twenty Years"], answer: 0 },
  { prompt: "Which film features the qawwali 'Bhar Do Jholi Meri'?", options: ["Rockstar", "Kabir Singh", "Sarfarosh", "Bajrangi Bhaijaan"], answer: 3 },
  { prompt: "Which actor played the poet Faiz-inspired singer in Bajrangi Bhaijaan's 'Bhar Do Jholi'?", options: ["Adnan Sami", "Rahat Fateh Ali Khan", "Sonu Nigam", "Kailash Kher"], answer: 1 },
  { prompt: "Which film is Shah Rukh Khan's obsessive-stalker breakout of 1993?", options: ["Darr", "Baazigar", "Anjaam", "Duplicate"], answer: 0 },
  { prompt: "Which 1993 film has Shah Rukh Khan as a vengeful anti-hero opposite Kajol?", options: ["Baazigar", "Darr", "Karan Arjun", "Koyla"], answer: 0 },
  { prompt: "Which film ends with the song 'Jai Ho'?", options: ["Slumdog Millionaire", "Dil Se..", "Rang De Basanti", "Guru"], answer: 0 },
  { prompt: "Who directed Guru (2007)?", options: ["Mani Ratnam", "Ashutosh Gowariker", "Rakeysh Omprakash Mehra", "Shimit Amin"], answer: 0 },
  { prompt: "Which film is loosely based on the rise of a textile magnate?", options: ["Guru", "Corporate", "Rocket Singh", "Band Baaja Baaraat"], answer: 0 },
  { prompt: "Which film follows two Delhi youngsters starting a wedding-planning business?", options: ["Band Baaja Baaraat", "Rocket Singh", "Ishaqzaade", "Shuddh Desi Romance"], answer: 0 },
  { prompt: "Which film's title refers to a Mumbai chawl and a rap scene?", options: ["Gully Boy", "Slumdog Millionaire", "Dharavi", "Traffic"], answer: 0 },
  { prompt: "Gully Boy is inspired by which real rappers?", options: ["Divine and Naezy", "Badshah and Raftaar", "Honey Singh and Bohemia", "Emiway and Krsna"], answer: 0 },
  { prompt: "Which actress starred opposite Ranveer Singh in Gully Boy?", options: ["Alia Bhatt", "Deepika Padukone", "Kiara Advani", "Bhumi Pednekar"], answer: 0 },
];
