import type { ChoiceItem } from "@curio/core";

/** Straight trivia: four options, one truth. Everything here is 2000–2019. */
export const choice: ChoiceItem[] = [
  /* ── the films everyone saw ── */
  { prompt: "Which film ends with a village playing the British at cricket?", options: ["Swades", "Lagaan", "Iqbal", "Chak De! India"], answer: 1 },
  { prompt: "In Lagaan, what is the tax the villagers are gambling to escape?", options: ["Lagaan, the land tax", "The salt tax", "A tithe on grain", "A toll on the road"], answer: 0 },
  { prompt: "Who directed Lagaan?", options: ["Ashutosh Gowariker", "Rakeysh Omprakash Mehra", "Farhan Akhtar", "Rajkumar Hirani"], answer: 0 },
  { prompt: "Which 2001 film follows three friends from Mumbai to Goa and then apart?", options: ["Rock On!!", "Dil Chahta Hai", "Zindagi Na Milegi Dobara", "Kai Po Che!"], answer: 1 },
  { prompt: "Dil Chahta Hai was whose directorial debut?", options: ["Zoya Akhtar", "Farhan Akhtar", "Anurag Basu", "Imtiaz Ali"], answer: 1 },
  { prompt: "Which three actors play the friends in Dil Chahta Hai?", options: ["Aamir Khan, Saif Ali Khan and Akshaye Khanna", "Aamir Khan, Salman Khan and Saif Ali Khan", "Saif Ali Khan, Abhishek Bachchan and Akshaye Khanna", "Aamir Khan, Ajay Devgn and Saif Ali Khan"], answer: 0 },
  { prompt: "Who directed the 2002 Devdas with Shah Rukh Khan?", options: ["Karan Johar", "Sanjay Leela Bhansali", "Ashutosh Gowariker", "Yash Chopra"], answer: 1 },
  { prompt: "Who plays Chandramukhi in the 2002 Devdas?", options: ["Aishwarya Rai", "Madhuri Dixit", "Rani Mukerji", "Kareena Kapoor"], answer: 1 },
  { prompt: "Who plays Paro in the 2002 Devdas?", options: ["Madhuri Dixit", "Aishwarya Rai", "Preity Zinta", "Tabu"], answer: 1 },
  { prompt: "In Koi... Mil Gaya, what is the alien called?", options: ["Jadoo", "Bittu", "Chotu", "Krrish"], answer: 0 },
  { prompt: "Krrish is the sequel to which film?", options: ["Koi... Mil Gaya", "Kaho Naa... Pyaar Hai", "Mission Kashmir", "Lakshya"], answer: 0 },
  { prompt: "Who directed both Koi... Mil Gaya and Krrish?", options: ["Rakesh Roshan", "Sanjay Gadhvi", "Anil Sharma", "Vidhu Vinod Chopra"], answer: 0 },
  { prompt: "What is Munna Bhai's sidekick called?", options: ["Circuit", "Tapori", "Rancho", "Chulbul"], answer: 0 },
  { prompt: "Who plays Circuit in the Munna Bhai films?", options: ["Boman Irani", "Arshad Warsi", "Vijay Raaz", "Rajpal Yadav"], answer: 1 },
  { prompt: "Which actor's real-life father played his father in Munna Bhai M.B.B.S.?", options: ["Sanjay Dutt", "Abhishek Bachchan", "Hrithik Roshan", "Saif Ali Khan"], answer: 0, note: "Sunil Dutt played Hari Prasad Sharma." },
  { prompt: "What word did Lage Raho Munna Bhai add to the language?", options: ["Gandhigiri", "Jugaad", "Timepass", "Bindaas"], answer: 0 },
  { prompt: "In Kal Ho Naa Ho, which city are Naina and Aman living in?", options: ["London", "New York", "Toronto", "Sydney"], answer: 1 },
  { prompt: "Who directed Kal Ho Naa Ho?", options: ["Karan Johar", "Nikkhil Advani", "Aditya Chopra", "Kunal Kohli"], answer: 1, note: "Karan Johar wrote and produced it." },
  { prompt: "Which film's hero is a NASA engineer who goes home to a village?", options: ["Swades", "Rang De Basanti", "Guru", "Peepli Live"], answer: 0 },
  { prompt: "What is the village in Swades called?", options: ["Charanpur", "Champaner", "Chanderi", "Wasseypur"], answer: 0 },
  { prompt: "In Veer-Zaara, what keeps Veer in a Pakistani prison for twenty-two years?", options: ["He confesses to a crime he did not commit", "He refuses to give his real name to protect Zaara's honour", "He is mistaken for a spy and never tried", "He escapes and is recaptured"], answer: 1 },
  { prompt: "Which film gave Farah Khan her first credit as director?", options: ["Om Shanti Om", "Main Hoon Na", "Tees Maar Khan", "Happy New Year"], answer: 1 },
  { prompt: "Who plays the two cops chasing bikers in Dhoom?", options: ["Abhishek Bachchan and Uday Chopra", "Abhishek Bachchan and John Abraham", "Ajay Devgn and Uday Chopra", "Akshay Kumar and Abhishek Bachchan"], answer: 0 },
  { prompt: "What is Abhishek Bachchan's character called in the Dhoom films?", options: ["Jai Dixit", "Ali Akbar", "Kabir", "Aryan"], answer: 0 },
  { prompt: "Who plays the thief in Dhoom 2?", options: ["John Abraham", "Hrithik Roshan", "Aamir Khan", "Abhishek Bachchan"], answer: 1 },
  { prompt: "Who plays the thief in Dhoom 3?", options: ["Hrithik Roshan", "Aamir Khan", "Ranbir Kapoor", "John Abraham"], answer: 1 },

  /* ── mid-2000s ── */
  { prompt: "In Black, what does Michelle McNally live with?", options: ["She is deaf and blind", "She is paralysed", "She has amnesia", "She is mute only"], answer: 0 },
  { prompt: "Who plays Michelle's teacher in Black?", options: ["Naseeruddin Shah", "Amitabh Bachchan", "Anupam Kher", "Om Puri"], answer: 1 },
  { prompt: "Who directed Black?", options: ["Sanjay Leela Bhansali", "Vidhu Vinod Chopra", "Mani Ratnam", "Rakeysh Omprakash Mehra"], answer: 0 },
  { prompt: "Rang De Basanti's students end up re-enacting the lives of which group?", options: ["Bhagat Singh and the revolutionaries of the 1920s", "The 1857 mutineers", "The Quit India leaders", "The men of the Indian National Army"], answer: 0 },
  { prompt: "Who composed the music for Rang De Basanti?", options: ["Shankar–Ehsaan–Loy", "A. R. Rahman", "Pritam", "Vishal–Shekhar"], answer: 1 },
  { prompt: "Which Shakespeare play is Vishal Bhardwaj's Omkara built on?", options: ["Macbeth", "Othello", "Hamlet", "King Lear"], answer: 1 },
  { prompt: "Which Shakespeare play is Maqbool built on?", options: ["Macbeth", "Othello", "Hamlet", "The Tempest"], answer: 0 },
  { prompt: "Which Shakespeare play is Haider built on?", options: ["Othello", "Hamlet", "Macbeth", "Julius Caesar"], answer: 1 },
  { prompt: "Where is Haider set?", options: ["Kashmir", "Punjab", "Bihar", "Assam"], answer: 0 },
  { prompt: "In Omkara, who plays Langda Tyagi?", options: ["Ajay Devgn", "Saif Ali Khan", "Vivek Oberoi", "Naseeruddin Shah"], answer: 1 },
  { prompt: "Which object stands in for Othello's handkerchief in Omkara?", options: ["A waistband", "A ring", "A shawl", "A letter"], answer: 0 },
  { prompt: "In the 2006 Don, who takes the title role?", options: ["Amitabh Bachchan", "Shah Rukh Khan", "Abhishek Bachchan", "Ajay Devgn"], answer: 1 },
  { prompt: "Who directed the 2006 remake of Don?", options: ["Farhan Akhtar", "Karan Johar", "Sanjay Gadhvi", "Rohit Shetty"], answer: 0 },
  { prompt: "What is Shah Rukh Khan's character called in Chak De! India?", options: ["Kabir Khan", "Aman Mathur", "Surinder Sahni", "Rahul Raichand"], answer: 0 },
  { prompt: "Which sport does Chak De! India follow?", options: ["Women's hockey", "Women's cricket", "Kabaddi", "Football"], answer: 0 },
  { prompt: "How long does Kabir Khan give his team in the film's famous half-time speech?", options: ["Sattar minute — seventy minutes", "Ninety minutes", "Sixty minutes", "Forty-five minutes"], answer: 0 },
  { prompt: "Which film marked Deepika Padukone's Hindi debut?", options: ["Love Aaj Kal", "Om Shanti Om", "Bachna Ae Haseeno", "Cocktail"], answer: 1 },
  { prompt: "Om Shanti Om's 'Deewangi Deewangi' is famous for what?", options: ["Being shot in a single take", "Packing in thirty-one stars", "Having no music", "Being filmed underwater"], answer: 1 },
  { prompt: "Which film did Aamir Khan direct?", options: ["Rang De Basanti", "Taare Zameen Par", "Peepli Live", "Delhi Belly"], answer: 1, note: "He produced the other two." },
  { prompt: "What is the boy in Taare Zameen Par living with?", options: ["Dyslexia", "Autism", "Deafness", "Polio"], answer: 0 },
  { prompt: "What is the child's name in Taare Zameen Par?", options: ["Ishaan", "Aryan", "Rohan", "Bittu"], answer: 0 },
  { prompt: "Where does Geet come from in Jab We Met?", options: ["Bhatinda", "Bareilly", "Kanpur", "Jhansi"], answer: 0 },
  { prompt: "Who directed Jab We Met?", options: ["Imtiaz Ali", "Anurag Basu", "Ayan Mukerji", "Kunal Kohli"], answer: 0 },
  { prompt: "Guru is widely read as a film about which businessman?", options: ["Dhirubhai Ambani", "J. R. D. Tata", "G. D. Birla", "Vijay Mallya"], answer: 0 },
  { prompt: "What is the band called in Rock On!!?", options: ["Magik", "Sadda Haq", "Junoon", "Indian Ocean"], answer: 0 },
  { prompt: "What condition does the hero of Ghajini have?", options: ["Anterograde amnesia", "Blindness", "Schizophrenia", "Insomnia"], answer: 0 },
  { prompt: "How does Ghajini's hero keep track of what he has learnt?", options: ["Tattoos and Polaroids", "A voice recorder", "A diary chained to his wrist", "Notes on his phone"], answer: 0 },
  { prompt: "In Rab Ne Bana Di Jodi, what is Surinder's alter ego called?", options: ["Raj", "Rahul", "Don", "Bunny"], answer: 0 },

  /* ── the Hirani run and 2009 ── */
  { prompt: "Which novel is 3 Idiots loosely based on?", options: ["Five Point Someone", "The 3 Mistakes of My Life", "2 States", "Revolution 2020"], answer: 0 },
  { prompt: "What is Rancho's real name at the end of 3 Idiots?", options: ["Phunsukh Wangdu", "Ranchoddas Chanchad", "Farhan Qureshi", "Raju Rastogi"], answer: 0 },
  { prompt: "What do the students call the principal in 3 Idiots?", options: ["Virus", "Circuit", "Doctor", "Bhaiya"], answer: 0 },
  { prompt: "Who plays the principal in 3 Idiots?", options: ["Boman Irani", "Anupam Kher", "Paresh Rawal", "Om Puri"], answer: 0 },
  { prompt: "Which phrase does 3 Idiots repeat as a charm against panic?", options: ["All is well", "Jaadu ki jhappi", "Apna time aayega", "Picture abhi baaki hai"], answer: 0 },
  { prompt: "Rajkumar Hirani directed all of these except which?", options: ["Munna Bhai M.B.B.S.", "3 Idiots", "PK", "Barfi!"], answer: 3 },
  { prompt: "Dev.D is a modern retelling of which story?", options: ["Devdas", "Umrao Jaan", "Pyaasa", "Guide"], answer: 0 },
  { prompt: "Who directed Dev.D?", options: ["Anurag Kashyap", "Dibakar Banerjee", "Vishal Bhardwaj", "Sriram Raghavan"], answer: 0 },
  { prompt: "In Kaminey, what is different about the twin brothers?", options: ["One lisps and one stammers", "One is blind", "One is deaf", "They speak different languages"], answer: 0 },
  { prompt: "Who plays both brothers in Kaminey?", options: ["Shahid Kapoor", "Ranbir Kapoor", "Imran Khan", "Abhay Deol"], answer: 0 },
  { prompt: "In Paa, Amitabh Bachchan plays the son of which actor?", options: ["Abhishek Bachchan", "Ajay Devgn", "Boman Irani", "Paresh Rawal"], answer: 0 },
  { prompt: "What condition does Auro have in Paa?", options: ["Progeria", "Dyslexia", "Autism", "Muscular dystrophy"], answer: 0 },
  { prompt: "Which film opens with a young man moving out of his mother's Mumbai flat to work at a magazine?", options: ["Wake Up Sid", "Rocket Singh", "Luck by Chance", "Bachna Ae Haseeno"], answer: 0 },

  /* ── 2010–2014 ── */
  { prompt: "What is Salman Khan's character called in Dabangg?", options: ["Chulbul Pandey", "Bajirao Singham", "Sangram Bhalerao", "Sultan Ali Khan"], answer: 0 },
  { prompt: "Which line does My Name Is Khan build itself around?", options: ["My name is Khan and I am not a terrorist", "All is well", "How's the josh?", "Apna time aayega"], answer: 0 },
  { prompt: "Where do the three friends of Zindagi Na Milegi Dobara take their road trip?", options: ["Spain", "Italy", "Portugal", "Greece"], answer: 0 },
  { prompt: "Which festival do the friends end up at in Zindagi Na Milegi Dobara?", options: ["La Tomatina", "Oktoberfest", "Carnival in Rio", "Holi in Mathura"], answer: 0 },
  { prompt: "Who directed Zindagi Na Milegi Dobara?", options: ["Farhan Akhtar", "Zoya Akhtar", "Reema Kagti", "Ayan Mukerji"], answer: 1 },
  { prompt: "What does each friend have to do in Zindagi Na Milegi Dobara?", options: ["Choose an adventure the others cannot refuse", "Write a poem", "Win a bet", "Find a job"], answer: 0 },
  { prompt: "In Rockstar, what name does Janardhan take as a musician?", options: ["Jordan", "Murad", "Jai", "Rocky"], answer: 0 },
  { prompt: "Who composed the music for Rockstar?", options: ["A. R. Rahman", "Pritam", "Amit Trivedi", "Mithoon"], answer: 0 },
  { prompt: "Which actor won a National Award for The Dirty Picture?", options: ["Vidya Balan", "Kangana Ranaut", "Priyanka Chopra", "Rani Mukerji"], answer: 0 },
  { prompt: "Gangs of Wasseypur is set in and around which coal town?", options: ["Dhanbad", "Bokaro", "Ranchi", "Raniganj"], answer: 0 },
  { prompt: "How many parts was Gangs of Wasseypur released in?", options: ["Two", "One", "Three", "Four"], answer: 0 },
  { prompt: "Who plays Faizal Khan in Gangs of Wasseypur?", options: ["Manoj Bajpayee", "Nawazuddin Siddiqui", "Pankaj Tripathi", "Huma Qureshi"], answer: 1 },
  { prompt: "Where is Kahaani set?", options: ["Kolkata", "Delhi", "Lucknow", "Chennai"], answer: 0 },
  { prompt: "Which festival is going on through Kahaani?", options: ["Durga Puja", "Diwali", "Ganesh Chaturthi", "Holi"], answer: 0 },
  { prompt: "What is Barfi's hero unable to do?", options: ["Hear or speak", "See", "Walk", "Remember"], answer: 0 },
  { prompt: "Which hill town is Barfi! largely set in?", options: ["Darjeeling", "Shimla", "Ooty", "Manali"], answer: 0 },
  { prompt: "What subject made Vicky Donor unusual for a mainstream comedy?", options: ["Sperm donation", "Surrogacy", "Divorce", "Adoption"], answer: 0 },
  { prompt: "Which film was Ayushmann Khurrana's debut?", options: ["Vicky Donor", "Dum Laga Ke Haisha", "Bareilly Ki Barfi", "Badhaai Ho"], answer: 0 },
  { prompt: "Paan Singh Tomar was a national champion in which event before he became a dacoit?", options: ["The steeplechase", "The marathon", "Wrestling", "Boxing"], answer: 0 },
  { prompt: "Which actor played Paan Singh Tomar?", options: ["Irrfan Khan", "Nawazuddin Siddiqui", "Manoj Bajpayee", "Randeep Hooda"], answer: 0 },
  { prompt: "In English Vinglish, what does Shashi quietly set out to learn?", options: ["English", "To drive", "To swim", "To cook professionally"], answer: 0 },
  { prompt: "Which actor returned to Hindi film after fifteen years with English Vinglish?", options: ["Sridevi", "Madhuri Dixit", "Juhi Chawla", "Karisma Kapoor"], answer: 0 },
  { prompt: "Student of the Year launched which three actors?", options: ["Alia Bhatt, Varun Dhawan and Sidharth Malhotra", "Alia Bhatt, Ranveer Singh and Arjun Kapoor", "Parineeti Chopra, Varun Dhawan and Aditya Roy Kapur", "Alia Bhatt, Tiger Shroff and Sidharth Malhotra"], answer: 0 },
  { prompt: "What are the two leads called in Yeh Jawaani Hai Deewani?", options: ["Bunny and Naina", "Jai and Aditi", "Sid and Aisha", "Ved and Tara"], answer: 0 },
  { prompt: "Bhaag Milkha Bhaag tells the story of which athlete?", options: ["Milkha Singh", "P. T. Usha", "Mary Kom", "Abhinav Bindra"], answer: 0 },
  { prompt: "What was Milkha Singh's nickname?", options: ["The Flying Sikh", "The Punjab Express", "The Sardar of Sprint", "The Rocket"], answer: 0 },
  { prompt: "What sets The Lunchbox in motion?", options: ["A dabbawala delivers a tiffin to the wrong desk", "A letter is posted to the wrong flat", "Two phones are swapped", "A train ticket is lost"], answer: 0 },
  { prompt: "Which two actors carry The Lunchbox's correspondence?", options: ["Irrfan Khan and Nimrat Kaur", "Nawazuddin Siddiqui and Nimrat Kaur", "Irrfan Khan and Konkona Sen Sharma", "Manoj Bajpayee and Radhika Apte"], answer: 0 },
  { prompt: "Kai Po Che! is adapted from which Chetan Bhagat novel?", options: ["The 3 Mistakes of My Life", "Five Point Someone", "2 States", "One Night @ the Call Center"], answer: 0 },
  { prompt: "In Queen, where does Rani go after her wedding is called off?", options: ["Paris and Amsterdam", "London and Berlin", "Rome and Barcelona", "New York and Toronto"], answer: 0 },
  { prompt: "Who plays Rani in Queen?", options: ["Kangana Ranaut", "Alia Bhatt", "Parineeti Chopra", "Anushka Sharma"], answer: 0 },
  { prompt: "In PK, what is the stranger looking for?", options: ["His remote, to get home", "His brother", "A passport", "A lost fortune"], answer: 0 },
  { prompt: "Which film has Alia Bhatt kidnapped and then unwilling to go home?", options: ["Highway", "Udta Punjab", "Raazi", "Dear Zindagi"], answer: 0 },

  /* ── 2015–2019 ── */
  { prompt: "In Bajrangi Bhaijaan, what is the little girl trying to do?", options: ["Get home to Pakistan", "Find her missing brother", "Reach a hospital", "Go to school"], answer: 0 },
  { prompt: "What is unusual about the child in Bajrangi Bhaijaan?", options: ["She cannot speak", "She cannot see", "She is deaf", "She has no memory"], answer: 0 },
  { prompt: "Piku is built around a road trip between which two cities?", options: ["Delhi and Kolkata", "Mumbai and Goa", "Delhi and Jaipur", "Chennai and Bengaluru"], answer: 0 },
  { prompt: "Which three actors share Piku?", options: ["Amitabh Bachchan, Deepika Padukone and Irrfan Khan", "Amitabh Bachchan, Vidya Balan and Irrfan Khan", "Naseeruddin Shah, Deepika Padukone and Irrfan Khan", "Amitabh Bachchan, Deepika Padukone and Nawazuddin Siddiqui"], answer: 0 },
  { prompt: "Bajirao Mastani is about a Peshwa of which empire?", options: ["The Maratha empire", "The Mughal empire", "Vijayanagara", "The Rajput confederacy"], answer: 0 },
  { prompt: "Who plays Kashibai in Bajirao Mastani?", options: ["Priyanka Chopra", "Deepika Padukone", "Anushka Sharma", "Kriti Sanon"], answer: 0 },
  { prompt: "Where is Masaan set?", options: ["Varanasi", "Allahabad", "Patna", "Lucknow"], answer: 0 },
  { prompt: "Dangal follows a father training his daughters in which sport?", options: ["Wrestling", "Boxing", "Athletics", "Weightlifting"], answer: 0 },
  { prompt: "Whose family does Dangal tell the story of?", options: ["Mahavir Singh Phogat's", "Sushil Kumar's", "Yogeshwar Dutt's", "Vijender Singh's"], answer: 0 },
  { prompt: "Which market made Dangal the biggest-earning Indian film of its time?", options: ["China", "The United States", "The Gulf", "The United Kingdom"], answer: 0 },
  { prompt: "Which three-word phrase does Pink turn into an argument?", options: ["No means no", "All is well", "Enough is enough", "Speak your truth"], answer: 0 },
  { prompt: "Neerja is about a flight attendant on which hijacked flight?", options: ["Pan Am Flight 73", "Indian Airlines 814", "Air India 182", "Lufthansa 181"], answer: 0 },
  { prompt: "Who plays Neerja Bhanot?", options: ["Sonam Kapoor", "Priyanka Chopra", "Alia Bhatt", "Taapsee Pannu"], answer: 0 },
  { prompt: "Airlift dramatises the evacuation of Indians from where?", options: ["Kuwait in 1990", "Yemen in 2015", "Libya in 2011", "Iraq in 2003"], answer: 0 },
  { prompt: "Sultan is about a wrestler from which state?", options: ["Haryana", "Punjab", "Uttar Pradesh", "Maharashtra"], answer: 0 },
  { prompt: "Newton follows one man's attempt to do what?", options: ["Run a fair polling booth in a forest", "Build a school", "Win a court case", "Reopen a mine"], answer: 0 },
  { prompt: "Which actor plays the title role in Newton?", options: ["Rajkummar Rao", "Nawazuddin Siddiqui", "Vicky Kaushal", "Ayushmann Khurrana"], answer: 0 },
  { prompt: "Hindi Medium is a comedy about which anxiety?", options: ["Getting a child into an English-medium school", "Buying a flat", "Arranging a wedding", "Passing a driving test"], answer: 0 },
  { prompt: "In Secret Superstar, how does the girl hide her identity online?", options: ["She sings in a burqa", "She uses a cartoon avatar", "She sings offscreen", "She uses a voice filter"], answer: 0 },
  { prompt: "In Andhadhun, what is Akash pretending to be?", options: ["Blind", "Deaf", "Mute", "A policeman"], answer: 0 },
  { prompt: "Who directed Andhadhun?", options: ["Sriram Raghavan", "Sujoy Ghosh", "Anurag Kashyap", "Neeraj Pandey"], answer: 0 },
  { prompt: "Which actor plays Simi, the widow, in Andhadhun?", options: ["Tabu", "Radhika Apte", "Konkona Sen Sharma", "Huma Qureshi"], answer: 0 },
  { prompt: "Padmaavat is adapted from a poem by whom?", options: ["Malik Muhammad Jayasi", "Amir Khusro", "Tulsidas", "Kalidasa"], answer: 0 },
  { prompt: "Who plays Alauddin Khilji in Padmaavat?", options: ["Ranveer Singh", "Shahid Kapoor", "Ranbir Kapoor", "Rajkummar Rao"], answer: 0 },
  { prompt: "In Raazi, what does Sehmat do after her marriage?", options: ["Spies for India from inside a Pakistani military family", "Runs a school in Kashmir", "Joins the army", "Defects to Pakistan"], answer: 0 },
  { prompt: "Which war is Raazi set around?", options: ["The 1971 war", "Kargil in 1999", "The 1965 war", "The 1962 war"], answer: 0 },
  { prompt: "What is the surprise at the heart of Badhaai Ho?", options: ["A middle-aged mother is pregnant", "A father remarries", "A son fails his exams", "A wedding is called off"], answer: 0 },
  { prompt: "In which town is Stree set?", options: ["Chanderi", "Bareilly", "Bhopal", "Gwalior"], answer: 0 },
  { prompt: "What do the people of Chanderi write on their walls in Stree?", options: ["O Stree, kal aana", "Stree yahan nahi", "Stree ko bhagao", "Ghar khaali hai"], answer: 0 },
  { prompt: "Sanju is a biopic of which actor?", options: ["Sanjay Dutt", "Govinda", "Sunil Shetty", "Jackie Shroff"], answer: 0 },
  { prompt: "Who plays Sanjay Dutt in Sanju?", options: ["Ranbir Kapoor", "Ranveer Singh", "Vicky Kaushal", "Arjun Kapoor"], answer: 0 },
  { prompt: "Gully Boy is set in which Mumbai neighbourhood?", options: ["Dharavi", "Bandra", "Andheri", "Colaba"], answer: 0 },
  { prompt: "Gully Boy took its cue from which two real rappers?", options: ["Divine and Naezy", "Badshah and Raftaar", "Honey Singh and Badshah", "Prabh Deep and Seedhe Maut"], answer: 0 },
  { prompt: "Which line does Uri: The Surgical Strike keep asking?", options: ["How's the josh?", "All is well", "Apna time aayega", "No means no"], answer: 0 },
  { prompt: "Which actor leads Uri: The Surgical Strike?", options: ["Vicky Kaushal", "Sidharth Malhotra", "Varun Dhawan", "John Abraham"], answer: 0 },
  { prompt: "Article 15 is a police procedural about what?", options: ["Caste violence in rural India", "A stock market fraud", "A serial arsonist", "A kidnapping in Delhi"], answer: 0 },
  { prompt: "Super 30 is about a teacher who coaches students for which exam?", options: ["The IIT entrance exam", "The civil services exam", "The medical entrance exam", "The bar exam"], answer: 0 },
  { prompt: "Which two actors headline War (2019)?", options: ["Hrithik Roshan and Tiger Shroff", "Hrithik Roshan and Vicky Kaushal", "Tiger Shroff and Varun Dhawan", "Salman Khan and Hrithik Roshan"], answer: 0 },

  /* ── directors ── */
  { prompt: "Who directed Gangs of Wasseypur?", options: ["Anurag Kashyap", "Dibakar Banerjee", "Tigmanshu Dhulia", "Vishal Bhardwaj"], answer: 0 },
  { prompt: "Who directed Kahaani?", options: ["Sujoy Ghosh", "Sriram Raghavan", "Neeraj Pandey", "Ribhu Dasgupta"], answer: 0 },
  { prompt: "Who directed Queen?", options: ["Vikas Bahl", "Vikramaditya Motwane", "Anurag Basu", "Shoojit Sircar"], answer: 0 },
  { prompt: "Who directed Piku and Vicky Donor?", options: ["Shoojit Sircar", "Sujoy Ghosh", "Dibakar Banerjee", "Nitesh Tiwari"], answer: 0 },
  { prompt: "Who directed Dangal?", options: ["Nitesh Tiwari", "Rajkumar Hirani", "Kabir Khan", "Amit Sharma"], answer: 0 },
  { prompt: "Who directed Bajrangi Bhaijaan?", options: ["Kabir Khan", "Ali Abbas Zafar", "Sooraj Barjatya", "Prabhu Deva"], answer: 0 },
  { prompt: "Who directed Raazi?", options: ["Meghna Gulzar", "Zoya Akhtar", "Alankrita Shrivastava", "Konkona Sen Sharma"], answer: 0 },
  { prompt: "Who directed Udaan?", options: ["Vikramaditya Motwane", "Anurag Kashyap", "Abhishek Kapoor", "Neeraj Ghaywan"], answer: 0 },
  { prompt: "Who directed Barfi!?", options: ["Anurag Basu", "Anurag Kashyap", "Imtiaz Ali", "Ayan Mukerji"], answer: 0 },
  { prompt: "Who directed Wake Up Sid and Yeh Jawaani Hai Deewani?", options: ["Ayan Mukerji", "Karan Johar", "Punit Malhotra", "Shakun Batra"], answer: 0 },
  { prompt: "Which of these did Karan Johar direct?", options: ["My Name Is Khan", "Dostana", "Kapoor & Sons", "Ek Main Aur Ekk Tu"], answer: 0 },
  { prompt: "Who directed Singham and Chennai Express?", options: ["Rohit Shetty", "Sajid Khan", "Anees Bazmee", "Farah Khan"], answer: 0 },
  { prompt: "Who directed Masaan?", options: ["Neeraj Ghaywan", "Ritesh Batra", "Chaitanya Tamhane", "Avinash Arun"], answer: 0 },
  { prompt: "Who directed Bhaag Milkha Bhaag and Rang De Basanti?", options: ["Rakeysh Omprakash Mehra", "Ashutosh Gowariker", "Farhan Akhtar", "Nikkhil Advani"], answer: 0 },
  { prompt: "Which director made Khosla Ka Ghosla and Oye Lucky! Lucky Oye!?", options: ["Dibakar Banerjee", "Anurag Kashyap", "Hansal Mehta", "Rajat Kapoor"], answer: 0 },
  { prompt: "Which of these is a Sanjay Leela Bhansali film?", options: ["Guzaarish", "Kahaani", "Talaash", "Agneepath"], answer: 0 },
  { prompt: "Who directed Tanu Weds Manu and Raanjhanaa?", options: ["Anand L. Rai", "Imtiaz Ali", "Habib Faisal", "Maneesh Sharma"], answer: 0 },

  /* ── music ── */
  { prompt: "Which two Oscars did A. R. Rahman win for Slumdog Millionaire?", options: ["Best Original Score and Best Original Song", "Best Original Song and Best Sound", "Best Original Score and Best Editing", "Best Original Song and Best Picture"], answer: 0 },
  { prompt: "Who wrote the lyrics of 'Jai Ho'?", options: ["Gulzar", "Javed Akhtar", "Prasoon Joshi", "Irshad Kamil"], answer: 0 },
  { prompt: "Which Indian sound engineer won an Oscar for Slumdog Millionaire?", options: ["Resul Pookutty", "Nakul Kamte", "Biswadeep Chatterjee", "Subash Sahoo"], answer: 0 },
  { prompt: "Which song belongs to Bunty Aur Babli?", options: ["Kajra Re", "Chikni Chameli", "Sheila Ki Jawani", "Munni Badnaam Hui"], answer: 0 },
  { prompt: "'Munni Badnaam Hui' is from which film?", options: ["Dabangg", "Tees Maar Khan", "Agneepath", "Singham"], answer: 0 },
  { prompt: "'Sheila Ki Jawani' is from which film?", options: ["Tees Maar Khan", "Dabangg", "Bodyguard", "Ready"], answer: 0 },
  { prompt: "'Chikni Chameli' is from which film?", options: ["Agneepath", "Dabangg 2", "Ram-Leela", "Kick"], answer: 0 },
  { prompt: "Which film gave Arijit Singh his breakout in 'Tum Hi Ho'?", options: ["Aashiqui 2", "Ek Villain", "Rockstar", "Raabta"], answer: 0 },
  { prompt: "Who composed the music for Dil Chahta Hai, Kal Ho Naa Ho and Rock On!!?", options: ["Shankar–Ehsaan–Loy", "Vishal–Shekhar", "Pritam", "Salim–Sulaiman"], answer: 0 },
  { prompt: "Who composed the music for Gangs of Wasseypur?", options: ["Sneha Khanwalkar", "Amit Trivedi", "Ram Sampath", "Vishal Bhardwaj"], answer: 0 },
  { prompt: "Who composed the music for Dev.D and Udaan?", options: ["Amit Trivedi", "Pritam", "Mithoon", "Sachin–Jigar"], answer: 0 },
  { prompt: "Which song is from Rockstar?", options: ["Sadda Haq", "Emotional Atyachaar", "Bhaag DK Bose", "Malhari"], answer: 0 },
  { prompt: "'Emotional Atyachaar' belongs to which film?", options: ["Dev.D", "Delhi Belly", "Gangs of Wasseypur", "Udaan"], answer: 0 },
  { prompt: "'Apna Time Aayega' is from which film?", options: ["Gully Boy", "Sanju", "Article 15", "Super 30"], answer: 0 },
  { prompt: "Which film features 'Deewani Mastani'?", options: ["Bajirao Mastani", "Padmaavat", "Ram-Leela", "Devdas"], answer: 0 },
  { prompt: "'Ghoomar' is the big set-piece dance of which film?", options: ["Padmaavat", "Bajirao Mastani", "Jodhaa Akbar", "Ram-Leela"], answer: 0 },
  { prompt: "Which singer's voice carries 'Masakali' in Delhi-6?", options: ["Mohit Chauhan", "Sonu Nigam", "KK", "Shaan"], answer: 0 },
  { prompt: "Who wrote the lyrics for Taare Zameen Par and Rang De Basanti?", options: ["Prasoon Joshi", "Gulzar", "Javed Akhtar", "Swanand Kirkire"], answer: 0 },
  { prompt: "Which lyricist wrote 'Beedi' and the rest of Omkara?", options: ["Gulzar", "Javed Akhtar", "Irshad Kamil", "Amitabh Bhattacharya"], answer: 0 },
  { prompt: "Which film gave Shreya Ghoshal her first playback songs in Hindi cinema?", options: ["Devdas", "Guru", "Jab We Met", "Om Shanti Om"], answer: 0 },
  { prompt: "Who composed Jab We Met, Yeh Jawaani Hai Deewani and Barfi!?", options: ["Pritam", "A. R. Rahman", "Amit Trivedi", "Vishal–Shekhar"], answer: 0 },
  { prompt: "Which film's soundtrack includes 'Kun Faya Kun'?", options: ["Rockstar", "Highway", "Tamasha", "Delhi-6"], answer: 0 },

  /* ── careers and debuts ── */
  { prompt: "Which film was Ranveer Singh's debut?", options: ["Band Baaja Baaraat", "Ladies vs Ricky Bahl", "Lootera", "Gunday"], answer: 0 },
  { prompt: "Which film was Ranbir Kapoor's debut?", options: ["Saawariya", "Wake Up Sid", "Bachna Ae Haseeno", "Rocket Singh"], answer: 0 },
  { prompt: "Which film was Alia Bhatt's debut?", options: ["Student of the Year", "Highway", "2 States", "Humpty Sharma Ki Dulhania"], answer: 0 },
  { prompt: "Which film was Vidya Balan's Hindi debut?", options: ["Parineeta", "Lage Raho Munna Bhai", "Bhool Bhulaiyaa", "Paa"], answer: 0 },
  { prompt: "Which film was Kangana Ranaut's debut?", options: ["Gangster", "Fashion", "Tanu Weds Manu", "Woh Lamhe"], answer: 0 },
  { prompt: "Which film was Sushant Singh Rajput's debut?", options: ["Kai Po Che!", "Shuddh Desi Romance", "M.S. Dhoni: The Untold Story", "Detective Byomkesh Bakshy!"], answer: 0 },
  { prompt: "Which film was Vicky Kaushal's first leading role?", options: ["Masaan", "Raazi", "Sanju", "Uri: The Surgical Strike"], answer: 0 },
  { prompt: "Farhan Akhtar made his acting debut in which film?", options: ["Rock On!!", "Luck by Chance", "Zindagi Na Milegi Dobara", "Bhaag Milkha Bhaag"], answer: 0 },
  { prompt: "Zoya Akhtar and Farhan Akhtar are the children of which writer?", options: ["Javed Akhtar", "Salim Khan", "Gulzar", "Kamlesh Pandey"], answer: 0 },
  { prompt: "Which actor plays M. S. Dhoni in his 2016 biopic?", options: ["Sushant Singh Rajput", "Ranveer Singh", "Rajkummar Rao", "Vicky Kaushal"], answer: 0 },
  { prompt: "Priyanka Chopra played which boxer on screen?", options: ["Mary Kom", "Sarita Devi", "Lovlina Borgohain", "Nikhat Zareen"], answer: 0 },
  { prompt: "Which actor appears in both Gangs of Wasseypur and Kahaani?", options: ["Nawazuddin Siddiqui", "Pankaj Tripathi", "Manoj Bajpayee", "Vineet Kumar Singh"], answer: 0 },
  { prompt: "Which film won Irrfan Khan the National Award for Best Actor?", options: ["Paan Singh Tomar", "The Lunchbox", "Haider", "Hindi Medium"], answer: 0 },
  { prompt: "Which of these films did Amitabh Bachchan not appear in?", options: ["Gully Boy", "Black", "Piku", "Pink"], answer: 0 },
  { prompt: "Which film brought Aamir Khan back to a village and a cricket bat in 2001?", options: ["Lagaan", "Mangal Pandey: The Rising", "Swades", "Peepli Live"], answer: 0 },

  /* ── awards and records ── */
  { prompt: "Which 2001 film was nominated for the Best Foreign Language Film Oscar?", options: ["Lagaan", "Devdas", "Dil Chahta Hai", "Monsoon Wedding"], answer: 0 },
  { prompt: "Which film is usually named as the first Hindi film to take ₹100 crore at the domestic box office?", options: ["Ghajini", "3 Idiots", "Dabangg", "Krrish"], answer: 0 },
  { prompt: "Which of these was India's official Oscar submission?", options: ["Newton", "Andhadhun", "Pink", "Queen"], answer: 0 },
  { prompt: "Which film was India's official Oscar submission for 2019?", options: ["Gully Boy", "Uri: The Surgical Strike", "Article 15", "Super 30"], answer: 0 },
  { prompt: "Barfi! was India's Oscar submission in which year?", options: ["2012", "2010", "2014", "2016"], answer: 0 },
  { prompt: "Which actor has won National Awards for both Paa and Piku?", options: ["Amitabh Bachchan", "Irrfan Khan", "Nawazuddin Siddiqui", "Manoj Bajpayee"], answer: 0 },
  { prompt: "Which film won Kangana Ranaut a National Award for Best Actress?", options: ["Queen", "Fashion", "Gangster", "Manikarnika"], answer: 0 },

  /* ── lines and lore ── */
  { prompt: "'Thappad se darr nahi lagta sahab, pyaar se lagta hai' comes from which film?", options: ["Gangs of Wasseypur", "Dabangg", "Singham", "Omkara"], answer: 0 },
  { prompt: "Which film popularised 'Kehte hain agar kisi cheez ko dil se chaaho…'?", options: ["Om Shanti Om", "Main Hoon Na", "Kal Ho Naa Ho", "Veer-Zaara"], answer: 0 },
  { prompt: "'Ek baar jo maine commitment kar di…' is the calling card of which 2009 film?", options: ["Wanted", "Dabangg", "Bodyguard", "Ready"], answer: 0 },
  { prompt: "Which cop does Ajay Devgn play for Rohit Shetty?", options: ["Bajirao Singham", "Sangram Bhalerao", "Chulbul Pandey", "Kabir Khan"], answer: 0 },
  { prompt: "Which cop does Ranveer Singh play in Simmba?", options: ["Sangram Bhalerao", "Bajirao Singham", "Vihaan Shergill", "Ayan Ranjan"], answer: 0 },
  { prompt: "In Hera Pheri, what is Paresh Rawal's character called?", options: ["Baburao Ganpatrao Apte", "Raju", "Shyam", "Kadar Bhai"], answer: 0 },
  { prompt: "Which trio starred in Hera Pheri?", options: ["Akshay Kumar, Suniel Shetty and Paresh Rawal", "Akshay Kumar, Govinda and Paresh Rawal", "Suniel Shetty, Ajay Devgn and Paresh Rawal", "Akshay Kumar, Suniel Shetty and Johnny Lever"], answer: 0 },
  { prompt: "Bhool Bhulaiyaa's ghost is named what?", options: ["Manjulika", "Stree", "Shabana", "Chandramukhi"], answer: 0 },
  { prompt: "In Ra.One, what is Shah Rukh Khan's heroic character called?", options: ["G.One", "Ra.One", "Krrish", "Drona"], answer: 0 },
  { prompt: "Which superhero film has Hrithik Roshan wearing a black mask and a long coat?", options: ["Krrish", "Ra.One", "Drona", "Mr. India"], answer: 0 },
  { prompt: "In Yeh Jawaani Hai Deewani, where does the trek at the start of the film go?", options: ["Manali", "Ladakh", "Sikkim", "Rishikesh"], answer: 0 },
  { prompt: "Which film has Shah Rukh Khan playing a Gujarati bootlegger?", options: ["Raees", "Don", "Fan", "Dilwale"], answer: 0 },
  { prompt: "Which film has Shah Rukh Khan playing both a star and his obsessive lookalike fan?", options: ["Fan", "Ra.One", "Duplicate", "Don 2"], answer: 0 },
  { prompt: "Udta Punjab is about what?", options: ["A drug epidemic in Punjab", "A farmers' protest", "A pop star's comeback", "A police force in Amritsar"], answer: 0 },
  { prompt: "Which film has Nawazuddin Siddiqui playing a serial killer for Anurag Kashyap?", options: ["Raman Raghav 2.0", "Badlapur", "Manjhi", "Monsoon Shootout"], answer: 0 },
  { prompt: "Which of these is a Neeraj Pandey film?", options: ["A Wednesday", "Talvar", "Drishyam", "Kahaani"], answer: 0 },
  { prompt: "Drishyam (2015) is a Hindi remake of a film from which industry?", options: ["Malayalam", "Tamil", "Telugu", "Kannada"], answer: 0 },
  { prompt: "Kabir Singh is a remake of which film?", options: ["Arjun Reddy", "Vikram Vedha", "Jersey", "Pink"], answer: 0 },
  { prompt: "Which film has Amitabh Bachchan as a lawyer defending three young women in Delhi?", options: ["Pink", "Badla", "Wazir", "Te3n"], answer: 0 },
  { prompt: "Which of these films is set in Chhattisgarh's forests on polling day?", options: ["Newton", "Sonchiriya", "Mukkabaaz", "Peepli Live"], answer: 0 },
  { prompt: "Peepli Live is a satire about what?", options: ["A farmer's announced suicide becoming a news circus", "A film shoot in a village", "An election campaign", "A cricket match fixed for TV"], answer: 0 },
  { prompt: "Which film follows a young man from a Delhi bungalow to a Punjab wedding-planning business?", options: ["Band Baaja Baaraat", "Vicky Donor", "Dum Laga Ke Haisha", "Shuddh Desi Romance"], answer: 0 },
  { prompt: "Dil Dhadakne Do takes place mostly where?", options: ["On a cruise ship", "On a train", "In a hill station", "At a resort in Goa"], answer: 0 },
  { prompt: "Which of these films is not directed by Zoya Akhtar?", options: ["Highway", "Luck by Chance", "Dil Dhadakne Do", "Gully Boy"], answer: 0 },
  { prompt: "Which film pairs Kareena Kapoor and Shahid Kapoor on a train to Punjab?", options: ["Jab We Met", "Chup Chup Ke", "Milenge Milenge", "36 China Town"], answer: 0 },
];
