import type { MatchItem } from "@curio/core";

/** Film to the person behind it. Four are drawn per question. */
export const match: MatchItem[] = [
  { left: "Sholay", right: "Ramesh Sippy" },
  { left: "Mughal-e-Azam", right: "K. Asif" },
  { left: "Mother India", right: "Mehboob Khan" },
  { left: "Pyaasa", right: "Guru Dutt" },
  { left: "Awara", right: "Raj Kapoor" },
  { left: "Do Bigha Zamin", right: "Bimal Roy" },
  { left: "Anand", right: "Hrishikesh Mukherjee" },
  { left: "Lagaan", right: "Ashutosh Gowariker" },
  { left: "Dil Chahta Hai", right: "Farhan Akhtar" },
  { left: "Zindagi Na Milegi Dobara", right: "Zoya Akhtar" },
  { left: "3 Idiots", right: "Rajkumar Hirani" },
  { left: "Devdas (2002)", right: "Sanjay Leela Bhansali" },
  { left: "Dil Se..", right: "Mani Ratnam" },
  { left: "Gangs of Wasseypur", right: "Anurag Kashyap" },
  { left: "Omkara", right: "Vishal Bhardwaj" },
  { left: "Kuch Kuch Hota Hai", right: "Karan Johar" },
  { left: "Dilwale Dulhania Le Jayenge", right: "Aditya Chopra" },
  { left: "Hum Aapke Hain Koun..!", right: "Sooraj Barjatya" },
  { left: "Rang De Basanti", right: "Rakeysh Omprakash Mehra" },
  { left: "Jab We Met", right: "Imtiaz Ali" },
  { left: "Barfi!", right: "Anurag Basu" },
  { left: "Singham", right: "Rohit Shetty" },
  { left: "Raazi", right: "Meghna Gulzar" },
  { left: "English Vinglish", right: "Gauri Shinde" },
  { left: "Queen", right: "Vikas Bahl" },
  { left: "Andhadhun", right: "Sriram Raghavan" },
  { left: "Chak De! India", right: "Shimit Amin" },
  { left: "Ankur", right: "Shyam Benegal" },
  { left: "Aandhi", right: "Gulzar" },
  { left: "Yeh Jawaani Hai Deewani", right: "Ayan Mukerji" },
  { left: "Newton", right: "Amit V. Masurkar" },
  { left: "Masaan", right: "Neeraj Ghaywan" },
  { left: "Court", right: "Chaitanya Tamhane" },
  { left: "The Lunchbox", right: "Ritesh Batra" },
  { left: "Peepli Live", right: "Anusha Rizvi" },
  { left: "Bandit Queen", right: "Shekhar Kapur" },
  { left: "Mr. India", right: "Shekhar Kapur" },
  { left: "Satya", right: "Ram Gopal Varma" },
  { left: "Taare Zameen Par", right: "Aamir Khan" },
  { left: "Swades", right: "Ashutosh Gowariker" },
];
