import type { MatchItem } from "@curio/core";

/**
 * Film to the director behind it. Four are drawn per question.
 *
 * Every right-hand name appears once, so a drawn set never offers two
 * indistinguishable pairings.
 */
export const match: MatchItem[] = [
  { left: "Lagaan", right: "Ashutosh Gowariker" },
  { left: "Dil Chahta Hai", right: "Farhan Akhtar" },
  { left: "Devdas (2002)", right: "Sanjay Leela Bhansali" },
  { left: "Company", right: "Ram Gopal Varma" },
  { left: "Gadar: Ek Prem Katha", right: "Anil Sharma" },
  { left: "Munna Bhai M.B.B.S.", right: "Rajkumar Hirani" },
  { left: "Kal Ho Naa Ho", right: "Nikkhil Advani" },
  { left: "Koi... Mil Gaya", right: "Rakesh Roshan" },
  { left: "Dhoom", right: "Sanjay Gadhvi" },
  { left: "Main Hoon Na", right: "Farah Khan" },
  { left: "Veer-Zaara", right: "Yash Chopra" },
  { left: "No Entry", right: "Anees Bazmee" },
  { left: "Rang De Basanti", right: "Rakeysh Omprakash Mehra" },
  { left: "Omkara", right: "Vishal Bhardwaj" },
  { left: "Khosla Ka Ghosla", right: "Dibakar Banerjee" },
  { left: "Fashion", right: "Madhur Bhandarkar" },
  { left: "Chak De! India", right: "Shimit Amin" },
  { left: "Jab We Met", right: "Imtiaz Ali" },
  { left: "Guru", right: "Mani Ratnam" },
  { left: "Bhool Bhulaiyaa", right: "Priyadarshan" },
  { left: "Taare Zameen Par", right: "Aamir Khan" },
  { left: "Rock On!!", right: "Abhishek Kapoor" },
  { left: "Rab Ne Bana Di Jodi", right: "Aditya Chopra" },
  { left: "A Wednesday", right: "Neeraj Pandey" },
  { left: "Dev.D", right: "Anurag Kashyap" },
  { left: "Wake Up Sid", right: "Ayan Mukerji" },
  { left: "My Name Is Khan", right: "Karan Johar" },
  { left: "Udaan", right: "Vikramaditya Motwane" },
  { left: "Peepli Live", right: "Anusha Rizvi" },
  { left: "Band Baaja Baaraat", right: "Maneesh Sharma" },
  { left: "Zindagi Na Milegi Dobara", right: "Zoya Akhtar" },
  { left: "Singham", right: "Rohit Shetty" },
  { left: "Tanu Weds Manu", right: "Anand L. Rai" },
  { left: "Kahaani", right: "Sujoy Ghosh" },
  { left: "Barfi!", right: "Anurag Basu" },
  { left: "Vicky Donor", right: "Shoojit Sircar" },
  { left: "Paan Singh Tomar", right: "Tigmanshu Dhulia" },
  { left: "English Vinglish", right: "Gauri Shinde" },
  { left: "Cocktail", right: "Homi Adajania" },
  { left: "The Lunchbox", right: "Ritesh Batra" },
  { left: "Shahid", right: "Hansal Mehta" },
  { left: "Aashiqui 2", right: "Mohit Suri" },
  { left: "Ship of Theseus", right: "Anand Gandhi" },
  { left: "Queen", right: "Vikas Bahl" },
  { left: "Masaan", right: "Neeraj Ghaywan" },
  { left: "Bajrangi Bhaijaan", right: "Kabir Khan" },
  { left: "Drishyam (2015)", right: "Nishikant Kamat" },
  { left: "Sultan", right: "Ali Abbas Zafar" },
  { left: "Dangal", right: "Nitesh Tiwari" },
  { left: "Pink", right: "Aniruddha Roy Chowdhury" },
  { left: "Neerja", right: "Ram Madhvani" },
  { left: "Udta Punjab", right: "Abhishek Chaubey" },
  { left: "Newton", right: "Amit Masurkar" },
  { left: "Hindi Medium", right: "Saket Chaudhary" },
  { left: "Secret Superstar", right: "Advait Chandan" },
  { left: "Bareilly Ki Barfi", right: "Ashwiny Iyer Tiwari" },
  { left: "Lipstick Under My Burkha", right: "Alankrita Shrivastava" },
  { left: "Andhadhun", right: "Sriram Raghavan" },
  { left: "Raazi", right: "Meghna Gulzar" },
  { left: "Badhaai Ho", right: "Amit Sharma" },
  { left: "Stree", right: "Amar Kaushik" },
  { left: "Uri: The Surgical Strike", right: "Aditya Dhar" },
  { left: "Article 15", right: "Anubhav Sinha" },
  { left: "Kabir Singh", right: "Sandeep Reddy Vanga" },
  { left: "War", right: "Siddharth Anand" },
];
