import type { OddOneOutItem } from "@curio/core";

/** Three belong together, one doesn't, and `why` says so on the reveal. */
export const oddOneOut: OddOneOutItem[] = [
  { items: ["Shah Rukh Khan", "Salman Khan", "Aamir Khan", "Akshay Kumar"], answer: 3, why: "The other three are the Khans." },
  { items: ["Sholay", "Deewaar", "Zanjeer", "Mughal-e-Azam"], answer: 3, why: "The other three were written by Salim-Javed." },
  { items: ["Maqbool", "Omkara", "Haider", "Kaminey"], answer: 3, why: "The other three are Vishal Bhardwaj's Shakespeare adaptations." },
  { items: ["Lata Mangeshkar", "Asha Bhosle", "Kishore Kumar", "Madhubala"], answer: 3, why: "The other three are playback singers." },
  { items: ["Raj Kapoor", "Guru Dutt", "Bimal Roy", "Dilip Kumar"], answer: 3, why: "The other three directed as well as acted or produced." },
  { items: ["Gryffindor", "Dharma", "Yash Raj", "Rajshri"], answer: 0, why: "The other three are film production houses." },
  { items: ["Munna Bhai M.B.B.S.", "Lage Raho Munna Bhai", "3 Idiots", "Dil Chahta Hai"], answer: 3, why: "The other three are Rajkumar Hirani films." },
  { items: ["Goa", "Spain", "Manali", "Pondicherry"], answer: 1, why: "Zindagi Na Milegi Dobara went to Spain; the rest are Dil Chahta Hai country." },
  { items: ["Quidditch", "Kabaddi", "Hockey", "Wrestling"], answer: 0, why: "The other three have carried Hindi sports films." },
  { items: ["Kaho Naa... Pyaar Hai", "Koi... Mil Gaya", "Krrish", "Dhoom"], answer: 3, why: "The other three are Rakesh Roshan's films with Hrithik." },
  { items: ["Mother India", "Lagaan", "Salaam Bombay!", "Sholay"], answer: 3, why: "The other three were Oscar-nominated in the foreign film category." },
  { items: ["Nargis", "Meena Kumari", "Madhubala", "Sridevi"], answer: 3, why: "The other three belong to the black-and-white era." },
  { items: ["Pyaasa", "Kaagaz Ke Phool", "Sahib Bibi Aur Ghulam", "Awara"], answer: 3, why: "The other three are Guru Dutt's." },
  { items: ["Chennai", "Kolkata", "Hyderabad", "Mumbai"], answer: 3, why: "Bollywood is Mumbai; the rest head other industries." },
  { items: ["A. R. Rahman", "R. D. Burman", "S. D. Burman", "Javed Akhtar"], answer: 3, why: "Javed Akhtar writes; the others compose." },
  { items: ["Gulzar", "Sahir Ludhianvi", "Shailendra", "Yash Chopra"], answer: 3, why: "The other three are lyricists." },
  { items: ["Kahaani", "Drishyam", "Andhadhun", "Chennai Express"], answer: 3, why: "The other three are thrillers." },
  { items: ["Barfi!", "Black", "Taare Zameen Par", "Dabangg"], answer: 3, why: "The other three centre on disability." },
  { items: ["Dangal", "Sultan", "Mary Kom", "Piku"], answer: 3, why: "The other three are about athletes." },
  { items: ["Queen", "English Vinglish", "Piku", "Singham"], answer: 3, why: "The other three are led by a woman's story." },
  { items: ["Gully Boy", "Rockstar", "Aashiqui 2", "Drishyam"], answer: 3, why: "The other three are about musicians." },
  { items: ["Amitabh Bachchan", "Vinod Khanna", "Shatrughan Sinha", "Ranveer Singh"], answer: 3, why: "The other three are 1970s leading men." },
  { items: ["Bajirao Mastani", "Padmaavat", "Jodhaa Akbar", "Wake Up Sid"], answer: 3, why: "The other three are historical epics." },
  { items: ["Deewaar", "Trishul", "Kaala Patthar", "Chupke Chupke"], answer: 3, why: "The other three are Amitabh's angry-young-man films." },
  { items: ["Hera Pheri", "Andaz Apna Apna", "Golmaal", "Satya"], answer: 3, why: "The other three are comedies." },
  { items: ["Satya", "Company", "Sarkar", "Swades"], answer: 3, why: "The other three are Ram Gopal Varma's." },
  { items: ["Kishore Kumar", "Mohammed Rafi", "Mukesh", "Naushad"], answer: 3, why: "Naushad composed; the others sang." },
  { items: ["Filmfare", "National Film Award", "IIFA", "Booker"], answer: 3, why: "The Booker is for fiction." },
  { items: ["Nagin", "Naagin", "Sheshnaag", "Sholay"], answer: 3, why: "The other three are snake films." },
  { items: ["Dhoom", "Dhoom 2", "Dhoom 3", "Race"], answer: 3, why: "The other three are the same franchise." },
  { items: ["Karan Johar", "Zoya Akhtar", "Farhan Akhtar", "Nawazuddin Siddiqui"], answer: 3, why: "The other three direct." },
  { items: ["Shabana Azmi", "Smita Patil", "Naseeruddin Shah", "Govinda"], answer: 3, why: "The other three are parallel-cinema names." },
  { items: ["Chak De! India", "Lagaan", "Iqbal", "Kabhi Khushi Kabhie Gham"], answer: 3, why: "The other three are sports films." },
  { items: ["Maratha Mandir", "Regal", "Liberty", "Wankhede"], answer: 3, why: "Wankhede is a cricket stadium; the rest are Mumbai cinemas." },
  { items: ["Paro", "Chandramukhi", "Devdas", "Anarkali"], answer: 3, why: "The other three are from Devdas." },
  { items: ["Jai", "Veeru", "Basanti", "Vijay"], answer: 3, why: "The other three are from Sholay." },
  { items: ["Rancho", "Farhan", "Raju", "Circuit"], answer: 3, why: "The other three are the 3 Idiots; Circuit is Munna Bhai's." },
  { items: ["Prithviraj Kapoor", "Raj Kapoor", "Rishi Kapoor", "Dharmendra"], answer: 3, why: "The other three are Kapoors." },
  { items: ["Kajol", "Rani Mukerji", "Tanuja", "Juhi Chawla"], answer: 3, why: "The other three are one family." },
  { items: ["Bhaag Milkha Bhaag", "Mary Kom", "Neerja", "Andhadhun"], answer: 3, why: "The other three are biopics." },
];
