import type { OddOneOutItem } from "@curio/core";

/** Three belong together, one doesn't, and `why` says so on the reveal. */
export const oddOneOut: OddOneOutItem[] = [
  { items: ["Shah Rukh Khan", "Salman Khan", "Aamir Khan", "Akshay Kumar"], answer: 3, why: "The other three are the Khans." },
  { items: ["Munna Bhai M.B.B.S.", "3 Idiots", "PK", "Barfi!"], answer: 3, why: "The other three are Rajkumar Hirani's." },
  { items: ["Maqbool", "Omkara", "Haider", "Kaminey"], answer: 3, why: "The other three are Vishal Bhardwaj's Shakespeare adaptations." },
  { items: ["Lagaan", "Swades", "Jodhaa Akbar", "Rang De Basanti"], answer: 3, why: "The other three are Ashutosh Gowariker's." },
  { items: ["Dil Chahta Hai", "Lakshya", "Don", "Rock On!!"], answer: 3, why: "Farhan Akhtar directed the other three; he only acted in Rock On!!." },
  { items: ["Luck by Chance", "Zindagi Na Milegi Dobara", "Dil Dhadakne Do", "Wake Up Sid"], answer: 3, why: "The other three are Zoya Akhtar's." },
  { items: ["Highway", "Tamasha", "Rockstar", "Queen"], answer: 3, why: "The other three are Imtiaz Ali's." },
  { items: ["Gangs of Wasseypur", "Dev.D", "Ugly", "Barfi!"], answer: 3, why: "The other three are Anurag Kashyap's; Barfi! is Anurag Basu's." },
  { items: ["Udaan", "Lootera", "Trapped", "Masaan"], answer: 3, why: "The other three are Vikramaditya Motwane's." },
  { items: ["Golmaal", "Singham", "Simmba", "Dabangg"], answer: 3, why: "The other three are Rohit Shetty's." },
  { items: ["Devdas", "Black", "Guzaarish", "Barfi!"], answer: 3, why: "The other three are Sanjay Leela Bhansali's." },
  { items: ["Vicky Donor", "Piku", "Madras Cafe", "Kahaani"], answer: 3, why: "The other three are Shoojit Sircar's." },
  { items: ["A Wednesday", "Special 26", "Baby", "Drishyam"], answer: 3, why: "The other three are Neeraj Pandey's." },
  { items: ["Om Shanti Om", "Main Hoon Na", "Happy New Year", "Chennai Express"], answer: 3, why: "The other three are Farah Khan's." },
  { items: ["Koi... Mil Gaya", "Krrish", "Kaho Naa... Pyaar Hai", "Dhoom 2"], answer: 3, why: "Rakesh Roshan directed the other three." },
  { items: ["Dabangg", "Wanted", "Bodyguard", "Ghajini"], answer: 3, why: "The other three are Salman Khan's; Ghajini is Aamir's." },
  { items: ["Ghajini", "Dhoom 3", "Talaash", "Krrish"], answer: 3, why: "The other three are Aamir Khan's; Krrish is Hrithik's." },
  { items: ["Chak De! India", "Iqbal", "Bhaag Milkha Bhaag", "Kahaani"], answer: 3, why: "The other three are sports films." },
  { items: ["Dangal", "Sultan", "Mary Kom", "Piku"], answer: 3, why: "The other three are about athletes." },
  { items: ["M.S. Dhoni: The Untold Story", "Bhaag Milkha Bhaag", "Dangal", "Chak De! India"], answer: 3, why: "The other three are about real sportspeople; Kabir Khan is invented." },
  { items: ["Barfi!", "Black", "Taare Zameen Par", "Dabangg"], answer: 3, why: "The other three centre on disability." },
  { items: ["Gully Boy", "Rockstar", "Rock On!!", "Drishyam"], answer: 3, why: "The other three are about musicians." },
  { items: ["Kahaani", "Drishyam", "Andhadhun", "Chennai Express"], answer: 3, why: "The other three are thrillers." },
  { items: ["Queen", "English Vinglish", "Piku", "Singham"], answer: 3, why: "The other three are led by a woman's story." },
  { items: ["Tanu Weds Manu", "Queen", "Manikarnika", "Kahaani"], answer: 3, why: "The other three are Kangana Ranaut's; Kahaani is Vidya Balan's." },
  { items: ["The Dirty Picture", "Kahaani", "Ishqiya", "Queen"], answer: 3, why: "The other three are Vidya Balan's." },
  { items: ["Bajirao Mastani", "Jodhaa Akbar", "Padmaavat", "Dangal"], answer: 3, why: "The other three are period films in court dress." },
  { items: ["Uri: The Surgical Strike", "Raazi", "Airlift", "Stree"], answer: 3, why: "The other three come from real events." },
  { items: ["Neerja", "Mary Kom", "Sanju", "Barfi!"], answer: 3, why: "The other three are biopics." },
  { items: ["Lagaan", "Devdas", "Barfi!", "Dangal"], answer: 3, why: "The other three were India's official Oscar entries." },
  { items: ["Ghajini", "Wanted", "Singham", "Chennai Express"], answer: 3, why: "The other three are remakes of southern hits." },
  { items: ["3 Idiots", "Kai Po Che!", "2 States", "Rang De Basanti"], answer: 3, why: "The other three come from Chetan Bhagat novels." },
  { items: ["Saawariya", "Band Baaja Baaraat", "Student of the Year", "Rockstar"], answer: 3, why: "The other three were launches — Ranbir, Ranveer, and the class of 2012." },
  { items: ["Bajirao Singham", "Sangram Bhalerao", "Chulbul Pandey", "Kabir Khan"], answer: 3, why: "The other three are policemen; Kabir Khan coaches hockey." },
  { items: ["Delhi-6", "Vicky Donor", "Band Baaja Baaraat", "Masaan"], answer: 3, why: "The other three are Delhi films; Masaan is Banaras." },
  { items: ["Kal Ho Naa Ho", "My Name Is Khan", "English Vinglish", "Jab We Met"], answer: 3, why: "The other three are set in America." },
  { items: ["Spain", "Amsterdam", "New York", "Bhatinda"], answer: 3, why: "The other three are where these films went abroad." },
  { items: ["Zindagi Na Milegi Dobara", "Dil Chahta Hai", "Kai Po Che!", "Piku"], answer: 3, why: "The other three are about three friends." },
  { items: ["Stree", "Tumbbad", "Bhool Bhulaiyaa", "Badhaai Ho"], answer: 3, why: "The other three are horror." },
  { items: ["Pink", "Article 15", "Newton", "Golmaal Again"], answer: 3, why: "The other three argue about the state of the country." },
  { items: ["Nawazuddin Siddiqui", "Irrfan Khan", "Rajkummar Rao", "Karan Johar"], answer: 3, why: "The other three are actors first." },
  { items: ["Arijit Singh", "Shreya Ghoshal", "Sonu Nigam", "Pritam"], answer: 3, why: "The other three sing; Pritam composes." },
  { items: ["A. R. Rahman", "Amit Trivedi", "Pritam", "Gulzar"], answer: 3, why: "The other three compose; Gulzar writes the words." },
  { items: ["Gulzar", "Prasoon Joshi", "Irshad Kamil", "Sunidhi Chauhan"], answer: 3, why: "The other three are lyricists." },
  { items: ["Dhoom", "Dhoom 2", "Dhoom 3", "Don 2"], answer: 3, why: "The other three are one franchise." },
  { items: ["Shah Rukh Khan", "Preity Zinta", "Juhi Chawla", "Aamir Khan"], answer: 3, why: "The other three have owned a share of an IPL team." },
];
