import type { TrueFalseItem } from "@curio/core";

/** A statement to accept or reject. `note` explains the trap on a miss. */
export const truefalse: TrueFalseItem[] = [
  /* ── the record books ── */
  { statement: "Lagaan was nominated for the Best Foreign Language Film Oscar.", answer: true },
  { statement: "Lagaan won the Academy Award for Best Foreign Language Film.", answer: false, note: "It was nominated and lost to No Man's Land." },
  { statement: "A. R. Rahman won two Academy Awards in a single night for Slumdog Millionaire.", answer: true, note: "Best Original Score and Best Original Song." },
  { statement: "Gulzar shared an Academy Award for the lyrics of 'Jai Ho'.", answer: true },
  { statement: "Slumdog Millionaire was directed by Danny Boyle.", answer: true },
  { statement: "Resul Pookutty won an Oscar for sound on Slumdog Millionaire.", answer: true },
  { statement: "Ghajini is usually named as the first Hindi film to take ₹100 crore at home.", answer: true },
  { statement: "Dangal took more money in China than it did in India.", answer: true },
  { statement: "The Lunchbox was India's official entry for the Oscars.", answer: false, note: "It was passed over for The Good Road, which caused a public row." },
  { statement: "Newton was India's official Oscar entry in 2017.", answer: true },
  { statement: "Gully Boy was India's official Oscar entry in 2019.", answer: true },
  { statement: "Barfi! was India's official Oscar entry in 2012.", answer: true },
  { statement: "Devdas (2002) was the most expensive Hindi film made up to that point.", answer: true },
  { statement: "Devdas (2002) screened at the Cannes Film Festival.", answer: true },
  { statement: "Gangs of Wasseypur premiered at the Cannes Directors' Fortnight.", answer: true },

  /* ── who made what ── */
  { statement: "Aamir Khan directed Taare Zameen Par.", answer: true },
  { statement: "Aamir Khan directed 3 Idiots.", answer: false, note: "Rajkumar Hirani directed it; Aamir starred." },
  { statement: "Rajkumar Hirani directed Munna Bhai M.B.B.S., 3 Idiots, PK and Sanju.", answer: true },
  { statement: "Farhan Akhtar's first film as director was Dil Chahta Hai.", answer: true },
  { statement: "Zoya Akhtar directed Zindagi Na Milegi Dobara.", answer: true },
  { statement: "Farhan Akhtar directed Zindagi Na Milegi Dobara.", answer: false, note: "His sister Zoya did; he acted in it." },
  { statement: "Zoya Akhtar and Farhan Akhtar are Javed Akhtar's children.", answer: true },
  { statement: "Anurag Kashyap directed Gangs of Wasseypur.", answer: true },
  { statement: "Anurag Basu and Anurag Kashyap are the same person.", answer: false, note: "Basu made Barfi!; Kashyap made Gangs of Wasseypur." },
  { statement: "Vishal Bhardwaj composes the music for his own films.", answer: true },
  { statement: "Vishal Bhardwaj worked as a music director before he directed films.", answer: true },
  { statement: "Sanjay Leela Bhansali directed Black, Bajirao Mastani and Padmaavat.", answer: true },
  { statement: "Dabangg was directed by Arbaaz Khan.", answer: false, note: "Arbaaz produced it and acted in it; Abhinav Kashyap directed." },
  { statement: "Farah Khan worked as a choreographer before she directed.", answer: true },
  { statement: "Meghna Gulzar directed Raazi.", answer: true },
  { statement: "Shoojit Sircar directed Vicky Donor and Piku.", answer: true },
  { statement: "Sriram Raghavan directed Andhadhun.", answer: true },
  { statement: "Karan Johar directed Kapoor & Sons.", answer: false, note: "Shakun Batra directed it; Dharma produced it." },
  { statement: "Imtiaz Ali directed Jab We Met, Rockstar and Tamasha.", answer: true },
  { statement: "Ashutosh Gowariker directed both Lagaan and Swades.", answer: true },
  { statement: "Nitesh Tiwari directed Dangal.", answer: true },

  /* ── adaptations and remakes ── */
  { statement: "Maqbool, Omkara and Haider are all adapted from Shakespeare.", answer: true, note: "Macbeth, Othello and Hamlet." },
  { statement: "Haider transplants Hamlet to Kashmir.", answer: true },
  { statement: "Omkara is an adaptation of Macbeth.", answer: false, note: "It is Othello; Maqbool is Macbeth." },
  { statement: "3 Idiots is loosely based on a Chetan Bhagat novel.", answer: true, note: "Five Point Someone." },
  { statement: "Kai Po Che! is adapted from The 3 Mistakes of My Life.", answer: true },
  { statement: "Ghajini was a remake of a Tamil film by the same director.", answer: true },
  { statement: "Drishyam (2015) began life as a Malayalam film.", answer: true },
  { statement: "Kabir Singh is a remake of a Telugu film.", answer: true, note: "Arjun Reddy." },
  { statement: "Wanted (2009) was a remake of a Telugu film.", answer: true, note: "Pokiri." },
  { statement: "Singham was an original story with no earlier version.", answer: false, note: "It remade a Tamil film of the same name." },
  { statement: "Dev.D is a modern retelling of Devdas.", answer: true },
  { statement: "Padmaavat draws on a sixteenth-century poem.", answer: true, note: "Malik Muhammad Jayasi's Padmavat." },
  { statement: "Stree grew out of an urban legend.", answer: true },
  { statement: "Baahubali is a Hindi-language film.", answer: false, note: "It was made in Telugu and dubbed into Hindi." },
  { statement: "Sacred Games is a feature film.", answer: false, note: "It is a streaming series." },

  /* ── the films themselves ── */
  { statement: "Chak De! India follows a women's hockey team.", answer: true },
  { statement: "Sultan is about a boxer.", answer: false, note: "Salman Khan plays a wrestler." },
  { statement: "Mary Kom is about a boxer.", answer: true },
  { statement: "Milkha Singh won an Olympic medal, as shown in Bhaag Milkha Bhaag.", answer: false, note: "He finished fourth at Rome in 1960." },
  { statement: "Dangal is about a father coaching his daughters as wrestlers.", answer: true },
  { statement: "Iqbal's young cricketer cannot hear or speak.", answer: true },
  { statement: "In Andhadhun the pianist is blind from the first scene.", answer: false, note: "He is pretending, which is the whole engine of the plot." },
  { statement: "Kahaani is set in Kolkata during Durga Puja.", answer: true },
  { statement: "Barfi!'s lead can neither hear nor speak.", answer: true },
  { statement: "Black's Michelle McNally is deaf and blind.", answer: true },
  { statement: "Taare Zameen Par is about a child with dyslexia.", answer: true },
  { statement: "In Paa, Amitabh Bachchan plays Abhishek Bachchan's son.", answer: true },
  { statement: "My Name Is Khan's Rizwan has Asperger's syndrome.", answer: true },
  { statement: "Queen's Rani goes on her honeymoon alone.", answer: true },
  { statement: "English Vinglish is about a woman learning French.", answer: false, note: "Shashi learns English, in New York." },
  { statement: "Piku is a road trip from Delhi to Kolkata.", answer: true },
  { statement: "The Lunchbox turns on a delivery going to the wrong desk.", answer: true },
  { statement: "Zindagi Na Milegi Dobara was shot largely in Spain.", answer: true },
  { statement: "Dil Chahta Hai sends its friends to Goa.", answer: true },
  { statement: "Gully Boy is set in Dharavi.", answer: true },
  { statement: "Uri: The Surgical Strike dramatises events of 2016.", answer: true },
  { statement: "Airlift is about the evacuation of Indians from Kuwait in 1990.", answer: true },
  { statement: "Neerja is about a hijacking in 1986.", answer: true },
  { statement: "Newton is set on polling day in a forest district.", answer: true },
  { statement: "Peepli Live is a satire on television news.", answer: true },
  { statement: "Vicky Donor is a comedy about sperm donation.", answer: true },
  { statement: "Badhaai Ho turns on a middle-aged couple expecting a baby.", answer: true },
  { statement: "Gangs of Wasseypur was released in two parts.", answer: true },
  { statement: "Rang De Basanti's students are drawn into re-enacting the 1920s revolutionaries.", answer: true },
  { statement: "Swades has Shah Rukh Khan playing a NASA engineer.", answer: true },
  { statement: "Veer-Zaara was directed by Aditya Chopra.", answer: false, note: "His father Yash Chopra directed it." },

  /* ── people ── */
  { statement: "Amitabh Bachchan began hosting Kaun Banega Crorepati in 2000.", answer: true },
  { statement: "Aamir Khan hosted the television series Satyamev Jayate.", answer: true },
  { statement: "Shah Rukh Khan is a co-owner of an IPL team.", answer: true, note: "Kolkata Knight Riders, from 2008." },
  { statement: "Preity Zinta co-owned an IPL team.", answer: true },
  { statement: "Ranveer Singh made his debut in a Yash Raj film.", answer: true, note: "Band Baaja Baaraat." },
  { statement: "Ranbir Kapoor made his debut in Wake Up Sid.", answer: false, note: "Saawariya came first, in 2007." },
  { statement: "Deepika Padukone and Ranbir Kapoor both made their debuts in 2007.", answer: true, note: "Om Shanti Om and Saawariya." },
  { statement: "Rab Ne Bana Di Jodi was Anushka Sharma's first film.", answer: true },
  { statement: "Alia Bhatt is Mahesh Bhatt's daughter.", answer: true },
  { statement: "Sridevi's return to Hindi film after a long break was English Vinglish.", answer: true },
  { statement: "Irrfan Khan appeared in Slumdog Millionaire.", answer: true },
  { statement: "Anil Kapoor played the quiz show host in Slumdog Millionaire.", answer: true },
  { statement: "Nawazuddin Siddiqui appears in both Gangs of Wasseypur and Kahaani.", answer: true },
  { statement: "Irrfan Khan won a National Award for Paan Singh Tomar.", answer: true },
  { statement: "Vidya Balan won a National Award for The Dirty Picture.", answer: true },
  { statement: "Kangana Ranaut won National Awards for both Queen and Tanu Weds Manu Returns.", answer: true },
  { statement: "Ayushmann Khurrana worked in television before he acted in films.", answer: true },
  { statement: "Ranbir Kapoor played Sanjay Dutt in Sanju.", answer: true },
  { statement: "Sushant Singh Rajput played M. S. Dhoni on screen.", answer: true },
  { statement: "Priyanka Chopra played Mary Kom.", answer: true },
  { statement: "Vidya Balan's first Hindi film was Parineeta.", answer: true },
  { statement: "Kangana Ranaut has a co-director credit on Manikarnika.", answer: true },
  { statement: "Karan Johar has acted in a film directed by Anurag Kashyap.", answer: true, note: "He played Kaizad Khambatta in Bombay Velvet." },

  /* ── music ── */
  { statement: "Shankar–Ehsaan–Loy scored Dil Chahta Hai, Kal Ho Naa Ho and Rock On!!.", answer: true },
  { statement: "A. R. Rahman scored Rockstar.", answer: true },
  { statement: "Pritam scored Jab We Met, Barfi! and Yeh Jawaani Hai Deewani.", answer: true },
  { statement: "Amit Trivedi won a National Award for the music of Dev.D.", answer: true },
  { statement: "Sneha Khanwalkar wrote the songs for Gangs of Wasseypur.", answer: true },
  { statement: "Arijit Singh's breakout song was 'Tum Hi Ho' from Aashiqui 2.", answer: true },
  { statement: "Shreya Ghoshal's first Hindi playback songs were for Devdas.", answer: true },
  { statement: "'Munni Badnaam Hui' belongs to Dabangg and 'Sheila Ki Jawani' to Tees Maar Khan.", answer: true },
  { statement: "'Chikni Chameli' is from Ram-Leela.", answer: false, note: "It is from the 2012 Agneepath." },
  { statement: "'Masakali' is from Delhi-6.", answer: true },
  { statement: "'Kajra Re' is from Bunty Aur Babli.", answer: true },
  { statement: "Prasoon Joshi wrote the lyrics for Taare Zameen Par.", answer: true },
  { statement: "Mohit Chauhan sang before he played back, in a band.", answer: true },
];
