import type { TrueFalseItem } from "@curio/core";

/** A statement to accept or reject. `note` explains the trap on a miss. */
export const truefalse: TrueFalseItem[] = [
  { statement: "Sholay was released in 1975.", answer: true },
  { statement: "Gabbar Singh is the hero of Sholay.", answer: false, note: "He is the bandit the village is terrorised by." },
  { statement: "Amitabh Bachchan began as a playback singer.", answer: false, note: "He began as an actor; the singing came much later." },
  { statement: "Amitabh Bachchan's father was the poet Harivansh Rai Bachchan.", answer: true },
  { statement: "Mughal-e-Azam was released entirely in colour in 1960.", answer: false, note: "Only parts were in colour; a fully coloured version came in 2004." },
  { statement: "Lata Mangeshkar and Asha Bhosle were sisters.", answer: true },
  { statement: "Kishore Kumar also directed films.", answer: true },
  { statement: "A. R. Rahman was born in Chennai.", answer: true },
  { statement: "Lagaan won the Academy Award for Best Foreign Language Film.", answer: false, note: "It was nominated and lost to No Man's Land." },
  { statement: "Dilwale Dulhania Le Jayenge was Aditya Chopra's directorial debut.", answer: true },
  { statement: "Shah Rukh Khan started out in television.", answer: true },
  { statement: "Raj Kapoor directed as well as acted.", answer: true },
  { statement: "Mother India was India's first Oscar nomination in the foreign film category.", answer: true },
  { statement: "Guru Dutt directed Pyaasa.", answer: true },
  { statement: "Pakeezah was released before Meena Kumari's death.", answer: true, note: "It opened in February 1972; she died weeks later." },
  { statement: "Satyajit Ray made his films primarily in Hindi.", answer: false, note: "He worked mainly in Bengali." },
  { statement: "Bollywood is the Hindi-language film industry.", answer: true },
  { statement: "Kollywood refers to the Tamil film industry.", answer: true },
  { statement: "Tollywood refers to the Punjabi film industry.", answer: false, note: "It refers to Telugu, and originally to Bengali cinema in Tollygunge." },
  { statement: "Dev Anand starred in Guide.", answer: true },
  { statement: "Nargis starred in Mother India.", answer: true },
  { statement: "Madhubala played Anarkali in Mughal-e-Azam.", answer: true },
  { statement: "Salim-Javed were a writing partnership.", answer: true },
  { statement: "Gulzar has won an Academy Award.", answer: true, note: "For the lyrics of 'Jai Ho'." },
  { statement: "3 Idiots is set at a medical college.", answer: false, note: "It is set at an engineering college." },
  { statement: "Munna Bhai M.B.B.S. was directed by Rajkumar Hirani.", answer: true },
  { statement: "Chak De! India is about cricket.", answer: false, note: "It is about women's field hockey." },
  { statement: "Dangal is based on the Phogat family of wrestlers.", answer: true },
  { statement: "Taare Zameen Par was directed by Aamir Khan.", answer: true },
  { statement: "PK features an alien who cannot speak Hindi at first.", answer: true },
  { statement: "Gangs of Wasseypur was released as a single film.", answer: false, note: "It was released in two parts." },
  { statement: "Vishal Bhardwaj has adapted three Shakespeare plays.", answer: true, note: "Maqbool, Omkara and Haider." },
  { statement: "Haider is set in Kashmir.", answer: true },
  { statement: "Mani Ratnam directed Dil Se..", answer: true },
  { statement: "'Chaiyya Chaiyya' was filmed on a moving train.", answer: true },
  { statement: "Sanjay Leela Bhansali directed Devdas (2002).", answer: true },
  { statement: "Devdas has been filmed only once in India.", answer: false, note: "It has been adapted many times, across several languages." },
  { statement: "Aishwarya Rai won Miss Universe.", answer: false, note: "She won Miss World in 1994." },
  { statement: "Priyanka Chopra won Miss World.", answer: true },
  { statement: "Sridevi worked in Tamil and Telugu films before Hindi ones.", answer: true },
  { statement: "Madhuri Dixit trained in Kathak.", answer: true },
  { statement: "Hrithik Roshan's father directed his debut film.", answer: true, note: "Rakesh Roshan directed Kaho Naa... Pyaar Hai." },
  { statement: "Kajol and Rani Mukerji are cousins.", answer: true },
  { statement: "The Kapoor film family began with Prithviraj Kapoor.", answer: true },
  { statement: "Nutan and Tanuja were sisters.", answer: true },
  { statement: "Irrfan Khan appeared in Slumdog Millionaire.", answer: true },
  { statement: "Om Puri never worked outside India.", answer: false, note: "He appeared in several British and American films." },
  { statement: "Naseeruddin Shah is associated with the parallel cinema movement.", answer: true },
  { statement: "Shyam Benegal directed Ankur.", answer: true },
  { statement: "Smita Patil and Shabana Azmi were both parallel-cinema regulars.", answer: true },
  { statement: "The Filmfare Award trophy is called the Black Lady.", answer: true },
  { statement: "The National Film Awards are given by the Indian government.", answer: true },
  { statement: "Hindi films must legally contain songs.", answer: false, note: "There is no such rule; plenty have none." },
  { statement: "A 'masala' film mixes several genres at once.", answer: true },
  { statement: "'Playback singing' means the actor sings live on set.", answer: false, note: "It means the song is recorded first and mimed to." },
  { statement: "R. D. Burman's father was also a music director.", answer: true, note: "S. D. Burman." },
  { statement: "Mohammed Rafi sang for Shammi Kapoor.", answer: true },
  { statement: "Kishore Kumar sang most of Rajesh Khanna's hits.", answer: true },
  { statement: "Jab We Met was directed by Imtiaz Ali.", answer: true },
  { statement: "Zindagi Na Milegi Dobara is set in Italy.", answer: false, note: "It is set in Spain." },
  { statement: "Queen is largely set in Paris and Amsterdam.", answer: true },
  { statement: "Andhadhun's lead pretends to be deaf.", answer: false, note: "He pretends to be blind." },
  { statement: "Drishyam was originally a Malayalam film.", answer: true },
  { statement: "Kahaani is set in Delhi.", answer: false, note: "It is set in Kolkata." },
  { statement: "Gully Boy is set in Mumbai.", answer: true },
  { statement: "Barfi! has almost no dialogue for its lead.", answer: true },
  { statement: "Bajirao Mastani is a historical drama.", answer: true },
  { statement: "Padmaavat was released without controversy.", answer: false, note: "Its release was heavily protested." },
  { statement: "The Lunchbox turns on a dabbawala delivery error.", answer: true },
  { statement: "Hera Pheri was remade from a Malayalam film.", answer: true },
  { statement: "Andaz Apna Apna was a hit on release.", answer: false, note: "It flopped, and became a cult favourite later." },
  { statement: "Mr. India's villain is called Mogambo.", answer: true },
  { statement: "Don (1978) and Don (2006) share a director.", answer: false, note: "Chandra Barot made the first; Farhan Akhtar the remake." },
  { statement: "Amitabh Bachchan hosted Kaun Banega Crorepati.", answer: true },
  { statement: "Shah Rukh Khan owns an IPL cricket team.", answer: true },
  { statement: "Aamir Khan hosted the television show Satyamev Jayate.", answer: true },
  { statement: "Dharma Productions was founded by Karan Johar.", answer: false, note: "His father Yash Johar founded it." },
  { statement: "Yash Raj Films was founded by Yash Chopra.", answer: true },
  { statement: "Rajshri Productions made Hum Aapke Hain Koun..!", answer: true },
  { statement: "Bhaag Milkha Bhaag is a biopic.", answer: true },
  { statement: "Mary Kom is a boxing biopic.", answer: true },
  { statement: "Neerja is about a flight attendant.", answer: true },
  { statement: "Raazi is based on a novel.", answer: true, note: "Harinder Sikka's Calling Sehmat." },
  { statement: "Swades has Shah Rukh Khan playing a NASA scientist.", answer: true },
  { statement: "Rang De Basanti is set in the 1930s throughout.", answer: false, note: "It is contemporary, with historical re-enactments." },
];
