import type { UnscrambleItem } from "@curio/core";

/** A jumbled word and the hint that unlocks it. */
export const unscramble: UnscrambleItem[] = [
  { word: "RANCHO", hint: "The engineering student who says all is well" },
  { word: "VIRUS", hint: "What the students call their principal in 3 Idiots" },
  { word: "CIRCUIT", hint: "Munna Bhai's right-hand man" },
  { word: "GANDHIGIRI", hint: "The word Lage Raho Munna Bhai gave the language" },
  { word: "CHULBUL", hint: "Dabangg's Pandey, first name" },
  { word: "SINGHAM", hint: "Ajay Devgn's roaring cop" },
  { word: "SIMMBA", hint: "Ranveer Singh's cop, one letter doubled" },
  { word: "JADOO", hint: "The alien who befriends Rohit in Koi... Mil Gaya" },
  { word: "KRRISH", hint: "A black mask, a long coat, and an extra R" },
  { word: "GEET", hint: "The talker on the train from Bhatinda" },
  { word: "JORDAN", hint: "The name Janardhan takes when he becomes a rockstar" },
  { word: "MURAD", hint: "The rapper from Dharavi" },
  { word: "DHARAVI", hint: "Where Gully Boy writes his verses" },
  { word: "WASSEYPUR", hint: "The coal town with the gangs" },
  { word: "CHANDERI", hint: "The town that writes on its walls to keep a ghost out" },
  { word: "BAREILLY", hint: "This town has its own barfi, and a film about it" },
  { word: "KANPUR", hint: "Where Tanu weds Manu" },
  { word: "CHAMPANER", hint: "The village that plays the British at cricket" },
  { word: "CHARANPUR", hint: "The village a NASA engineer comes home to" },
  { word: "SEHMAT", hint: "The bride who was sent across the border to listen" },
  { word: "NEERJA", hint: "The flight attendant on Pan Am 73" },
  { word: "MILKHA", hint: "Run, said the title, twice" },
  { word: "PHOGAT", hint: "The wrestling family of Dangal" },
  { word: "DANGAL", hint: "A wrestling bout in the mud" },
  { word: "SULTAN", hint: "Salman Khan's wrestler from Haryana" },
  { word: "BAJIRAO", hint: "The Peshwa with two wives and one Bhansali film" },
  { word: "MASTANI", hint: "The warrior he could not give up" },
  { word: "KHILJI", hint: "Ranveer Singh's sultan in Padmaavat" },
  { word: "MAQBOOL", hint: "Macbeth, moved to the Mumbai underworld" },
  { word: "HAIDER", hint: "Hamlet, moved to Kashmir" },
  { word: "LANGDA", hint: "Omkara's Iago, and his limp" },
  { word: "BARFI", hint: "He cannot hear, and Darjeeling loves him anyway" },
  { word: "JHILMIL", hint: "Barfi's companion, played by Priyanka Chopra" },
  { word: "PIKU", hint: "The daughter, the father, and the drive to Kolkata" },
  { word: "SHASHI", hint: "She goes to New York and learns the language" },
  { word: "AKASH", hint: "The pianist who is not as blind as he says" },
  { word: "GHAJINI", hint: "Tattoos, Polaroids, and no short-term memory" },
  { word: "MAGIK", hint: "The band that gets back together in Rock On!!" },
  { word: "TOMATINA", hint: "The Spanish festival the friends end up throwing fruit at" },
  { word: "AMSTERDAM", hint: "Queen's second stop, after Paris" },
  { word: "DABBAWALA", hint: "He delivers your lunch, and almost never to the wrong desk" },
  { word: "TIFFIN", hint: "The stacked tin that carried the letters" },
  { word: "MULTIPLEX", hint: "The screen that changed what a hit had to be" },
  { word: "CRORE", hint: "Ten million, and the unit a hit is counted in" },
  { word: "PLAYBACK", hint: "Recorded first, mimed to later" },
  { word: "FILMFARE", hint: "Its trophy is a Black Lady" },
  { word: "ARIJIT", hint: "The voice of the 2010s love song" },
  { word: "RAHMAN", hint: "Two Academy Awards in one night" },
  { word: "PRITAM", hint: "He scored Jab We Met, Barfi! and Yeh Jawaani Hai Deewani" },
  { word: "SHREYA", hint: "Bhansali cast her for Devdas, and she never stopped" },
  { word: "JOSH", hint: "Uri keeps asking how it is" },
  { word: "SANJU", hint: "Ranbir Kapoor plays this actor's life" },
  { word: "NEWTON", hint: "A polling officer with a borrowed name" },
  { word: "MASAAN", hint: "The burning ground at Banaras, and a film named for it" },
];
