import type { UnscrambleItem } from "@curio/core";

/** A jumbled word and the hint that unlocks it. */
export const unscramble: UnscrambleItem[] = [
  { word: "SHOLAY", hint: "Two friends, one bandit, one water tank" },
  { word: "GABBAR", hint: "He asks how many men there were" },
  { word: "MOGAMBO", hint: "He is pleased" },
  { word: "PATRONAGE", hint: "What a film family gives a newcomer" },
  { word: "PLAYBACK", hint: "Recorded first, mimed to later" },
  { word: "QAWWALI", hint: "Devotional, and sung in call and response" },
  { word: "GHAZAL", hint: "Couplets of longing, often sung" },
  { word: "TABLA", hint: "A pair of drums played with the fingers" },
  { word: "DHOLAK", hint: "The two-headed drum of a wedding song" },
  { word: "SITAR", hint: "Long-necked, many-stringed, unmistakably Indian" },
  { word: "MASALA", hint: "A film that is every genre at once" },
  { word: "FILMFARE", hint: "Its trophy is a Black Lady" },
  { word: "BOLLYWOOD", hint: "The Hindi industry's nickname" },
  { word: "DABBAWALA", hint: "He delivers your lunch and never loses it" },
  { word: "BAARAT", hint: "The groom's procession" },
  { word: "SANGEET", hint: "The night of songs before the wedding" },
  { word: "MEHNDI", hint: "Patterns drawn on the bride's hands" },
  { word: "CHAWL", hint: "Mumbai tenement, shared verandah" },
  { word: "RICKSHAW", hint: "Three wheels, one fare, no meter" },
  { word: "MONSOON", hint: "The rain a song has been waiting for" },
  { word: "DEVDAS", hint: "He drinks himself towards Paro's door" },
  { word: "PAKEEZAH", hint: "Meena Kumari's last, and her greatest" },
  { word: "ANARKALI", hint: "She dances in a hall of mirrors" },
  { word: "LAGAAN", hint: "The tax the village played cricket to escape" },
  { word: "DANGAL", hint: "A wrestling bout, and a father's obsession" },
  { word: "NAMASTE", hint: "Palms together, and hello" },
  { word: "RANGOLI", hint: "Coloured powder at a doorstep" },
  { word: "PARATHA", hint: "Flatbread, stuffed and fried" },
  { word: "BIRYANI", hint: "Rice, spice, and an argument about which city does it best" },
  { word: "CHAIWALA", hint: "He pours from a great height" },
  { word: "SANSKAAR", hint: "What every Barjatya family has plenty of" },
  { word: "SHEHNAI", hint: "Its sound means a wedding is starting" },
  { word: "BINDAAS", hint: "Carefree, and slightly reckless" },
  { word: "JUGAAD", hint: "A fix that shouldn't work but does" },
  { word: "TAMASHA", hint: "A spectacle, and an Imtiaz Ali title" },
  { word: "SHAHENSHAH", hint: "Emperor, and a nickname for Amitabh" },
  { word: "NIGHTINGALE", hint: "What they called Lata Mangeshkar" },
  { word: "PANCHAM", hint: "R. D. Burman, to his friends" },
  { word: "ANTAKSHARI", hint: "The song game that never ends on a long journey" },
  { word: "INTERVAL", hint: "Halfway, and time for a samosa" },
];
