import type { CategorizeItem } from "@curio/core";

/** Every sorting item, tagged with the set whose buckets it belongs to. */
export const categorize: CategorizeItem[] = [
  { set: "houses", label: "Luna Lovegood", category: "ravenclaw" },
  { set: "houses", label: "Cedric Diggory", category: "hufflepuff" },
  { set: "houses", label: "Draco Malfoy", category: "slytherin" },
  { set: "houses", label: "Neville Longbottom", category: "gryffindor" },
  { set: "houses", label: "Cho Chang", category: "ravenclaw" },
  { set: "houses", label: "Nymphadora Tonks", category: "hufflepuff" },
  { set: "houses", label: "Bellatrix Lestrange", category: "slytherin" },
  { set: "houses", label: "Ginny Weasley", category: "gryffindor" },
  { set: "houses", label: "Filius Flitwick", category: "ravenclaw" },
  { set: "houses", label: "Pomona Sprout", category: "hufflepuff" },
  { set: "houses", label: "Horace Slughorn", category: "slytherin" },
  { set: "houses", label: "Minerva McGonagall", category: "gryffindor" },
  { set: "houses", label: "Gilderoy Lockhart", category: "ravenclaw" },
  { set: "houses", label: "Newt Scamander", category: "hufflepuff" },
  { set: "houses", label: "Regulus Black", category: "slytherin" },
  { set: "houses", label: "Sirius Black", category: "gryffindor" },
  { set: "houses", label: "Padma Patil", category: "ravenclaw" },
  { set: "houses", label: "Justin Finch-Fletchley", category: "hufflepuff" },
  { set: "houses", label: "Dolores Umbridge", category: "slytherin" },
  { set: "houses", label: "Seamus Finnigan", category: "gryffindor" },
  { set: "houses", label: "Moaning Myrtle", category: "ravenclaw" },
  { set: "houses", label: "Susan Bones", category: "hufflepuff" },
  { set: "houses", label: "Marcus Flint", category: "slytherin" },
  { set: "houses", label: "Colin Creevey", category: "gryffindor" },


  /* ── beasts, beings, spirits and plants ── */

  { set: "creatures", label: "Hippogriff", category: "beast" },
  { set: "creatures", label: "Thestral", category: "beast" },
  { set: "creatures", label: "Niffler", category: "beast" },
  { set: "creatures", label: "Acromantula", category: "beast" },
  { set: "creatures", label: "Basilisk", category: "beast" },
  { set: "creatures", label: "Hungarian Horntail", category: "beast" },
  { set: "creatures", label: "Grindylow", category: "beast" },
  { set: "creatures", label: "Kneazle", category: "beast" },
  { set: "creatures", label: "House-elf", category: "being" },
  { set: "creatures", label: "Goblin", category: "being" },
  { set: "creatures", label: "Centaur", category: "being" },
  { set: "creatures", label: "Merperson", category: "being" },
  { set: "creatures", label: "Veela", category: "being" },
  { set: "creatures", label: "Giant", category: "being" },
  { set: "creatures", label: "Boggart", category: "spirit" },
  { set: "creatures", label: "Dementor", category: "spirit" },
  { set: "creatures", label: "Poltergeist", category: "spirit" },
  { set: "creatures", label: "Inferius", category: "spirit" },
  { set: "creatures", label: "Mandrake", category: "plant" },
  { set: "creatures", label: "Devil's Snare", category: "plant" },
  { set: "creatures", label: "Whomping Willow", category: "plant" },
  { set: "creatures", label: "Venomous Tentacula", category: "plant" },
  { set: "creatures", label: "Gillyweed", category: "plant" },

  /* ── spell, potion, or object ── */

  { set: "magic", label: "Expelliarmus", category: "spell" },
  { set: "magic", label: "Riddikulus", category: "spell" },
  { set: "magic", label: "Expecto Patronum", category: "spell" },
  { set: "magic", label: "Alohomora", category: "spell" },
  { set: "magic", label: "Obliviate", category: "spell" },
  { set: "magic", label: "Sectumsempra", category: "spell" },
  { set: "magic", label: "Morsmordre", category: "spell" },
  { set: "magic", label: "Felix Felicis", category: "potion" },
  { set: "magic", label: "Polyjuice Potion", category: "potion" },
  { set: "magic", label: "Veritaserum", category: "potion" },
  { set: "magic", label: "Amortentia", category: "potion" },
  { set: "magic", label: "Draught of Living Death", category: "potion" },
  { set: "magic", label: "Skele-Gro", category: "potion" },
  { set: "magic", label: "Time-Turner", category: "object" },
  { set: "magic", label: "Deluminator", category: "object" },
  { set: "magic", label: "Remembrall", category: "object" },
  { set: "magic", label: "Sneakoscope", category: "object" },
  { set: "magic", label: "Marauder's Map", category: "object" },
  { set: "magic", label: "Pensieve", category: "object" },
  { set: "magic", label: "Portkey", category: "object" },

  /* ── where in the world ── */

  { set: "places", label: "The Room of Requirement", category: "hogwarts" },
  { set: "places", label: "The Chamber of Secrets", category: "hogwarts" },
  { set: "places", label: "The Forbidden Forest", category: "hogwarts" },
  { set: "places", label: "The Owlery", category: "hogwarts" },
  { set: "places", label: "The Great Hall", category: "hogwarts" },
  { set: "places", label: "The Prefects' Bathroom", category: "hogwarts" },
  { set: "places", label: "Diagon Alley", category: "london" },
  { set: "places", label: "The Leaky Cauldron", category: "london" },
  { set: "places", label: "Knockturn Alley", category: "london" },
  { set: "places", label: "Grimmauld Place", category: "london" },
  { set: "places", label: "St Mungo's", category: "london" },
  { set: "places", label: "Platform Nine and Three-Quarters", category: "london" },
  { set: "places", label: "Azkaban", category: "elsewhere" },
  { set: "places", label: "Hogsmeade", category: "elsewhere" },
  { set: "places", label: "Godric's Hollow", category: "elsewhere" },
  { set: "places", label: "The Burrow", category: "elsewhere" },
  { set: "places", label: "Shell Cottage", category: "elsewhere" },
  { set: "places", label: "Malfoy Manor", category: "elsewhere" },
];
