import type { ChoiceItem } from "@candlelight/core";

/** Straight trivia: four options, one truth. */
export const choice: ChoiceItem[] = [
  { prompt: "What form does Harry's Patronus take?", options: ["A stag", "A doe", "An otter", "A jack russell terrier"], answer: 0 },
  { prompt: "What is the core of Harry's first wand?", options: ["Dragon heartstring", "Unicorn hair", "Phoenix feather", "Thestral tail hair"], answer: 2 },
  { prompt: "What is Voldemort's birth name?", options: ["Tom Marvolo Riddle", "Marvolo Gaunt", "Thomas Slytherin", "Tom Gaunt Riddle"], answer: 0 },
  { prompt: "Which potion grants the drinker good luck?", options: ["Amortentia", "Veritaserum", "Felix Felicis", "Draught of Peace"], answer: 2 },
  { prompt: "What kind of creature is Aragog?", options: ["An Acromantula", "A Nundu", "A Quintaped", "A Doxy"], answer: 0 },
  { prompt: "How many points is the Golden Snitch worth?", options: ["50", "100", "150", "200"], answer: 2 },
  { prompt: "How many players are on a Quidditch team?", options: ["Five", "Six", "Seven", "Nine"], answer: 2 },
  { prompt: "Which dragon did Harry face in the first Triwizard task?", options: ["Chinese Fireball", "Hungarian Horntail", "Swedish Short-Snout", "Welsh Green"], answer: 1 },
  { prompt: "Who killed Bellatrix Lestrange?", options: ["Neville Longbottom", "Molly Weasley", "Ginny Weasley", "Minerva McGonagall"], answer: 1 },
  { prompt: "What does S.P.E.W. stand for?", options: ["Society for the Protection of Enchanted Wildlife", "Society for the Promotion of Elfish Welfare", "Students Protesting Elf Work", "Society for Practical Elfish Wages"], answer: 1 },
  { prompt: "Which object did Dumbledore leave Harry in his will?", options: ["The Sword of Gryffindor", "A Deluminator", "The first Snitch he ever caught", "A copy of The Tales of Beedle the Bard"], answer: 2 },
  { prompt: "What animal represents Hufflepuff house?", options: ["A badger", "A raven", "An otter", "A boar"], answer: 0 },
  { prompt: "Which teacher turns out to be the Half-Blood Prince?", options: ["Horace Slughorn", "Remus Lupin", "Severus Snape", "Filius Flitwick"], answer: 2 },
  { prompt: "What destroyed the Basilisk in the Chamber of Secrets?", options: ["The Sword of Gryffindor", "A rooster's crow", "Fawkes' tears", "A Killing Curse"], answer: 0 },
  { prompt: "Where do the Weasleys live?", options: ["Shell Cottage", "Spinner's End", "The Burrow", "Godric's Hollow"], answer: 2 },
  { prompt: "Which platform does the Hogwarts Express leave from?", options: ["Nine and a half", "Nine and three-quarters", "Ten and a quarter", "Seven and three-quarters"], answer: 1 },
  { prompt: "Who teaches Herbology at Hogwarts?", options: ["Pomona Sprout", "Charity Burbage", "Wilhelmina Grubbly-Plank", "Septima Vector"], answer: 0 },
  { prompt: "How many Horcruxes did Voldemort deliberately create?", options: ["Five", "Six", "Seven", "Eight"], answer: 1 },
  { prompt: "What is the wizarding newspaper of Britain called?", options: ["The Quibbler", "Witch Weekly", "The Daily Prophet", "The Evening Seer"], answer: 2 },
  { prompt: "Which house ghost is the Grey Lady?", options: ["Gryffindor", "Ravenclaw", "Hufflepuff", "Slytherin"], answer: 1 },
  { prompt: "What is the highest-value wizarding coin?", options: ["Knut", "Sickle", "Galleon", "Sovereign"], answer: 2 },
  { prompt: "What kind of creature is Dobby?", options: ["A goblin", "A house-elf", "A gnome", "A leprechaun"], answer: 1 },
  { prompt: "Which two schools competed against Hogwarts in the Triwizard Tournament?", options: ["Ilvermorny and Mahoutokoro", "Beauxbatons and Durmstrang", "Castelobruxo and Uagadou", "Durmstrang and Ilvermorny"], answer: 1 },
  { prompt: "What does the Marauder's Map reveal?", options: ["Hidden passages only", "Everyone's location inside Hogwarts", "Dark objects nearby", "The future"], answer: 1 },
  { prompt: "Which Marauder went by the nickname Padfoot?", options: ["Remus Lupin", "James Potter", "Sirius Black", "Peter Pettigrew"], answer: 2 },
  { prompt: "What subject did Snape teach for most of Harry's school years?", options: ["Potions", "Defence Against the Dark Arts", "Transfiguration", "Charms"], answer: 0 },
  { prompt: "What is Hagrid's three-headed dog called?", options: ["Fang", "Fluffy", "Norbert", "Cerberus"], answer: 1 },
  { prompt: "Which creature can only be seen by someone who has witnessed death?", options: ["A Hippogriff", "A Thestral", "A Nifflers", "A Boggart"], answer: 1 },
  { prompt: "What does a Boggart become when it is defeated?", options: ["Invisible", "Something laughable", "A cloud of smoke", "A mirror"], answer: 1 },
  { prompt: "Which Weasley brother works with dragons in Romania?", options: ["Bill", "Charlie", "Percy", "Fred"], answer: 1 },
  { prompt: "What was Tom Riddle's diary a fragment of?", options: ["A curse", "A Horcrux", "A Pensieve", "A Portkey"], answer: 1 },
  { prompt: "Who was the Hogwarts caretaker?", options: ["Argus Filch", "Rubeus Hagrid", "Aberforth Dumbledore", "Amos Diggory"], answer: 0 },
  { prompt: "What is Hermione's cat named?", options: ["Crookshanks", "Mrs Norris", "Scabbers", "Pigwidgeon"], answer: 0 },
  { prompt: "Which shop sells wands in Diagon Alley?", options: ["Flourish and Blotts", "Ollivanders", "Borgin and Burkes", "Madam Malkin's"], answer: 1 },
  { prompt: "What is the name of the wizarding prison?", options: ["Nurmengard", "Azkaban", "Gringotts", "Grimmauld"], answer: 1 },
  { prompt: "Which spell is known as the Killing Curse?", options: ["Crucio", "Imperio", "Avada Kedavra", "Morsmordre"], answer: 2 },
  { prompt: "Who founded Dumbledore's Army?", options: ["Harry, Ron and Hermione", "Neville and Luna", "The Order of the Phoenix", "Fred and George"], answer: 0 },
  { prompt: "What was Lupin's condition?", options: ["He was a werewolf", "He was a vampire", "He was an Animagus", "He was a Squib"], answer: 0 },
  { prompt: "What does a Pensieve store?", options: ["Potions", "Memories", "Prophecies", "Souls"], answer: 1 },
  { prompt: "Who won the Triwizard Tournament alongside Harry?", options: ["Viktor Krum", "Fleur Delacour", "Cedric Diggory", "Nobody"], answer: 2 },
  { prompt: "Which magical creature guards the deepest Gringotts vaults?", options: ["A dragon", "A Sphinx", "A Chimaera", "Goblin warriors"], answer: 0 },
  { prompt: "What is Neville's toad called?", options: ["Trevor", "Errol", "Arnold", "Nagini"], answer: 0 },
  { prompt: "Which room appears only when someone truly needs it?", options: ["The Chamber of Secrets", "The Room of Requirement", "The Restricted Section", "The Great Hall"], answer: 1 },
  { prompt: "What is the name of the pub that hides the entrance to Diagon Alley?", options: ["The Three Broomsticks", "The Hog's Head", "The Leaky Cauldron", "The Green Dragon"], answer: 2 },
];
