import type { ChoiceItem } from "@curio/core";

/**
 * Straight trivia: four options, one truth.
 *
 * Written to span the room. A pack where every question is "what animal is
 * Hufflepuff" is a pack the person who has read the books six times has no
 * reason to play, so the bank runs from things a filmgoer knows to things
 * that need the text — vault numbers, the Gaunts, who actually owned the
 * Elder Wand and when.
 *
 * Book canon decides anything the films changed.
 */
export const choice: ChoiceItem[] = [
  /* ── the things everyone knows ── */
  { prompt: "What form does Harry's Patronus take?", options: ["A stag", "A doe", "An otter", "A jack russell terrier"], answer: 0 },
  { prompt: "What is the core of Harry's first wand?", options: ["Dragon heartstring", "Unicorn hair", "Phoenix feather", "Thestral tail hair"], answer: 2 },
  { prompt: "What is Voldemort's birth name?", options: ["Tom Marvolo Riddle", "Marvolo Gaunt", "Thomas Slytherin", "Tom Gaunt Riddle"], answer: 0 },
  { prompt: "Which potion grants the drinker good luck?", options: ["Amortentia", "Veritaserum", "Felix Felicis", "Draught of Peace"], answer: 2 },
  { prompt: "What kind of creature is Aragog?", options: ["An Acromantula", "A Nundu", "A Quintaped", "A Doxy"], answer: 0 },
  { prompt: "How many points is the Golden Snitch worth?", options: ["50", "100", "150", "200"], answer: 2 },
  { prompt: "How many players are on a Quidditch team?", options: ["Five", "Six", "Seven", "Nine"], answer: 2 },
  { prompt: "Which dragon did Harry face in the first Triwizard task?", options: ["Chinese Fireball", "Hungarian Horntail", "Swedish Short-Snout", "Welsh Green"], answer: 1 },
  { prompt: "Who killed Bellatrix Lestrange?", options: ["Neville Longbottom", "Molly Weasley", "Ginny Weasley", "Minerva McGonagall"], answer: 1 },
  { prompt: "What does S.P.E.W. stand for?", options: ["Society for the Protection of Enchanted Wildlife", "Society for the Promotion of Elfish Welfare", "Students Protesting Elf Work", "Society for Practical Elfish Wages"], answer: 1 },
  { prompt: "Which object did Dumbledore leave Harry in his will?", options: ["The Sword of Gryffindor", "A Deluminator", "The first Snitch he ever caught", "A copy of The Tales of Beedle the Bard"], answer: 2 },
  { prompt: "What animal represents Hufflepuff house?", options: ["A badger", "A raven", "An otter", "A boar"], answer: 0 },
  { prompt: "Which teacher turns out to be the Half-Blood Prince?", options: ["Horace Slughorn", "Remus Lupin", "Severus Snape", "Filius Flitwick"], answer: 2 },
  { prompt: "What destroyed the Basilisk in the Chamber of Secrets?", options: ["The Sword of Gryffindor", "A rooster's crow", "Fawkes' tears", "A Killing Curse"], answer: 0 },
  { prompt: "Where do the Weasleys live?", options: ["Shell Cottage", "Spinner's End", "The Burrow", "Godric's Hollow"], answer: 2 },
  { prompt: "Which platform does the Hogwarts Express leave from?", options: ["Nine and a half", "Nine and three-quarters", "Ten and a quarter", "Seven and three-quarters"], answer: 1 },
  { prompt: "Who teaches Herbology at Hogwarts?", options: ["Pomona Sprout", "Charity Burbage", "Wilhelmina Grubbly-Plank", "Septima Vector"], answer: 0 },
  { prompt: "How many Horcruxes did Voldemort deliberately create?", options: ["Five", "Six", "Seven", "Eight"], answer: 1 },
  { prompt: "What is the wizarding newspaper of Britain called?", options: ["The Quibbler", "Witch Weekly", "The Daily Prophet", "The Evening Seer"], answer: 2 },
  { prompt: "Which house ghost is the Grey Lady?", options: ["Gryffindor", "Ravenclaw", "Hufflepuff", "Slytherin"], answer: 1 },
  { prompt: "What is the highest-value wizarding coin?", options: ["Knut", "Sickle", "Galleon", "Sovereign"], answer: 2 },
  { prompt: "What kind of creature is Dobby?", options: ["A goblin", "A house-elf", "A gnome", "A leprechaun"], answer: 1 },
  { prompt: "Which two schools competed against Hogwarts in the Triwizard Tournament?", options: ["Ilvermorny and Mahoutokoro", "Beauxbatons and Durmstrang", "Castelobruxo and Uagadou", "Durmstrang and Ilvermorny"], answer: 1 },
  { prompt: "What does the Marauder's Map reveal?", options: ["Hidden passages only", "Everyone's location inside Hogwarts", "Dark objects nearby", "The future"], answer: 1 },
  { prompt: "Which Marauder went by the nickname Padfoot?", options: ["Remus Lupin", "James Potter", "Sirius Black", "Peter Pettigrew"], answer: 2 },
  { prompt: "What subject did Snape teach for most of Harry's school years?", options: ["Potions", "Defence Against the Dark Arts", "Transfiguration", "Charms"], answer: 0 },
  { prompt: "What is Hagrid's three-headed dog called?", options: ["Fluffy", "Fang", "Norbert", "Ripper"], answer: 0 },
  { prompt: "Which creature can only be seen by someone who has witnessed death?", options: ["A Thestral", "A Hippogriff", "A Demiguise", "A Kelpie"], answer: 0 },
  { prompt: "Which Weasley brother works with dragons in Romania?", options: ["Bill", "Charlie", "Percy", "Fred"], answer: 1 },
  { prompt: "What was Tom Riddle's diary a fragment of?", options: ["His memory", "His soul", "His magic", "His body"], answer: 1 },
  { prompt: "Who was the Hogwarts caretaker?", options: ["Argus Filch", "Rubeus Hagrid", "Ernie Prang", "Stan Shunpike"], answer: 0 },
  { prompt: "What is Hermione's cat named?", options: ["Crookshanks", "Mrs Norris", "Pigwidgeon", "Trevor"], answer: 0 },
  { prompt: "Which shop sells wands in Diagon Alley?", options: ["Ollivanders", "Flourish and Blotts", "Madam Malkin's", "Gringotts"], answer: 0 },
  { prompt: "What is the name of the wizarding prison?", options: ["Nurmengard", "Azkaban", "Gringotts", "Grimmauld"], answer: 1 },
  { prompt: "Which spell is known as the Killing Curse?", options: ["Crucio", "Imperio", "Avada Kedavra", "Morsmordre"], answer: 2 },
  { prompt: "Who founded Dumbledore's Army?", options: ["Harry, Ron and Hermione", "Dumbledore himself", "Neville and Luna", "The Order of the Phoenix"], answer: 0 },
  { prompt: "What was Lupin's condition?", options: ["He was a werewolf", "He was a vampire", "He was a Squib", "He was an Inferius"], answer: 0 },
  { prompt: "What does a Pensieve store?", options: ["Potions", "Memories", "Prophecies", "Souls"], answer: 1 },
  { prompt: "Who won the Triwizard Tournament alongside Harry?", options: ["Cedric Diggory", "Viktor Krum", "Fleur Delacour", "Nobody"], answer: 0 },
  { prompt: "Which magical creature guards the deepest Gringotts vaults?", options: ["A dragon", "A basilisk", "A chimaera", "A sphinx"], answer: 0 },
  { prompt: "What is Neville's toad called?", options: ["Trevor", "Errol", "Scabbers", "Nagini"], answer: 0 },
  { prompt: "Which room appears only when someone truly needs it?", options: ["The Room of Requirement", "The Chamber of Secrets", "The Trophy Room", "The Great Hall"], answer: 0 },
  { prompt: "What is the name of the pub that hides the entrance to Diagon Alley?", options: ["The Leaky Cauldron", "The Three Broomsticks", "The Hog's Head", "The Hanged Man"], answer: 0 },

  /* ── creatures ── */
  { prompt: "What does a Boggart become?", options: ["Your worst fear", "Your happiest memory", "A mirror", "A shadow"], answer: 0 },
  { prompt: "Which spell defeats a Boggart?", options: ["Riddikulus", "Expecto Patronum", "Finite", "Reducto"], answer: 0 },
  { prompt: "Why is a Boggart easier to face in a crowd?", options: ["It weakens with distance", "It cannot decide what shape to take", "It splits into pieces", "Laughter is louder"], answer: 1 },
  { prompt: "What kills a Basilisk?", options: ["A rooster's crow", "Sunlight", "Silver", "Salt water"], answer: 0 },
  { prompt: "What is a Niffler drawn to?", options: ["Anything shiny", "Fresh blood", "Loud noise", "Magic itself"], answer: 0 },
  { prompt: "How should you greet a Hippogriff?", options: ["Bow, and wait", "Offer food", "Look away", "Speak first"], answer: 0 },
  { prompt: "What repels a Dementor?", options: ["A Patronus", "Fire", "Iron", "Silence"], answer: 0 },
  { prompt: "What is a Grindylow?", options: ["A water demon", "A tree spirit", "A small dragon", "A kind of owl"], answer: 0 },
  { prompt: "What calmed Fluffy?", options: ["Music", "Meat", "Darkness", "A spell"], answer: 0 },
  { prompt: "What does a mature Mandrake's cry do?", options: ["Kills anyone who hears it", "Puts you to sleep", "Blinds you", "Summons more Mandrakes"], answer: 0 },
  { prompt: "Where do the Hogwarts merpeople live?", options: ["The Black Lake", "The Forbidden Forest", "The castle moat", "The Great Lake at Beauxbatons"], answer: 0 },
  { prompt: "What kind of creature is a Kneazle?", options: ["A cat-like creature", "A small dragon", "A rodent", "A bird"], answer: 0 },
  { prompt: "Who raised Aragog?", options: ["Rubeus Hagrid", "Newt Scamander", "Silvanus Kettleburn", "Tom Riddle"], answer: 0 },
  { prompt: "What is unusual about house-elf magic at Hogwarts?", options: ["They can Apparate where wizards cannot", "It only works at night", "It needs a wand", "It fails indoors"], answer: 0 },
  { prompt: "What did Hagrid breed for Care of Magical Creatures?", options: ["Blast-Ended Skrewts", "Nifflers", "Bowtruckles", "Puffskeins"], answer: 0 },
  { prompt: "What is a Boggart's true form?", options: ["Nobody knows", "A shapeless mist", "A small black dog", "A mirror image"], answer: 0 },
  { prompt: "Which creature's gaze petrifies rather than kills when seen indirectly?", options: ["A Basilisk", "A Gorgon", "A Chimaera", "A Sphinx"], answer: 0, note: "Everyone petrified in the Chamber saw it through water, a camera or a reflection." },
  { prompt: "What is a Red Cap?", options: ["A creature that lurks where blood has been spilt", "A garden gnome", "A kind of hat that shouts", "A Quidditch official"], answer: 0 },
  { prompt: "What does a Hinkypunk do?", options: ["Lures travellers into bogs with a light", "Steals shiny things", "Eats memories", "Guards treasure"], answer: 0 },
  { prompt: "What are Cornish pixies?", options: ["Small blue troublemakers", "Tiny green healers", "Winged horses", "A kind of house-elf"], answer: 0 },
  { prompt: "What did Fawkes do when he grew too old?", options: ["Burst into flame and was reborn", "Flew away for a year", "Slept for a decade", "Shed all his feathers"], answer: 0 },
  { prompt: "How do you kill a werewolf in wizarding lore?", options: ["Silver", "Fire", "A Killing Curse", "Wolfsbane"], answer: 0 },
  { prompt: "What does Wolfsbane Potion do?", options: ["Keeps a transformed werewolf's mind", "Prevents the transformation", "Cures lycanthropy", "Makes the wolf sleep"], answer: 0 },
  { prompt: "What is Buckbeak renamed after his escape?", options: ["Witherwings", "Stormwing", "Greyfeather", "Highwind"], answer: 0 },
  { prompt: "What is unusual about a unicorn's blood?", options: ["It keeps you alive at a terrible price", "It grants invisibility", "It burns anything it touches", "It cannot be seen"], answer: 0 },
  { prompt: "What did Aragog's colony do to Ron and Harry?", options: ["Tried to eat them", "Guided them home", "Ignored them entirely", "Gave them a warning"], answer: 0 },
  { prompt: "What is a Bowtruckle's job?", options: ["Guarding wand-wood trees", "Delivering post", "Finding truffles", "Cleaning cauldrons"], answer: 0 },

  /* ── spells and potions ── */
  { prompt: "Which spell lights the tip of a wand?", options: ["Lumos", "Incendio", "Aguamenti", "Nox"], answer: 0 },
  { prompt: "Which spell summons an object to you?", options: ["Accio", "Evanesco", "Reparo", "Engorgio"], answer: 0 },
  { prompt: "What does Levicorpus do?", options: ["Hangs the target upside down by an ankle", "Freezes the body", "Erases memory", "Ends a spell"], answer: 0 },
  { prompt: "Which spell conjures the Dark Mark?", options: ["Morsmordre", "Serpensortia", "Sectumsempra", "Densaugeo"], answer: 0 },
  { prompt: "What does the Fidelius Charm do?", options: ["Hides a secret inside one person", "Makes a place unplottable", "Hides an object in plain sight", "Locks a door for good"], answer: 0 },
  { prompt: "What does Priori Incantatem reveal?", options: ["A wand's last spells", "A person's last thought", "A hidden room", "A false name"], answer: 0 },
  { prompt: "Which of these is not an Unforgivable Curse?", options: ["Avada Kedavra", "Crucio", "Imperio", "Sectumsempra"], answer: 3 },
  { prompt: "What is Occlumency?", options: ["Sealing the mind against intrusion", "Reading another mind", "Erasing a memory", "Speaking to snakes"], answer: 0 },
  { prompt: "What does the Protean Charm do?", options: ["Links objects so a change to one changes all", "Turns an object inside out", "Makes something unbreakable", "Shrinks a thing to fit a pocket"], answer: 0, note: "It is how Hermione made the DA's coins — and it is N.E.W.T. standard." },
  { prompt: "Which potion turns you into someone else for an hour?", options: ["Polyjuice Potion", "Amortentia", "Draught of Living Death", "Skele-Gro"], answer: 0 },
  { prompt: "What does Amortentia smell like?", options: ["Whatever attracts the person smelling it", "Burnt sugar", "Nothing at all", "The same to everyone"], answer: 0 },
  { prompt: "What does Skele-Gro do?", options: ["Regrows bones", "Heals cuts", "Cures poison", "Stops bleeding"], answer: 0 },
  { prompt: "What is the antidote to most common poisons in Snape's first lesson?", options: ["A bezoar", "Mandrake root", "Powdered moonstone", "Essence of dittany"], answer: 0 },
  { prompt: "What is Essence of Dittany used for?", options: ["Healing wounds", "Curing werewolf bites", "Growing hair", "Sharpening the mind"], answer: 0 },
  { prompt: "What does a Fidelius-protected place look like to an outsider?", options: ["It is simply not there", "It looks derelict", "It looks like a field", "It appears to be somewhere else"], answer: 0 },
  { prompt: "Which spell did Harry use, not knowing what it did, against Draco?", options: ["Sectumsempra", "Levicorpus", "Confringo", "Densaugeo"], answer: 0 },
  { prompt: "What does Fiendfyre do?", options: ["Burns with cursed fire that takes living shapes", "Freezes what it touches", "Burns only wood", "Cannot be put out by water alone"], answer: 0 },
  { prompt: "Which of these can destroy a Horcrux?", options: ["Fiendfyre", "Incendio", "Reducto", "Confringo"], answer: 0 },
  { prompt: "What is the incantation for the Disarming Charm?", options: ["Expelliarmus", "Protego", "Impedimenta", "Stupefy"], answer: 0 },
  { prompt: "What does Stupefy do?", options: ["Stuns the target", "Confuses the target", "Binds the target", "Silences the target"], answer: 0 },
  { prompt: "What is the Draught of Living Death?", options: ["A sleeping potion of enormous power", "A poison with no antidote", "A potion that fakes a heartbeat", "A drink that raises the dead"], answer: 0 },
  { prompt: "What does the Imperius Curse do?", options: ["Puts the victim under the caster's control", "Causes unbearable pain", "Kills instantly", "Erases the victim's name"], answer: 0 },
  { prompt: "Who could throw off the Imperius Curse in Moody's lesson?", options: ["Harry", "Hermione", "Neville", "Ron"], answer: 0 },
  { prompt: "What is Legilimency?", options: ["Reading a mind from the inside", "Sealing the mind", "Speaking without sound", "Seeing the future"], answer: 0 },
  { prompt: "What does Anapneo do?", options: ["Clears a blocked airway", "Slows the heart", "Numbs pain", "Stops bleeding"], answer: 0 },
  { prompt: "What does the Trace do?", options: ["Detects magic done around under-seventeens", "Follows a stolen wand", "Marks a criminal", "Records every spell cast"], answer: 0 },
  { prompt: "Why could Harry not simply Apparate out of trouble at sixteen?", options: ["He had not passed his test", "He had no wand", "Apparition was banned", "He had never been taught"], answer: 0 },
  { prompt: "What are the three D's of Apparition?", options: ["Destination, Determination, Deliberation", "Direction, Distance, Decision", "Desire, Discipline, Delivery", "Distance, Determination, Descent"], answer: 0 },
  { prompt: "What is Splinching?", options: ["Leaving part of yourself behind when Apparating", "Landing in the wrong county", "Apparating into a wall", "Arriving before you left"], answer: 0 },

  /* ── the castle and the world ── */
  { prompt: "Where is the entrance to the Chamber of Secrets?", options: ["A girls' bathroom", "The dungeons", "Behind a portrait", "Under the lake"], answer: 0 },
  { prompt: "What guards the Gryffindor common room?", options: ["The Fat Lady", "A suit of armour", "A riddle", "A stone gargoyle"], answer: 0 },
  { prompt: "How do you enter the Ravenclaw common room?", options: ["Answer a riddle", "Give a password", "Bow to the eagle", "Knock three times"], answer: 0 },
  { prompt: "What is the Hufflepuff common room next to?", options: ["The kitchens", "The greenhouses", "The library", "The lake"], answer: 0 },
  { prompt: "Where is the Order of the Phoenix's headquarters?", options: ["Twelve Grimmauld Place", "The Burrow", "Hogwarts", "Shell Cottage"], answer: 0 },
  { prompt: "What is St Mungo's disguised as?", options: ["A closed department store", "A derelict church", "A public library", "An empty warehouse"], answer: 0 },
  { prompt: "How do you reach Diagon Alley from the Leaky Cauldron?", options: ["Tap the bricks behind the pub", "Say the password", "Walk through the fireplace", "Use a Portkey"], answer: 0 },
  { prompt: "What is Knockturn Alley known for?", options: ["Dark artefacts", "Second-hand robes", "Quidditch supplies", "Owls"], answer: 0 },
  { prompt: "How many staircases does Hogwarts have?", options: ["142", "99", "108", "76"], answer: 0 },
  { prompt: "What does the Hogwarts motto warn against?", options: ["Tickling a sleeping dragon", "Trusting a stranger's wand", "Walking the forest at night", "Believing a portrait"], answer: 0 },
  { prompt: "Which village near Hogwarts has no Muggles at all?", options: ["Hogsmeade", "Godric's Hollow", "Ottery St Catchpole", "Little Hangleton"], answer: 0 },
  { prompt: "Where did Harry's parents die?", options: ["Godric's Hollow", "Little Hangleton", "Ottery St Catchpole", "Spinner's End"], answer: 0 },
  { prompt: "Where does Snape live?", options: ["Spinner's End", "Godric's Hollow", "Little Whinging", "Hogsmeade"], answer: 0 },
  { prompt: "What is the Dursleys' address?", options: ["Four Privet Drive", "Twelve Grimmauld Place", "Nine Wisteria Walk", "Two Magnolia Crescent"], answer: 0 },
  { prompt: "What does Vernon Dursley's company make?", options: ["Drills", "Cars", "Biscuits", "Furniture"], answer: 0 },
  { prompt: "How do you enter the Ministry of Magic as a visitor?", options: ["A red telephone box", "A public toilet", "A lift in Whitehall", "A hidden staircase"], answer: 0 },
  { prompt: "Where is the Hall of Prophecy?", options: ["The Department of Mysteries", "Gringotts", "Hogwarts", "The Wizengamot chamber"], answer: 0 },
  { prompt: "What stands in the Ministry's atrium?", options: ["The Fountain of Magical Brethren", "A statue of Merlin", "A great clock", "A memorial to the fallen"], answer: 0 },
  { prompt: "Where did Bill and Fleur live after their wedding?", options: ["Shell Cottage", "The Burrow", "Grimmauld Place", "Godric's Hollow"], answer: 0 },
  { prompt: "Which pub does Aberforth Dumbledore run?", options: ["The Hog's Head", "The Three Broomsticks", "The Leaky Cauldron", "The Hanged Man"], answer: 0 },
  { prompt: "What is the wizarding sweet shop in Hogsmeade called?", options: ["Honeydukes", "Zonko's", "Gladrags", "Dervish and Banges"], answer: 0 },
  { prompt: "Which building in Hogsmeade was built for a werewolf?", options: ["The Shrieking Shack", "The Hog's Head", "Zonko's", "The station house"], answer: 0 },
  { prompt: "What is at 93 Diagon Alley?", options: ["Weasleys' Wizard Wheezes", "Ollivanders", "Flourish and Blotts", "Gringotts"], answer: 0 },

  /* ── people ── */
  { prompt: "What is Dumbledore's full first name and middle names?", options: ["Albus Percival Wulfric Brian", "Albus Brian Wulfric Percival", "Albus Wulfric Percival Brian", "Albus Peverell Wulfric Brian"], answer: 0 },
  { prompt: "Whom did Dumbledore famously defeat in 1945?", options: ["Gellert Grindelwald", "Tom Riddle", "Herpo the Foul", "Emeric the Evil"], answer: 0 },
  { prompt: "Who is the Half-Blood Prince's mother?", options: ["Eileen Prince", "Irma Pince", "Eileen Snape", "Elladora Prince"], answer: 0 },
  { prompt: "Who was Headmaster of Hogwarts when Tom Riddle was a student?", options: ["Armando Dippet", "Albus Dumbledore", "Phineas Nigellus Black", "Dilys Derwent"], answer: 0 },
  { prompt: "Who is R.A.B.?", options: ["Regulus Arcturus Black", "Rodolphus Antonin Black", "Regulus Alphard Black", "Rabastan Aurelius Black"], answer: 0 },
  { prompt: "Which house-elf retrieved the real locket?", options: ["Kreacher", "Dobby", "Winky", "Hokey"], answer: 0 },
  { prompt: "Who stole the locket from Grimmauld Place?", options: ["Mundungus Fletcher", "Dolores Umbridge", "Kreacher", "Bellatrix Lestrange"], answer: 0 },
  { prompt: "Who is Nymphadora Tonks's mother?", options: ["Andromeda Black", "Narcissa Black", "Bellatrix Black", "Walburga Black"], answer: 0 },
  { prompt: "What is Tonks's particular gift?", options: ["She is a Metamorphmagus", "She is an Animagus", "She is a Legilimens", "She is a Seer"], answer: 0 },
  { prompt: "Who was the Potters' Secret-Keeper?", options: ["Peter Pettigrew", "Sirius Black", "Remus Lupin", "Albus Dumbledore"], answer: 0, note: "Sirius was the obvious choice, which is exactly why they swapped." },
  { prompt: "Who taught Divination for most of Harry's years?", options: ["Sybill Trelawney", "Firenze", "Aurora Sinistra", "Cassandra Vablatsky"], answer: 0 },
  { prompt: "Who made the prophecy about Harry and Voldemort?", options: ["Sybill Trelawney", "Firenze", "Cassandra Trelawney", "Bathilda Bagshot"], answer: 0 },
  { prompt: "Who overheard part of that prophecy?", options: ["Severus Snape", "Peter Pettigrew", "Igor Karkaroff", "Barty Crouch Jr"], answer: 0 },
  { prompt: "Who was the Minister for Magic before Rufus Scrimgeour?", options: ["Cornelius Fudge", "Pius Thicknesse", "Millicent Bagnold", "Kingsley Shacklebolt"], answer: 0 },
  { prompt: "Who becomes Minister for Magic after the war?", options: ["Kingsley Shacklebolt", "Arthur Weasley", "Harry Potter", "Percy Weasley"], answer: 0 },
  { prompt: "Which Death Eater was impersonating Mad-Eye Moody?", options: ["Barty Crouch Jr", "Igor Karkaroff", "Antonin Dolohov", "Augustus Rookwood"], answer: 0 },
  { prompt: "Who sentenced Barty Crouch Jr to Azkaban?", options: ["His own father", "Cornelius Fudge", "Albus Dumbledore", "Bartemius Crouch Jr himself"], answer: 0 },
  { prompt: "Which Weasley became a curse-breaker for Gringotts?", options: ["Bill", "Charlie", "Percy", "George"], answer: 0 },
  { prompt: "What is Ginny Weasley's profession in the epilogue era?", options: ["Professional Quidditch player, then a sports writer", "Auror", "Healer", "Hogwarts teacher"], answer: 0 },
  { prompt: "Who is Teddy Lupin's godfather?", options: ["Harry Potter", "Ron Weasley", "Kingsley Shacklebolt", "Bill Weasley"], answer: 0 },
  { prompt: "What are Harry and Ginny's three children called?", options: ["James, Albus and Lily", "James, Sirius and Lily", "Albus, Severus and Lily", "James, Albus and Rose"], answer: 0 },
  { prompt: "Who is Aberforth Dumbledore?", options: ["Albus's younger brother", "Albus's father", "Albus's cousin", "Albus's nephew"], answer: 0 },
  { prompt: "What happened to Ariana Dumbledore?", options: ["She was killed in a three-way duel", "She was taken by Grindelwald", "She died of an illness", "She was never born"], answer: 0 },
  { prompt: "Who wrote A History of Magic?", options: ["Bathilda Bagshot", "Adalbert Waffling", "Miranda Goshawk", "Newt Scamander"], answer: 0 },
  { prompt: "Who wrote Fantastic Beasts and Where to Find Them?", options: ["Newt Scamander", "Bathilda Bagshot", "Phyllida Spore", "Arsenius Jigger"], answer: 0 },
  { prompt: "What is Rita Skeeter's unregistered Animagus form?", options: ["A beetle", "A cat", "A magpie", "A moth"], answer: 0 },
  { prompt: "What is McGonagall's Animagus form?", options: ["A tabby cat", "A raven", "A lioness", "An owl"], answer: 0 },
  { prompt: "What did Peter Pettigrew cut off in the graveyard?", options: ["His own right hand", "His left ear", "A finger", "A lock of Harry's hair"], answer: 0 },
  { prompt: "What three things went into Voldemort's rebirth?", options: ["Bone of the father, flesh of the servant, blood of the enemy", "Blood of the father, bone of the servant, flesh of the enemy", "Ash, bone and blood", "Three drops of the enemy's blood"], answer: 0 },
  { prompt: "Who killed Sirius Black?", options: ["Bellatrix Lestrange", "Lucius Malfoy", "Antonin Dolohov", "Voldemort"], answer: 0 },
  { prompt: "Who killed Dobby?", options: ["Bellatrix Lestrange", "Lucius Malfoy", "Greyback", "Voldemort"], answer: 0 },
  { prompt: "Who killed Nagini?", options: ["Neville Longbottom", "Ron Weasley", "Harry Potter", "Molly Weasley"], answer: 0 },
  { prompt: "Who killed Severus Snape?", options: ["Nagini, on Voldemort's order", "Voldemort himself", "Bellatrix Lestrange", "Harry Potter"], answer: 0 },
  { prompt: "What did Snape ask Dumbledore to protect, all those years ago?", options: ["Lily Potter", "Harry Potter", "The Potters entirely", "Himself"], answer: 0, note: "He asked for Lily first, and only then for the rest of them." },

  /* ── plot ── */
  { prompt: "What was hidden in Gringotts vault 713?", options: ["The Philosopher's Stone", "Slytherin's locket", "The Sword of Gryffindor", "Hufflepuff's cup"], answer: 0 },
  { prompt: "Which vault belongs to Harry?", options: ["687", "713", "711", "394"], answer: 0 },
  { prompt: "Who made the Philosopher's Stone?", options: ["Nicolas Flamel", "Albus Dumbledore", "Paracelsus", "Herpo the Foul"], answer: 0 },
  { prompt: "What does the Mirror of Erised show?", options: ["Your deepest desire", "Your future", "Your true self", "Your greatest fear"], answer: 0 },
  { prompt: "How did Harry get the Stone out of the Mirror?", options: ["He wanted to find it, not use it", "He asked Dumbledore", "He broke the glass", "He used a summoning charm"], answer: 0 },
  { prompt: "Which obstacle protecting the Stone did Snape set?", options: ["A riddle about potions", "A giant chess set", "Devil's Snare", "Winged keys"], answer: 0 },
  { prompt: "Who opened the Chamber of Secrets in Harry's second year?", options: ["Ginny Weasley, under the diary's control", "Draco Malfoy", "Tom Riddle in person", "Lucius Malfoy"], answer: 0 },
  { prompt: "Whose memory charm went wrong with a broken wand?", options: ["Gilderoy Lockhart's", "Ron Weasley's", "Professor Flitwick's", "Barty Crouch Sr's"], answer: 0 },
  { prompt: "What did Hermione use to attend extra classes in her third year?", options: ["A Time-Turner", "A Portkey", "A Room of Requirement", "An extension charm"], answer: 0 },
  { prompt: "What did Scabbers really turn out to be?", options: ["Peter Pettigrew", "Barty Crouch Jr", "A Boggart", "An enchanted rat"], answer: 0 },
  { prompt: "Which finger was missing from Pettigrew's rat form?", options: ["A toe", "An ear", "A tail", "An eye"], answer: 0, note: "He cut off a finger to fake his own death, so the rat was missing a toe." },
  { prompt: "Who put Harry's name in the Goblet of Fire?", options: ["Barty Crouch Jr", "Igor Karkaroff", "Ludo Bagman", "Severus Snape"], answer: 0 },
  { prompt: "What did the golden egg contain?", options: ["A merpeople's song, audible underwater", "A map of the maze", "A riddle in Latin", "A key"], answer: 0 },
  { prompt: "Whom did Harry rescue in the second task?", options: ["Ron Weasley", "Hermione Granger", "Ginny Weasley", "Gabrielle Delacour"], answer: 0 },
  { prompt: "How did Harry breathe underwater in the second task?", options: ["Gillyweed", "A Bubble-Head Charm", "A potion from Snape", "He transfigured his lungs"], answer: 0 },
  { prompt: "What was the Triwizard Cup?", options: ["A Portkey", "A Horcrux", "An ordinary trophy", "A Time-Turner"], answer: 0 },
  { prompt: "Who did Hermione go to the Yule Ball with?", options: ["Viktor Krum", "Ron Weasley", "Neville Longbottom", "Cormac McLaggen"], answer: 0 },
  { prompt: "What punishment did Umbridge use in detention?", options: ["A quill that cut the writer's own hand", "Lines with ordinary ink", "Cleaning the trophy room", "Copying out the school rules aloud"], answer: 0 },
  { prompt: "How did the DA members communicate meeting times?", options: ["Enchanted coins", "Owls", "The Marauder's Map", "Notes in the library"], answer: 0 },
  { prompt: "Who betrayed the DA to Umbridge?", options: ["Marietta Edgecombe", "Cho Chang", "Zacharias Smith", "Michael Corner"], answer: 0 },
  { prompt: "What appeared on the traitor's face?", options: ["The word SNEAK in pustules", "A black mark", "Nothing at all", "Boils that spelt her name"], answer: 0 },
  { prompt: "Who suggested the name Dumbledore's Army?", options: ["Ginny Weasley", "Hermione Granger", "Fred Weasley", "Luna Lovegood"], answer: 0 },
  { prompt: "What happened to Umbridge in the Forbidden Forest?", options: ["The centaurs carried her off", "She was petrified", "Grawp ate her hat", "She Apparated away"], answer: 0 },
  { prompt: "How did Harry and his friends get to the Ministry in Order of the Phoenix?", options: ["Thestrals", "Floo powder", "A Portkey", "The Knight Bus"], answer: 0 },
  { prompt: "What was Draco's task in Half-Blood Prince?", options: ["To kill Dumbledore", "To open the Chamber", "To steal the prophecy", "To poison Slughorn"], answer: 0 },
  { prompt: "How did the Death Eaters get into Hogwarts?", options: ["A pair of Vanishing Cabinets", "A secret passage from Hogsmeade", "Polyjuice Potion", "The Room of Requirement's front door"], answer: 0 },
  { prompt: "What did Dumbledore drink in the cave?", options: ["A potion that caused unbearable visions", "Poison", "Water from the lake", "Nothing — he refused"], answer: 0 },
  { prompt: "What was guarding the lake in the cave?", options: ["Inferi", "Dementors", "Acromantulas", "A basilisk"], answer: 0 },
  { prompt: "What was the locket in the cave?", options: ["A fake, with a note inside", "The real Horcrux", "Empty", "Hufflepuff's cup in disguise"], answer: 0 },
  { prompt: "What was the Unbreakable Vow Snape made with Narcissa?", options: ["To finish Draco's task if he failed", "To keep Draco out of Azkaban", "Never to speak of the plan", "To protect Draco from Voldemort"], answer: 0 },
  { prompt: "What is the Taboo?", options: ["A curse on saying Voldemort's name", "A ban on Muggle-borns", "A jinx on the Ministry's doors", "A charm that reveals lies"], answer: 0 },
  { prompt: "Who cast the doe Patronus that led Harry to the sword?", options: ["Severus Snape", "Albus Dumbledore", "Lily Potter's memory", "Aberforth Dumbledore"], answer: 0 },
  { prompt: "Where was the Sword of Gryffindor hidden?", options: ["At the bottom of a frozen forest pool", "In Dumbledore's office", "In Gringotts", "In the Room of Requirement"], answer: 0 },
  { prompt: "Who destroyed Slytherin's locket?", options: ["Ron Weasley", "Harry Potter", "Hermione Granger", "Neville Longbottom"], answer: 0 },
  { prompt: "Who destroyed Hufflepuff's cup?", options: ["Hermione Granger", "Ron Weasley", "Harry Potter", "Griphook"], answer: 0 },
  { prompt: "What destroyed Ravenclaw's diadem?", options: ["Crabbe's Fiendfyre", "The Sword of Gryffindor", "A Basilisk fang", "Harry's wand"], answer: 0 },
  { prompt: "What curses were on Bellatrix's vault?", options: ["Gemino and Flagrante", "Protego and Repello", "Confringo and Incendio", "Caterwauling and Anti-Disapparition"], answer: 0 },
  { prompt: "How did the three escape Gringotts?", options: ["On the back of a blind dragon", "By Apparating", "Through the Thief's Downfall", "In a cart"], answer: 0 },
  { prompt: "Who let Harry into Hogwarts for the final battle?", options: ["Aberforth Dumbledore", "Neville Longbottom", "Minerva McGonagall", "Argus Filch"], answer: 0 },
  { prompt: "Which portrait hid the passage into Hogwarts?", options: ["Ariana Dumbledore's", "Phineas Nigellus Black's", "The Fat Lady's", "Dilys Derwent's"], answer: 0 },
  { prompt: "On what date was the Battle of Hogwarts fought?", options: ["2 May 1998", "31 October 1997", "24 June 1996", "1 September 1998"], answer: 0 },
  { prompt: "Where does Harry go after Voldemort's curse hits him in the forest?", options: ["A version of King's Cross station", "The Department of Mysteries", "Godric's Hollow", "The Room of Requirement"], answer: 0 },
  { prompt: "What finally killed Voldemort?", options: ["His own rebounding curse", "Harry's Killing Curse", "The Sword of Gryffindor", "Neville's blade"], answer: 0 },
  { prompt: "Why did the Elder Wand not work properly for Voldemort?", options: ["Its allegiance had passed to Harry, through Draco", "It had been broken", "It only serves its maker", "Dumbledore had cursed it"], answer: 0 },
  { prompt: "Whom did Draco disarm, taking the Elder Wand's allegiance?", options: ["Albus Dumbledore", "Severus Snape", "Harry Potter", "Bellatrix Lestrange"], answer: 0 },
  { prompt: "Who owned the Elder Wand before Dumbledore?", options: ["Gellert Grindelwald", "Gregorovitch", "Antioch Peverell", "Armando Dippet"], answer: 0 },
  { prompt: "From whom did Grindelwald steal the Elder Wand?", options: ["Gregorovitch", "Ollivander", "Dumbledore", "Dippet"], answer: 0 },
  { prompt: "What did Harry do with the Elder Wand at the end?", options: ["Returned it to Dumbledore's tomb", "Broke it in half", "Threw it into the lake", "Kept it"], answer: 0 },
  { prompt: "Where did Harry drop the Resurrection Stone?", options: ["In the Forbidden Forest", "In the lake", "In Dumbledore's tomb", "At King's Cross"], answer: 0 },

  /* ── school life ── */
  { prompt: "What do O.W.L.s stand for?", options: ["Ordinary Wizarding Levels", "Official Wizarding Licences", "Outstanding Wizarding Learnings", "Ordinary Wandwork Levels"], answer: 0 },
  { prompt: "What do N.E.W.T.s stand for?", options: ["Nastily Exhausting Wizarding Tests", "National Examinations in Wizarding Theory", "Notably Exacting Wizarding Trials", "New Elective Wizarding Topics"], answer: 0 },
  { prompt: "Which is the lowest passing O.W.L. grade?", options: ["Acceptable", "Poor", "Dreadful", "Troll"], answer: 0 },
  { prompt: "What is the lowest grade of all?", options: ["Troll", "Dreadful", "Poor", "Abysmal"], answer: 0 },
  { prompt: "At what age do wizards take their Apparition test?", options: ["Seventeen", "Sixteen", "Eighteen", "Fifteen"], answer: 0 },
  { prompt: "What time does the Hogwarts Express leave King's Cross?", options: ["Eleven o'clock", "Nine o'clock", "Noon", "Half past ten"], answer: 0 },
  { prompt: "Which subject is compulsory for the first five years?", options: ["Potions", "Divination", "Care of Magical Creatures", "Muggle Studies"], answer: 0 },
  { prompt: "Which class did Hermione drop in a temper?", options: ["Divination", "Muggle Studies", "Arithmancy", "Ancient Runes"], answer: 0 },
  { prompt: "What is Arithmancy?", options: ["Magic worked through numbers", "The study of ancient wands", "Predicting the future by the stars", "Reading runes"], answer: 0 },
  { prompt: "How are house points displayed in the entrance hall?", options: ["Giant hourglasses of coloured stones", "A painted scoreboard", "Four banners", "A chalked list"], answer: 0 },
  { prompt: "What is written on the Sorting Hat's brim?", options: ["Nothing — it sings instead", "The founders' names", "A riddle", "The school motto"], answer: 0 },
  { prompt: "Which house did the Sorting Hat first consider for Harry?", options: ["Slytherin", "Ravenclaw", "Hufflepuff", "It never hesitated"], answer: 0 },
  { prompt: "Whose old wand did Neville use until his fifth year?", options: ["His father's", "His grandmother's", "His uncle Algie's", "One bought second-hand"], answer: 0 },
  { prompt: "What did Neville's uncle do to prove he had magic?", options: ["Dropped him out of a window", "Left him in a forest", "Set his robes alight", "Locked him in a cellar"], answer: 0 },
  { prompt: "What is a Squib?", options: ["Someone born to magical parents with no magic", "A wizard who has lost his magic", "A Muggle who knows about magic", "A failed Animagus"], answer: 0 },
  { prompt: "What course did Filch secretly take?", options: ["Kwikspell", "Basic Charms by Owl", "Wizarding Correspondence", "Spells for Squibs"], answer: 0 },
  { prompt: "What is a Howler?", options: ["A letter that shouts its message aloud", "A cursed envelope", "An alarm charm", "A wailing ghost"], answer: 0 },
  { prompt: "What flavour is definitely in Bertie Bott's Every Flavour Beans?", options: ["Every flavour, earwax included", "Only sweet flavours", "Twenty flavours exactly", "Whatever you are thinking of"], answer: 0 },
  { prompt: "What do you find inside a Chocolate Frog?", options: ["A collectable card of a famous witch or wizard", "A riddle", "A small toy", "Nothing"], answer: 0 },
  { prompt: "Which team does Ron support?", options: ["The Chudley Cannons", "Puddlemere United", "The Holyhead Harpies", "The Wimbourne Wasps"], answer: 0 },
  { prompt: "Which team did Ginny play for professionally?", options: ["The Holyhead Harpies", "The Chudley Cannons", "Puddlemere United", "The Tutshill Tornados"], answer: 0 },
  { prompt: "Which country won the Quidditch World Cup Harry attended?", options: ["Ireland", "Bulgaria", "England", "Egypt"], answer: 0, note: "Ireland won, even though Krum caught the Snitch." },
  { prompt: "Who caught the Snitch in that final?", options: ["Viktor Krum", "Aidan Lynch", "Nobody did", "Troy"], answer: 0 },
  { prompt: "How many fouls are there in Quidditch?", options: ["700", "300", "100", "27"], answer: 0 },
  { prompt: "What position did Charlie Weasley play?", options: ["Seeker", "Keeper", "Beater", "Chaser"], answer: 0 },
  { prompt: "What position did Oliver Wood play?", options: ["Keeper", "Seeker", "Beater", "Chaser"], answer: 0 },
  { prompt: "Which broom did Sirius send Harry?", options: ["A Firebolt", "A Nimbus 2001", "A Comet 260", "A Cleansweep Seven"], answer: 0 },
  { prompt: "Who bought the Slytherin team Nimbus 2001s?", options: ["Lucius Malfoy", "Severus Snape", "Marcus Flint's father", "The school"], answer: 0 },
  { prompt: "Which of these did Fred and George invent?", options: ["Skiving Snackboxes", "The Deluminator", "Extendable ears — bought, not made", "The Marauder's Map"], answer: 0 },
  { prompt: "What does a Puking Pastille do?", options: ["Makes you sick, then well again at the other end", "Turns your skin green", "Makes you faint", "Gives you a nosebleed"], answer: 0 },
  { prompt: "What is a Sneakoscope for?", options: ["Detecting untrustworthy people nearby", "Seeing through walls", "Finding lost things", "Recording conversations"], answer: 0 },
  { prompt: "What does a Remembrall do?", options: ["Turns red when you have forgotten something", "Tells you what you forgot", "Stores a memory", "Reminds you of a name"], answer: 0, note: "It never tells you what — which is Neville's whole problem with it." },
  { prompt: "What is a Deluminator?", options: ["It takes light from a source and returns it", "It makes light", "It reveals hidden doors", "It shrinks objects"], answer: 0 },
  { prompt: "What did the Weasleys' flying car become?", options: ["Wild, and living in the Forbidden Forest", "Scrap in Hagrid's yard", "Confiscated by the Ministry", "Repaired and sold"], answer: 0 },
];
