import type { OddOneOutItem } from "@curio/core";

/** Three belong together, one doesn't, and `why` says so on the reveal. */
export const oddOneOut: OddOneOutItem[] = [
  { items: ["Gryffindor", "Slytherin", "Ravenclaw", "Durmstrang"], answer: 3, why: "Durmstrang is a school, not a Hogwarts house." },
  { items: ["Quaffle", "Bludger", "Snitch", "Portkey"], answer: 3, why: "A Portkey isn't a Quidditch ball." },
  { items: ["Moony", "Wormtail", "Padfoot", "Nagini"], answer: 3, why: "The other three are Marauders' nicknames." },
  { items: ["The diary", "The locket", "The cup", "The Sorting Hat"], answer: 3, why: "The Sorting Hat was never a Horcrux." },
  { items: ["Hedwig", "Errol", "Pigwidgeon", "Crookshanks"], answer: 3, why: "Crookshanks is a cat; the rest are owls." },
  { items: ["Lumos", "Incendio", "Protego", "Felix Felicis"], answer: 3, why: "Felix Felicis is a potion, not a spell." },
  { items: ["Fang", "Fluffy", "Aragog", "Fawkes"], answer: 3, why: "Fawkes was Dumbledore's; the rest were Hagrid's." },
  { items: ["Snape", "McGonagall", "Flitwick", "Ollivander"], answer: 3, why: "Ollivander never taught at Hogwarts." },
  { items: ["Elder Wand", "Invisibility Cloak", "Resurrection Stone", "Time-Turner"], answer: 3, why: "A Time-Turner isn't a Deathly Hallow." },
  { items: ["Beauxbatons", "Durmstrang", "Hogwarts", "Ilvermorny"], answer: 3, why: "Ilvermorny didn't compete in the Triwizard Tournament." },
  { items: ["Fred", "George", "Percy", "Cedric"], answer: 3, why: "Cedric isn't a Weasley." },
  { items: ["Dementor", "Boggart", "Thestral", "Patronus"], answer: 3, why: "A Patronus is a charm, not a creature." },
  { items: ["Galleon", "Sickle", "Knut", "Florin"], answer: 3, why: "There's no wizarding Florin." },
  { items: ["Quirrell", "Lockhart", "Lupin", "Slughorn"], answer: 3, why: "Slughorn taught Potions, not Defence Against the Dark Arts." },
  { items: ["Bill", "Charlie", "Ginny", "Tonks"], answer: 3, why: "Tonks was born a Black, not a Weasley." },
  { items: ["Amortentia", "Polyjuice", "Veritaserum", "Deluminator"], answer: 3, why: "A Deluminator is a device, not a potion." },
  { items: ["Boggart", "Dementor", "Inferius", "Niffler"], answer: 3, why: "A Niffler is a living beast; the others never really were." },
  { items: ["Moaning Myrtle", "The Grey Lady", "The Bloody Baron", "Peeves"], answer: 3, why: "Peeves is a poltergeist. The rest are ghosts." },
  { items: ["Acromantula", "Grindylow", "Basilisk", "Merperson"], answer: 3, why: "Merpeople are Beings; the rest are Beasts." },
  { items: ["Avada Kedavra", "Crucio", "Imperio", "Sectumsempra"], answer: 3, why: "Sectumsempra is vicious, but not an Unforgivable Curse." },
  { items: ["Phoenix feather", "Unicorn hair", "Dragon heartstring", "Basilisk fang"], answer: 3, why: "The other three are wand cores." },
  { items: ["The Leaky Cauldron", "The Three Broomsticks", "The Hog's Head", "Flourish and Blotts"], answer: 3, why: "Flourish and Blotts sells books, not drinks." },
  { items: ["Floo Powder", "Portkey", "Apparition", "Patronus"], answer: 3, why: "A Patronus is a defence, not a way of travelling." },
  { items: ["Gryffindor Tower", "The Dungeons", "The Astronomy Tower", "Diagon Alley"], answer: 3, why: "Diagon Alley is not inside the castle." },
  { items: ["Mandrake", "Devil's Snare", "Gillyweed", "Grindylow"], answer: 3, why: "A Grindylow is a creature; the rest are plants." },
  { items: ["Fang", "Fluffy", "Buckbeak", "Crookshanks"], answer: 3, why: "Crookshanks was Hermione's; the others were Hagrid's." },
  { items: ["Bellatrix", "Lucius", "Dolohov", "Kingsley"], answer: 3, why: "Kingsley was in the Order, not among the Death Eaters." },
  { items: ["Riddikulus", "Lumos", "Accio", "Amortentia"], answer: 3, why: "Amortentia is a potion, not a spell." },

  /* ── for the ones who read the books twice ── */
  { items: ["Antioch", "Cadmus", "Ignotus", "Cadogan"], answer: 3, why: "The other three are the Peverell brothers; Sir Cadogan is a portrait." },
  { items: ["Marvolo", "Morfin", "Merope", "Mundungus"], answer: 3, why: "The other three are Gaunts." },
  { items: ["Kendra", "Percival", "Ariana", "Bathilda"], answer: 3, why: "The other three are Dumbledores; Bathilda Bagshot was only the neighbour." },
  { items: ["Fudge", "Scrimgeour", "Thicknesse", "Dippet"], answer: 3, why: "Dippet ran Hogwarts; the rest ran the Ministry." },
  { items: ["Dippet", "Dumbledore", "Snape", "Slughorn"], answer: 3, why: "The other three were Headmasters." },
  { items: ["Harry", "Ron", "Hermione", "Ginny"], answer: 3, why: "The other three each destroyed a Horcrux. Ginny was possessed by one." },
  { items: ["Chudley Cannons", "Holyhead Harpies", "Puddlemere United", "Wimbourne Wanderers"], answer: 3, why: "The team is the Wimbourne Wasps." },
  { items: ["Sirius", "Peter", "James", "Remus"], answer: 3, why: "The other three were Animagi; Remus could not choose his change." },
  { items: ["Rita Skeeter", "McGonagall", "Sirius", "Tonks"], answer: 3, why: "Tonks is a Metamorphmagus, not an Animagus." },
  { items: ["Ariana", "Ignotus", "Kendra", "Percival"], answer: 1, why: "Ignotus Peverell is buried at Godric's Hollow too, but he is not a Dumbledore." },
  { items: ["The Veil", "The Time Room", "The Hall of Prophecy", "The Room of Requirement"], answer: 3, why: "The other three are in the Department of Mysteries." },
  { items: ["Gemino", "Flagrante", "Thief's Downfall", "Felix Felicis"], answer: 3, why: "The other three guard Gringotts; Felix Felicis is a potion." },
  { items: ["Puking Pastilles", "Fainting Fancies", "Nosebleed Nougat", "Fizzing Whizbees"], answer: 3, why: "Fizzing Whizbees are Honeydukes sweets; the rest are Skiving Snackbox." },
  { items: ["Bertie Bott's", "Chocolate Frogs", "Acid Pops", "Butterbeer"], answer: 3, why: "Butterbeer is a drink." },
  { items: ["Hermione", "Ginny", "Luna", "Cho"], answer: 3, why: "The other three fought in the Department of Mysteries." },
  { items: ["Lavender Brown", "Bill Weasley", "Remus Lupin", "Peter Pettigrew"], answer: 3, why: "The other three were attacked by Fenrir Greyback." },
  { items: ["Ottery St Catchpole", "Godric's Hollow", "Little Hangleton", "Little Whinging"], answer: 3, why: "Little Whinging is where the Dursleys live — the only one with no wizarding history at all." },
  { items: ["Spinner's End", "Shell Cottage", "Grimmauld Place", "Malfoy Manor"], answer: 3, why: "The other three sheltered Harry's side at some point." },
  { items: ["Aragog", "Buckbeak", "Norbert", "Nagini"], answer: 3, why: "Nagini was Voldemort's; the rest were Hagrid's." },
  { items: ["A diary", "A ring", "A locket", "A wand"], answer: 3, why: "The other three were Horcruxes." },
  { items: ["Hepzibah Smith", "Frank Bryce", "Bertha Jorkins", "Hokey"], answer: 3, why: "Voldemort killed the other three. Hokey the house-elf was only framed for one of them." },
  { items: ["Outstanding", "Exceeds Expectations", "Acceptable", "Dreadful"], answer: 3, why: "Dreadful is a fail; the rest are passes." },
  { items: ["Arithmancy", "Ancient Runes", "Muggle Studies", "Transfiguration"], answer: 3, why: "The other three are electives; Transfiguration is compulsory." },
  { items: ["Gubraithian fire", "Fiendfyre", "Bluebell flames", "Incendio"], answer: 3, why: "Incendio is a plain spell; the other three are particular kinds of magical fire." },
];
