import type { TrueFalseItem } from "@curio/core";

/**
 * A statement to accept or reject. `note` explains the trap on a miss.
 *
 * The good false statements are the ones a filmgoer would accept — the film
 * gave Harry's parents the wrong headstone, put the diadem's destruction in
 * the wrong hands, and skipped the reason the Elder Wand answered to Harry.
 * Book canon decides.
 */
export const truefalse: TrueFalseItem[] = [
  /* ── the easy end ── */
  { statement: "Hedwig is a snowy owl.", answer: true },
  { statement: "Peeves is a ghost.", answer: false, note: "He's a poltergeist — never alive to begin with." },
  { statement: "Argus Filch is a Squib.", answer: true },
  { statement: "Fawkes is a griffin.", answer: false, note: "Fawkes is a phoenix." },
  { statement: "Sirius Black is Harry's godfather.", answer: true },
  { statement: "Draco Malfoy was sorted into Ravenclaw.", answer: false, note: "Slytherin, and instantly." },
  { statement: "Moaning Myrtle haunts a girls' bathroom.", answer: true },
  { statement: "Hagrid was expelled from Hogwarts as a student.", answer: true },
  { statement: "Nagini is Voldemort's cat.", answer: false, note: "Nagini is a snake." },
  { statement: "Dementors guard Azkaban.", answer: true },
  { statement: "Firenze the centaur taught Divination.", answer: true },
  { statement: "The Knight Bus is triple-decker and purple.", answer: true },
  { statement: "Umbridge decorates her office with kitten plates.", answer: true },
  { statement: "Butterbeer is sold at the Three Broomsticks.", answer: true },
  { statement: "Viktor Krum attended Beauxbatons.", answer: false, note: "Durmstrang." },
  { statement: "Luna Lovegood is a Ravenclaw.", answer: true },
  { statement: "The Whomping Willow hides a passage to Hogsmeade.", answer: true },
  { statement: "Cho Chang played Beater for Ravenclaw.", answer: false, note: "She was a Seeker." },
  { statement: "Bill Weasley worked as a curse-breaker for Gringotts.", answer: true },
  { statement: "A Niffler is attracted to anything shiny.", answer: true },
  { statement: "Godric's Hollow is where Harry's parents died.", answer: true },
  { statement: "Slughorn was Head of Ravenclaw house.", answer: false, note: "Slytherin." },
  { statement: "Fluffy has three heads.", answer: true },
  { statement: "A Patronus takes the form of an animal.", answer: true },
  { statement: "Crookshanks is part Kneazle.", answer: true },
  { statement: "Trevor belongs to Neville.", answer: true },
  { statement: "Errol is the Weasleys' owl.", answer: true },

  /* ── creatures and magic ── */
  { statement: "A Boggart takes the shape of whatever the person facing it fears most.", answer: true },
  { statement: "Riddikulus destroys a Boggart outright.", answer: false, note: "Laughter is what finishes it, not the spell alone." },
  { statement: "Nobody knows what a Boggart looks like when it is alone.", answer: true },
  { statement: "Dementors are blind.", answer: true, note: "They sense feeling rather than sight." },
  { statement: "Basilisk venom can destroy a Horcrux.", answer: true },
  { statement: "A phoenix's tears can heal wounds.", answer: true },
  { statement: "Wizards can Apparate inside Hogwarts.", answer: false, note: "House-elves can; wizards cannot." },
  { statement: "The Whomping Willow was planted for Remus Lupin.", answer: true },
  { statement: "Centaurs live in the Forbidden Forest.", answer: true },
  { statement: "Acromantulas can speak.", answer: true },
  { statement: "Gillyweed gives the eater gills.", answer: true },
  { statement: "Grindylows live in the Black Lake.", answer: true },
  { statement: "The Marauder's Map shows the Room of Requirement.", answer: false, note: "It is the one room the map never found." },
  { statement: "Veritaserum is regulated by the Ministry.", answer: true },
  { statement: "A house-elf can be freed by being given clothes.", answer: true },
  { statement: "Inferi are ghosts.", answer: false, note: "They are corpses made to move." },
  { statement: "Buckbeak was sentenced to death.", answer: true },
  { statement: "Norbert turned out to be female.", answer: true, note: "Norbert became Norberta." },
  { statement: "A werewolf is dangerous to humans at any time of the month.", answer: false, note: "Only at the full moon — Lupin taught the class this himself." },
  { statement: "Wolfsbane Potion cures lycanthropy.", answer: false, note: "It only lets the wolf keep a human mind." },
  { statement: "Unicorn blood will keep you alive even at death's door.", answer: true, note: "At the price of a cursed half-life." },
  { statement: "Thestrals are invisible to anyone who has not seen death.", answer: true },
  { statement: "The carriages to Hogwarts pull themselves.", answer: false, note: "Thestrals pull them; most students simply cannot see them." },
  { statement: "There are exactly three Unforgivable Curses.", answer: true },
  { statement: "Fiendfyre can be put out with water.", answer: false, note: "It is cursed fire, and very nearly unstoppable." },
  { statement: "A Portkey can be any ordinary object.", answer: true },
  { statement: "Polyjuice Potion works on animals.", answer: false, note: "It is meant for human transformation; Hermione's cat hair proved the point." },
  { statement: "Amortentia creates real love.", answer: false, note: "It creates obsession, which is not the same thing." },
  { statement: "A bezoar comes from the stomach of a goat.", answer: true },
  { statement: "Felix Felicis is safe to take often.", answer: false, note: "It is toxic in quantity, and banned in competition." },

  /* ── people ── */
  { statement: "Dumbledore's first name is Albus.", answer: true },
  { statement: "Dumbledore defeated Grindelwald in 1945.", answer: true },
  { statement: "Dumbledore and Grindelwald were once friends.", answer: true },
  { statement: "Aberforth is Albus Dumbledore's brother.", answer: true },
  { statement: "Snape's Patronus was a stag.", answer: false, note: "A doe — Lily's." },
  { statement: "Snape was Head of Slytherin house.", answer: true },
  { statement: "Snape's mother was a witch called Eileen Prince.", answer: true },
  { statement: "Lily Evans and Severus Snape grew up near each other.", answer: true },
  { statement: "James Potter was a Seeker.", answer: false, note: "He played Chaser." },
  { statement: "Harry inherited his mother's eyes.", answer: true },
  { statement: "Sirius Black was the Potters' Secret-Keeper.", answer: false, note: "They swapped to Pettigrew, which is what made the betrayal work." },
  { statement: "Sirius Black was tried before being sent to Azkaban.", answer: false, note: "He never got a trial at all." },
  { statement: "Sirius left Grimmauld Place to Harry.", answer: true },
  { statement: "Peter Pettigrew spent twelve years as the Weasleys' pet rat.", answer: true },
  { statement: "Tonks is a Metamorphmagus.", answer: true },
  { statement: "Tonks and Lupin had a son.", answer: true, note: "Teddy, whose godfather is Harry." },
  { statement: "Bellatrix Lestrange is Narcissa Malfoy's sister.", answer: true },
  { statement: "Andromeda Tonks was disowned by the Blacks.", answer: true },
  { statement: "Regulus Black died a Death Eater in good standing.", answer: false, note: "He turned, stole the locket and left the note signed R.A.B." },
  { statement: "Kreacher was Regulus Black's house-elf first.", answer: true },
  { statement: "Neville's parents were killed by Bellatrix Lestrange.", answer: false, note: "Tortured to insanity, not killed — they are alive at St Mungo's." },
  { statement: "Neville was born the day before Harry.", answer: true, note: "30 July; Harry on the 31st. The prophecy could have meant either of them." },
  { statement: "Luna's father edits The Quibbler.", answer: true },
  { statement: "Percy Weasley worked for Barty Crouch Sr.", answer: true },
  { statement: "Arthur Weasley works in the Misuse of Muggle Artefacts Office.", answer: true },
  { statement: "Molly Weasley's boggart is a dead body of one of her family.", answer: true },
  { statement: "Fred Weasley survived the Battle of Hogwarts.", answer: false, note: "George survived; Fred did not." },
  { statement: "Colin Creevey died at the Battle of Hogwarts.", answer: true },
  { statement: "Lavender Brown was attacked by Fenrir Greyback.", answer: true },
  { statement: "Bill Weasley became a full werewolf after Greyback attacked him.", answer: false, note: "Greyback was not transformed at the time, so Bill got the scars and a taste for very rare steak, not the condition." },
  { statement: "Rita Skeeter is a registered Animagus.", answer: false, note: "Unregistered, which is exactly what Hermione used against her." },
  { statement: "Minerva McGonagall can turn into a cat.", answer: true },
  { statement: "Ollivander was held prisoner at Malfoy Manor.", answer: true },
  { statement: "Griphook helped break into Gringotts.", answer: true, note: "And then took the sword and left them there." },

  /* ── the plot, precisely ── */
  { statement: "Voldemort made exactly seven Horcruxes on purpose.", answer: false, note: "Six deliberately; Harry was the accident." },
  { statement: "Harry was a Horcrux.", answer: true },
  { statement: "Nagini was a Horcrux.", answer: true },
  { statement: "The Sorting Hat was a Horcrux.", answer: false, note: "It hid the sword; it was never one." },
  { statement: "Dumbledore destroyed the ring Horcrux.", answer: true, note: "And the curse on it was killing him." },
  { statement: "Ron destroyed the locket with the Sword of Gryffindor.", answer: true },
  { statement: "Hermione destroyed Hufflepuff's cup with a Basilisk fang.", answer: true },
  { statement: "Neville destroyed the diadem.", answer: false, note: "Crabbe's Fiendfyre did. Neville killed Nagini." },
  { statement: "The Sword of Gryffindor takes in anything that makes it stronger.", answer: true, note: "Which is why Basilisk venom made it able to destroy a Horcrux." },
  { statement: "The Triwizard Cup was a Portkey.", answer: true },
  { statement: "Barty Crouch Jr put Harry's name in the Goblet of Fire.", answer: true },
  { statement: "Harry entered the Triwizard Tournament of his own accord.", answer: false },
  { statement: "Cedric Diggory was killed by Voldemort personally.", answer: false, note: "Voldemort said \"kill the spare\"; Wormtail cast it." },
  { statement: "The prophecy was made in the Hog's Head.", answer: true },
  { statement: "Snape heard the whole prophecy.", answer: false, note: "He was thrown out partway, which is the hinge the entire war turns on." },
  { statement: "Voldemort chose which boy the prophecy meant.", answer: true, note: "He marked Harry as his equal, and made it true by doing so." },
  { statement: "The Hall of Prophecy is in the Department of Mysteries.", answer: true },
  { statement: "Sirius Black fell through the Veil.", answer: true },
  { statement: "Dumbledore was killed by Draco Malfoy.", answer: false, note: "Draco disarmed him; Snape cast the curse, by arrangement." },
  { statement: "The Elder Wand answered to Harry because he beat Voldemort.", answer: false, note: "Because he disarmed Draco, who had disarmed Dumbledore." },
  { statement: "Voldemort took the Elder Wand from Dumbledore's tomb.", answer: true },
  { statement: "Harry broke the Elder Wand.", answer: false, note: "He returned it to the tomb, meaning to die undefeated and end its line." },
  { statement: "The Resurrection Stone was set in Marvolo Gaunt's ring.", answer: true },
  { statement: "Harry's Invisibility Cloak came from his father.", answer: true },
  { statement: "The Deathly Hallows symbol was invented by Xenophilius Lovegood.", answer: false, note: "He wore it; Grindelwald made it a sign, and the Peverells came long before either." },
  { statement: "Bathilda Bagshot was dead when Harry visited Godric's Hollow.", answer: true, note: "Nagini was wearing her." },
  { statement: "Dobby died at Malfoy Manor.", answer: false, note: "He got them out first, and died at Shell Cottage." },
  { statement: "Harry dug Dobby's grave by hand, without magic.", answer: true },
  { statement: "The Battle of Hogwarts happened in 1998.", answer: true },
  { statement: "Snape was Headmaster of Hogwarts in Harry's seventh year.", answer: true },
  { statement: "Harry became an Auror after the war.", answer: true },
  { statement: "Harry named a son after Snape.", answer: true, note: "Albus Severus." },
  { statement: "Nineteen years pass before the epilogue.", answer: true },

  /* ── school and the wider world ── */
  { statement: "Hogwarts has four houses.", answer: true },
  { statement: "The Sorting Hat once belonged to Godric Gryffindor.", answer: true },
  { statement: "The Sorting Hat sings a new song every year.", answer: true },
  { statement: "First-years travel to the castle by carriage.", answer: false, note: "They cross the lake by boat." },
  { statement: "Hogwarts sits somewhere in Scotland.", answer: true },
  { statement: "Muggles who look at Hogwarts see a ruin with a warning sign.", answer: true },
  { statement: "You can Apparate onto the Hogwarts grounds in an emergency.", answer: false, note: "The anti-Apparition enchantment holds; Dumbledore is the exception nobody else gets." },
  { statement: "Hogwarts has a hundred and forty-two staircases.", answer: true },
  { statement: "O.W.L.s are taken in the fifth year.", answer: true },
  { statement: "A Troll is a passing grade.", answer: false, note: "It is the lowest of the lot." },
  { statement: "The Goblet of Fire is an impartial judge.", answer: true },
  { statement: "The Ministry of Magic is entered through a red telephone box.", answer: true, note: "For visitors. Staff use the fireplaces." },
  { statement: "Gringotts is run by house-elves.", answer: false, note: "Goblins." },
  { statement: "Ireland won the Quidditch World Cup Harry attended.", answer: true, note: "Even though Krum caught the Snitch for Bulgaria." },
  { statement: "Catching the Snitch always wins the match.", answer: false, note: "It is 150 points, and Ireland proved that is not always enough." },
  { statement: "Ollivanders has traded since 382 BC.", answer: true },
  { statement: "The wand chooses the wizard.", answer: true },
  { statement: "Every wand at Ollivanders has a core of phoenix feather, unicorn hair or dragon heartstring.", answer: true },
  { statement: "Chocolate helps after a Dementor attack.", answer: true },
];
