import type { TrueFalseItem } from "@curio/core";

/** A statement to accept or reject. `note` explains the trap on a miss. */
export const truefalse: TrueFalseItem[] = [
  { statement: "Hedwig is a snowy owl.", answer: true },
  { statement: "Peeves is a ghost.", answer: false, note: "He's a poltergeist — never alive to begin with." },
  { statement: "Argus Filch is a Squib.", answer: true },
  { statement: "Fawkes is a griffin.", answer: false, note: "Fawkes is a phoenix." },
  { statement: "Sirius Black is Harry's godfather.", answer: true },
  { statement: "Draco Malfoy was sorted into Ravenclaw.", answer: false, note: "Slytherin, and instantly." },
  { statement: "Moaning Myrtle haunts a girls' bathroom.", answer: true },
  { statement: "Hagrid was expelled from Hogwarts as a student.", answer: true },
  { statement: "Nagini is Voldemort's cat.", answer: false, note: "Nagini is a snake." },
  { statement: "Dementors guard Azkaban.", answer: true },
  { statement: "Firenze the centaur taught Divination.", answer: true },
  { statement: "The Knight Bus is triple-decker and purple.", answer: true },
  { statement: "Umbridge decorates her office with kitten plates.", answer: true },
  { statement: "Butterbeer is sold at the Three Broomsticks.", answer: true },
  { statement: "Viktor Krum attended Beauxbatons.", answer: false, note: "Durmstrang." },
  { statement: "Luna Lovegood is a Ravenclaw.", answer: true },
  { statement: "The Whomping Willow hides a passage to Hogsmeade.", answer: true },
  { statement: "Cho Chang played Beater for Ravenclaw.", answer: false, note: "She was a Seeker." },
  { statement: "Bill Weasley worked as a curse-breaker for Gringotts.", answer: true },
  { statement: "A Niffler is attracted to anything shiny.", answer: true },
  { statement: "Godric's Hollow is where Harry's parents died.", answer: true },
  { statement: "Slughorn was Head of Ravenclaw house.", answer: false, note: "Slytherin." },

  { statement: "A Boggart takes the shape of whoever faces it fears most.", answer: true },
  { statement: "Riddikulus destroys a Boggart outright.", answer: false, note: "Laughter is what finishes it, not the spell alone." },
  { statement: "Nobody knows what a Boggart looks like when it is alone.", answer: true },
  { statement: "Dementors are blind.", answer: true, note: "They sense feeling rather than sight." },
  { statement: "A Patronus takes the form of an animal.", answer: true },
  { statement: "Fluffy has three heads.", answer: true },
  { statement: "Basilisk venom can destroy a Horcrux.", answer: true },
  { statement: "A phoenix's tears can heal wounds.", answer: true },
  { statement: "Wizards can Apparate inside Hogwarts.", answer: false, note: "House-elves can; wizards cannot." },
  { statement: "The Whomping Willow was planted for Remus Lupin.", answer: true },
  { statement: "Centaurs live in the Forbidden Forest.", answer: true },
  { statement: "Acromantulas can speak.", answer: true },
  { statement: "Gillyweed gives the eater gills.", answer: true },
  { statement: "Grindylows live in the Black Lake.", answer: true },
  { statement: "The Marauder's Map shows the Room of Requirement.", answer: false, note: "It is the one room the map never found." },
  { statement: "Veritaserum is regulated by the Ministry.", answer: true },
  { statement: "A house-elf can be freed by being given clothes.", answer: true },
  { statement: "Inferi are ghosts.", answer: false, note: "They are corpses made to move." },
  { statement: "Buckbeak was sentenced to death.", answer: true },
  { statement: "Norbert turned out to be female.", answer: true, note: "Norbert became Norberta." },
];
