import type { UnscrambleItem } from "@curio/core";

/** A jumbled word and the hint that unlocks it. */
export const unscramble: UnscrambleItem[] = [
  { word: "PATRONUS", hint: "Conjured by a happy memory" },
  { word: "HORCRUX", hint: "A hidden fragment of a soul" },
  { word: "THESTRAL", hint: "Only the bereaved can see them" },
  { word: "PENSIEVE", hint: "A stone basin of memories" },
  { word: "PARSELTONGUE", hint: "The language of snakes" },
  { word: "GRINGOTTS", hint: "Run by goblins" },
  { word: "HOGSMEADE", hint: "The all-wizarding village" },
  { word: "ANIMAGUS", hint: "A witch who becomes an animal at will" },
  { word: "BUTTERBEER", hint: "Warm, foamy, faintly alcoholic" },
  { word: "QUIDDITCH", hint: "Played on broomsticks" },
  { word: "BASILISK", hint: "Its gaze kills" },
  { word: "DEMENTOR", hint: "It feeds on happiness" },
  { word: "GRYFFINDOR", hint: "Lion, scarlet and gold" },
  { word: "RAVENCLAW", hint: "Eagle, blue and bronze" },
  { word: "HUFFLEPUFF", hint: "Badger, yellow and black" },
  { word: "SLYTHERIN", hint: "Serpent, green and silver" },
  { word: "AZKABAN", hint: "An island you don't leave" },
  { word: "PORTKEY", hint: "An ordinary object that yanks you away" },
  { word: "OCCLUMENCY", hint: "Sealing the mind against intrusion" },
  { word: "HIPPOGRIFF", hint: "Bow before you approach one" },
  { word: "VERITASERUM", hint: "Three drops and you'll tell the truth" },
  { word: "DEATHSTICK", hint: "Another name for the Elder Wand" },

  { word: "BOGGART", hint: "It becomes what you fear" },
  { word: "NIFFLER", hint: "Empty your pockets before it arrives" },
  { word: "ACROMANTULA", hint: "Eight legs, and far too large" },
  { word: "MANDRAKE", hint: "Wear earmuffs before repotting" },
  { word: "CENTAUR", hint: "Half horse, and reads the stars" },
  { word: "RIDDIKULUS", hint: "Say it, then laugh" },
  { word: "ALOHOMORA", hint: "For a door that will not open" },
  { word: "EXPELLIARMUS", hint: "A wand leaves its owner's hand" },
  { word: "OLLIVANDERS", hint: "Since 382 BC" },
  { word: "KNOCKTURN", hint: "The alley you do not wander into" },
  { word: "GRIMMAULD", hint: "A place, number twelve" },
  { word: "LEGILIMENCY", hint: "Reading a mind from the inside" },
  { word: "APPARITION", hint: "Destination, determination, deliberation" },
  { word: "BUCKBEAK", hint: "Bow first" },
  { word: "GRINDYLOW", hint: "It grips, and it lurks in the lake" },
];
